### ISSUE TITLE
Allow "part of" to refer to its parent library by URI instead of name.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#20792]
Currently a library part must start with:

```dart
part of some.library.name;
```

The is supposed to give a hint about which library the part is part of, but it doesn't give a direct way to find the file. It might require a global search to actually find the file starting with "library some.library.name;" that includes the part.

If it was possible to instead write:

```dart
part of "./thelibrary.dart";
```

then tools could simply and immediately find the library from the part.

See https://github.com/dart-lang/dart_enhancement_proposals/issues/45

- [x] Language (Spec)
- [x] VM
- [x] Analyzer https://github.com/dart-lang/sdk/issues/28522
- [x] dart2js
- [ ] intellij
- [x] dartfmt (https://github.com/dart-lang/dart_style/issues/615)
- [ ] Dart style guide

**Comment by davidmorgan** [comment]
+1

This change would be the perfect complement to the "library name defaults to empty" change. It would allow us to drop library statements altogether and still use part files when needed.

This would be particularly helpful for source_gen since it relies on parts for generated code. https://github.com/dart-lang/source_gen

**Comment by rkj** [comment]
+1

**Comment by sigmundch** [comment]
FYI - we also have a DEP for it - we had discussed it, but I forgot to file it under the DEP repo, so I just did [here][https://github.com/dart-lang/dart_enhancement_proposals/issues/45].

**Comment by zzzev** [comment]
+1

**Comment by BlackHC** [comment]
+1

**Comment by danrubel** [comment]
+1 ... this would allow analysis of part files to be more efficient.

**Comment by davidmorgan** [comment]
Any update on this, please?

**Comment by dgrove** [comment]
@floitschG can you please provide an update?

**Comment by floitschG** [comment]
This feature is accepted by the language team.
The spec hasn't been updated yet, but the DEP for it is ready.
Afaik no implementation has started work on it.

**Comment by floitschG** [comment]
Status update:
This is still an accepted feature, but we won't implement it for 1.50.

**Comment by floitschG** [comment]
This issue is now blocked by https://github.com/dart-lang/sdk/issues/28522

**Comment by davidmorgan** [comment]
Seems like dart_style needs to support this too? https://github.com/dart-lang/dart_style/issues/615

**Comment by floitschG** [comment]
This has been implemented.
We might want to change our own codebase, but that's an independent task.
