### ISSUE TITLE
Implement null-aware operators

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#23454]
The [null-aware operators proposal](https://github.com/dart-lang/dart_enhancement_proposals/issues/9) has been accepted by the DEP committee and is in the Dart language spec. Implementation should be underway, and it doesn't need to be behind any sort of flag.

This is the main tracking issue. Individual issues are below:

- [x] VM: #23455, first released in [1.12.0-dev.0.0](/dart-lang/sdk/releases/tag/1.12.0-dev.0.0)
- [x] support `Class?.x` in the VM: #23794
- [x] implement behind a flag in Analyzer: #23456, first released in [1.10.0](/dart-lang/sdk/releases/tag/1.10.0)
- [x] don't emit an error for `Class?.x` in Analyzer: #23464
- [x] enable by default in Analyzer: #23793
- [x] implement behind a flag in dart2js: #23457, first released in [1.11.0](/dart-lang/sdk/releases/tag/1.11.0)
- [ ] support `Class?.x` in dart2js: #23795
- [x] enable by default in dart2js: #23791, to be released in 1.12.0-dev.3.0
- [ ] Documentation (dart-lang/dartlang.org#1364)

*Edited by @nex3 to match [other similar issues](https://github.com/dart-lang/sdk/labels/meta)*

**Comment by sethladd** [comment]
Request for docs: https://github.com/dart-lang/www.dartlang.org/issues/1400

**Comment by sethladd** [comment]
As of now, looks like dart2js and VM have completed their implementations. Looks like analyzer is real close.

**Comment by stereotype441** [comment]
Analyzer implementation is feature complete.  There is one minor outstanding bug (#23464), but it shouldn't delay anything.

After discussion with Seth, it looks like all that needs to be done is to enable support by default in the VM, analyzer, and dart2js, and to drop the flag `--enable-null-aware-operators` from the tests.  Our aim is to have this switched on by 1.12.

**Comment by nex3** [comment]
@stereotype441 @sethladd are there issues filed to drop the flag?

**Comment by stereotype441** [comment]
@nex3 As far as I'm aware there are no issues filed to drop the flag; in fact, I don't even know how the VM and Dart2js behave if the flag is absent.  It's on my personal TODO list to drop the flag from the tests and modify analyzer to implement the proper behavior by default; once I've done that, if I see that it causes VM and/or Dart2js failures I'll file bugs against those platforms.

**Comment by sigmundch** [comment]
dart2js will show an error message requesting that you provide the flag. But it should be easy to remove it too. I just filed #23791 to track

**Comment by nex3** [comment]
It looks like they're enabled by default in the latest VM. I've filed #23793 to track enabling them by default in the Analyzer so there's something to link to in the checklist above.

**Comment by mit-mit** [comment]
Meta bug, assigning to self to drive to completion for 1.12.

**Comment by mit-mit** [comment]
Marking #23794 complete, see comments there

**Comment by mit-mit** [comment]
Closing this: outside of the docs -- which don't ship in the sdk -- just the dart2js impl. of Class?m remains, and that can be shipped in 1.13.

**Comment by kwalrath** [comment]
Doc changes are up for review: https://chromiumcodereview.appspot.com/1301343002/
