### ISSUE TITLE
BoringSSL: Switch SecureSocket implementation from NSS to BoringSSL

### ISSUE THREAD

**Issue by whesse** [dart-lang/sdk#23560]
We are switching the Dart standalone executable &quot;dart&quot; and the dart:io library to use the BoringSSL library (https://boringssl.googlesource.com/boringssl/)
instead of the Mozilla NSS library.

This will simplify the API for importing certificates and keys, simplify the build process and decrease the executable size, and switch to a simpler, smaller SSL library that is maintained by Google with outdated code removed and new TLS features added quickly.

 - [x] Merge in [BoringSSL branch](https://github.com/dart-lang/sdk/commit/13bf8ff9f8d0f993673ac40bda08bde460ba71dd)
 - [x] Support onBadCert arg: #23561
 - [ ] Add change log entry
 - [x] Update documentation
 - [x] Blog post
 - [x] Report errors from multithreaded encrypting: #24185

This master bug (issue) will be used to track requests, and be marked as blocked on all the bugs tracking individual feature implementations. @mit-mit: edited this to fit other [meta issues](https://github.com/dart-lang/sdk/wiki/Creating-and-triaging-meta-Issues).

**Comment by Scorpiion** [comment]
Looking forward to this, a nice change!

**Comment by mit-mit** [comment]
@whesse, I updated this to follow the meta bug style. Can you complete the list I started for things that need to happen in 1.13? Thanks!

**Comment by whesse** [comment]
This is now complete.  Filing a separate bug for the changelog entry.
