### ISSUE TITLE
Non-nullable types experimental implementation

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#23766]
This is the main tracking bug to experimentally implement the [Non-nullable types proposal](https://github.com/dart-lang/dart_enhancement_proposals/issues/30). It links to the more specific implementation issues below.

All implementation for this experiment should be gated behind a flag named "nonnull". If we decide to accept the proposal and add it to the language specification, the flag will be removed then.
### Parse `!` and `?` in type annotations

These should be allowed in _postfix_ position on type annotations. Initially, they will not do anything. The parser can simply ignore them and continue.
- [ ] Parse and ignore `!` and `?` in VM (#23767)
- [ ] Parse and ignore `!` and `?` in dart2js (#23768)
- [ ] Parse and ignore `!` and `?` in analyzer (#23769)

**TODO: Next steps...**

**Comment by munificent** [comment]
Wow, I completely forgot about these tracking issues. More than a year later, yes, we are going to try out non-nullable types (#22). However, we aren't directly tracking Patrice's DEP (though it is wonderful and is the primary inspiration for the in-progress proposal).

I'm going to close these old issues out to try to reduce some confusion. When we have a live proposal that the language team is working on, I'll file new issues to track against that.
