### ISSUE TITLE
Implement less restricted mixins (aka `allow super() calls`)

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#23770]
[DEP 34](https://github.com/dart-lang/dart_enhancement_proposals/issues/34) -- allowing mixins to have super() calls & superclasses other than object -- has been accepted (but has not yet gone through TC 52). That means now is a great time to start implementing it. That way we can iterate on the details if needed before they are carved into the spec.

Since this feature is not in the spec yet, the implementation should be gated behind a flag called "supermixin".

This is the main tracking bug. Each platform's specific bug is below:

Required for 1.13:
- [x] VM (#23771)
- [x] analyzer (#23772)
- [x] Remove flag from VM (https://github.com/dart-lang/sdk/issues/24479)
- [x] Update docs (https://github.com/dart-lang/www.dartlang.org/issues/1475)
- [x] Add UI to enable flag for Atom (https://github.com/dart-atom/dartlang/issues/370)

Post 1.13:
- [x] DDC: https://github.com/dart-lang/sdk/issues/27344
- [x] dart2js (#23773) 
- [x] TC52 approval (#24262)
- [ ] Add UI to enable flag for Eclipse

**Comment by donny-dont** [comment]
@munificent you have the dart2js and analyzer bug numbers swapped.

**Comment by sethladd** [comment]
Thanks @donny-dont , I fixed it.

**Comment by munificent** [comment]
Thanks, homies!

**Comment by jmesserly** [comment]
fyi DDC bug is
- [ ] https://github.com/dart-lang/dev_compiler/issues/306

**Comment by mit-mit** [comment]
munificient@, does this track both these two parts that are in the DEP? 
 - Mixins can refer to super.
 - Mixins can have superclasses other than Object.

**Comment by mit-mit** [comment]
Updated task list.

**Comment by munificent** [comment]
Yes, my intent is that this bug is for the whole proposal. (Also, neither of those parts is very useful without the other.)

**Comment by devoncarew** [comment]
I see the tasks for 1.13, and those for after, in order to add support for this flag. Is there a time-frame for removing the flag though? Or is that entirely dependent on TC52?

**Comment by bwilkerson** [comment]
That's entirely dependent on TC52.

**Comment by mit-mit** [comment]
Seth, can we mark this complete for 1.13?

**Comment by sethladd** [comment]
Still waiting for docs, but that doesn't impact the branch point.

**Comment by kwalrath** [comment]
Docs bug is at dart-lang/www.dartlang.org#1475

**Comment by donny-dont** [comment]
Is this officially enabled in 1.13? Didn't see any word in the changelog.

**Comment by mit-mit** [comment]
Hi @donny-dont, yes this is in 1.13, however as it has not been approved by TC52 and as it is not yet supported in dart2js, it's behind a flag -- see https://github.com/dart-lang/sdk/issues/23772#issuecomment-143890654

**Comment by zoechi** [comment]
```yaml
analyzer:
  language:
    enableSuperMixins: true
```
in `.analysis_options` should do it (not tested)

**Comment by anders-sandholm** [comment]
This was approved by TC52 in December'15.  
It is not yet supported in dart2js.

**Comment by robbecker-wf** [comment]
FWIW Workiva would benefit from this work.

**Comment by mraleph** [comment]
Is this part of Dart 2 features or is it gonna be still gated by flag post Dart 2?

/cc @lrhn @leafpetersen

**Comment by lrhn** [comment]
It's gated by a flag post Dart 2, until we add a more reasonable syntax for the feature.
The flag is only there to allow Flutter to keep using existing code, not because we like it.
That is, the feature is *removed* in Dart 2 (it was in Dart 1, just not implemented by dart2js).

**Comment by dgrove** [comment]
Work on this was finished long ago
