### ISSUE TITLE
Implement Resource class

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#23823]
The Resource class has landed in the SDK. Implementation should be underway, and it doesn't need to be behind any sort of flag.

This is the main tracking issue. Individual issues are below:

- [x] Resource class API in SDK (https://codereview.chromium.org/1181663002/)
- [x] VM #23824
- [x] VM tests #23987 
- [ ] dart2js #23825
- [x] sufficient api docs
- [x] .packages file is written during pub global activate (dart-lang/pub#22; merge request is #24094)
  (this is required to resolve a package: URI via the resource class from a globally activated package)
- [x] Mark class as experimental #24150

(original feature request: https://github.com/dart-lang/sdk/issues/21020)

**Comment by mit-mit** [comment]
@sethladd, would you mind updating this issue with the latest status (what remains for 1.12, and roughly when do we think that will be completed)?

**Comment by sethladd** [comment]
Hi @mit-mit . The issue's checklist is up to date. We might need a new title, though, because this was originally about the initial/minimal Resource class, but looks like it's grown to a list of many tasks around resources, in the general case.

**Comment by zoechi** [comment]
dart-lang/pub#22 is already fixed

**Comment by sethladd** [comment]
@zoechi it's not actually shipping in the SDK yet. I don't want to check it off until 1.12-dev-something has it.

**Comment by zoechi** [comment]
Thanks for the info. Makes sense.

**Comment by mit-mit** [comment]
Meta bug, assigning to self to drive to completion for 1.12.

**Comment by mit-mit** [comment]
Marking the merge item complete on checklist.

**Comment by mit-mit** [comment]
Added task to mark this experimental, see #24150

**Comment by mit-mit** [comment]
Marking task for experimental comment in docs complete.

**Comment by mit-mit** [comment]
Marking whole meta issue complete for 1.12: only the dart2js work remains, and that is now critical in 1.12 and will follow in 1.13.

**Comment by sethladd** [comment]
Thanks!
