### ISSUE TITLE
.packages: Run packagebots with a --no-package-symlinks configuration

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#24093]
We'd like to increase confidence in a no-symlinks world. One idea is to run the packagebots with a no-package-symlinks configuration (in parallel with the symlinks config we have now)

Thanks!

Blocked by:

 - [x] Need to support `packages` argument to `Isolate.spawnUri` https://github.com/dart-lang/sdk/issues/23951
 - [x] pkg/test supports packageSpec file https://github.com/dart-lang/test/issues/327
 - [ ] Update test.py https://github.com/dart-lang/sdk/issues/27063

**Comment by dgrove** [comment]
I believe we don't need this for 1.12 .

**Comment by whesse** [comment]
OK, so we don't do any special testing, just use the SDK as is, without extra options?  So pub generates both .package and symlinks, and other tools do what? Do they use the .package if it is there, by default?  Shouldn't we be testing something?  Like what if the .package file isn't there?  Tools besides pub are supposed to still work without a .package file.

**Comment by sethladd** [comment]
> So pub generates both .package and symlinks

Yes.

> Do they use the .package if it is there

They should, if they are following DEP5 correctly. https://github.com/lrhn/dep-pkgspec/blob/master/DEP-pkgspec.md

> Like what if the .package file isn't there

That would be the case if the user didn't upgrade to 1.12, or if they did upgrade to 1.12 but did not run `pub get` or `pub global activate` again (which adds the .packages).

> Tools besides pub are supposed to still work without a .package file.

Correct. @hterkelsen has some really nice integration tests that test for various scenarios (has a .packages, doesn't have a .packages, etc etc). I'm not sure they are sufficient, but they are definitely necessary and will help catch regressions on the package resolution discovery logic in our various tools.

Starting early in the 1.13 dev cycle, we'll want to start testing with --no-package-symlinks.

**Comment by mit-mit** [comment]
@kevmoo, how far are we from unblocking this?

**Comment by kevmoo** [comment]
Should be completely unblocked. @whesse running on this?

**Comment by kevmoo** [comment]
Emailed @whesse to confirm we are on track for 1.19

**Comment by whesse** [comment]
We started using --no-package-symlinks on all builders on the package waterfall, after commit https://github.com/dart-lang/package-bots/commit/f582ad4a04bb2cc13604fe41274cbc8b655904e2

The packages using "pub run test" are working fine, the packages using "test.py" are blocked on #27063

**Comment by whesse** [comment]
OK, all the packages seem to be running fine, both those running test.dart and those using package:test.
