### ISSUE TITLE
.packages: Eliminate symlinks, phase two

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#24112]
This bug tracks completing the work we started in 1.12 to eliminate symlinks (see previous work here: #23372). The goal of this second phase is to ensure that our whole SDK tool chain works even when no packages directory is present.

Concrete work items are:

Ensure the base SDK tools work great after a user uses pub's `--no-package-symlinks`:

- [x] Isolate.spawnUri takes a mapping of package data: #23951
- [x] `Isolate.packageConfig` returns map from package name to Uri #24022
- [x] `Isolate.packageConfigUri` returns a URI for the current package config #24524
- [x] `Isolate.packageRoot` should return a URI #19430

Then:

- [x] test package works without a packages/ dir (https://github.com/dart-lang/test/issues/327)

Then:

- [x] Test on packagebots with --no-package-symlinks config #24093 

Then:

- [x] Unhide flag in pub - https://github.com/dart-lang/pub/issues/1340
- [x] Document in SDK changelog

Finally, ensure the higher-level tools work great if there is no packages/ directory. That work is tracked here: https://github.com/dart-lang/sdk/issues/24288

**Comment by mit-mit** [comment]
@sethladd , can you take a look at the task list to check that we got everything?

**Comment by sethladd** [comment]
@nex3 I'd like to open a few issues for pub on this topic, but I know pub is on the end of a chain of other prerequisite changes. The new issues will simply help us understand the scope of what we need to do for symlink elimination. Thanks!

**Comment by nex3** [comment]
I closed dart-lang/pub#1331 and removed it from the list above because it's based on a misunderstanding: `pub serve` doesn't rely on symlinks, and never has. I believe the only place that pub ever actually *consumed* symlinks (as opposed to generating them) was `pub run` when it spawned a child process, and that was changed to `.packages` in dart-lang/pub@097ed875ea36b5406dce7c441f4feda1181f7664.

The actual title for dart-lang/pub#727 was always kind of misleading—it talks about not consuming on symlinks, but the discussion in the issue is actually about what it would take to not generate them. Maybe we should change the name to something like "Don't generate symlinks"?

**Comment by sethladd** [comment]
> Maybe we should change the name to something like "Don't generate symlinks"?

Sure thing. Done and done!

So, is there anything you'll need before you can stop generating symlinks, which isn't covered in this issue above?

**Comment by nex3** [comment]
It looks like there isn't a list item up there for accessing resolved package URIs—something like #23990 or [this CL](https://codereview.chromium.org/1307183002/) will be necessary to make it possible for packages (including `test`) to locate resources efficiently.

**Comment by sethladd** [comment]
My impression was that https://github.com/dart-lang/sdk/issues/24022 would be sufficient.

**Comment by nex3** [comment]
#24022 is very important for starting subprocesses with the right package information, but it's not a good fit for finding resources in an existing process.. It only works if a package spec is being used, it requires extra IO and parsing, and it won't work with internal Google infrastructure.

**Comment by sethladd** [comment]
> It only works if a package spec is being used

But you can use packageRoot otherwise, yes?

**Comment by nex3** [comment]
Not currently—the getter is only set if the user passed it explicitly on the command line, so if it was implicitly detected based on the entrypoint's location that's not reliable. I'm not sure whether #19430 will change that or not.

**Comment by sethladd** [comment]
> so if it was implicitly detected based on the entrypoint's location that's not reliable

Ah ha, I understand now. Thanks for the additional context.

**Comment by sethladd** [comment]
@nex3 talking to @iposva-google it sounds like #19430 should be sufficient. Will follow up over there.

**Comment by nex3** [comment]
Okay, but we'll still need resolved package URIs.

**Comment by sethladd** [comment]
> but we'll still need resolved package URIs.

If you had a combination of packageRoot and packageSpec/Map, could you not constract how a package: URI is resolved? In fact, could you not do this in a package that you built yourself?

**Comment by nex3** [comment]
As I said above, it requires extra IO and parsing and won't work with Google's internal infrastructure.

**Comment by sethladd** [comment]
> won't work with Google's internal infrastructure.

So there's no packageRoot or packageMap/Spec in internal google infrastructure? Both would be null, in all cases for internal google infrastructure?

cc @cbracken who might be able to help provide perspective

**Comment by cbracken** [comment]
We construct a "flattened" package directory, pubspec.yaml, pubspec.lock, and .packages files internally. If the question is whether we can run entirely without the packages/ dirs, it shouldn't be significantly different from externally.

**Comment by nex3** [comment]
@cbracken How does `dart path/to/file.dart` work internally?

**Comment by cbracken** [comment]
VM 'binary' builds emit two things. For an app named foo, we emit:
1. a small shell script named `foo`
2. a tree of all required dep srcs/assets/etc. named `foo.runfiles`.

First thing the `foo` script does on startup is create a tempdir in which it constructs a package-root layout from the srcs in `foo.runfiles`. It then invokes `dart --package-root=/tmp/sometmpdir `foo.runfiles/path/to/file.dart`.

**Comment by nex3** [comment]
I updated the main issue to reflect the current plan.

**Comment by bp74** [comment]
We haven't heard about the "eliminate symlinks" undertaking for quite some time. Is this feature postponed or canceled? I ask because i just deleted a lot of my source code AGAIN by simply deleting a packages symlink in WebStorm.

**Comment by mit-mit** [comment]
Sorry for the seemingly lack of progress. We are still working on it, but we realized that we needed more investigation and testing before we felt confident releasing this. Hopefully we will be able to launch this fairly soon!

**Comment by kevmoo** [comment]
Closed by https://github.com/dart-lang/sdk/commit/38dccc88ffa9ab190154a1f40b36d5ab0d3be728

🎉

**Comment by sethladd** [comment]
Hurray!
