### ISSUE TITLE
dart2js: make diagnostic tools awesome

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#24170]
This is a meta bug to keep track of several improvements we'd like to make to dump-info and it's diagnostic tools:

* [ ] make data collection accurate and complete #24095
* [ ] improve dependency tracking #24097
* [ ] track input-size data #24096
* [ ] track metrics about code quality (number of dynamic calls, nSM, etc)
* [ ] implement a new tool to show correlation of input and output data
* [ ] improve existing tools to track dependencies
* [ ] improve coverage support to make it easier to use (consider adding a hidden flag)

**Comment by mit-mit** [comment]
Clearing out 1.15 milestone as the last full push to dev has happened. If any changes are required before 1.15 is shipped, please file a merge request

**Comment by mit-mit** [comment]
Bumping to 1.17

**Comment by Markzipan** [comment]
Noting here that we should add robust testing to our diagnostic tools as well. Dump-info doesn't currently have tests for most of its commands.
