### ISSUE TITLE
Implement assert() messages

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#24213]
The DEP committee feels [Seth's proposal](https://github.com/sethladd/dep_assert_with_optional_message/blob/master/proposal.md) for an optional message to `assert()` is far enough along to be ready for a real implementation.

~**the implementation should be gated behind a flag called "assert-message".**~
The implementations can and should now remove the flag.

This is the main tracking bug. Each implementation's specific bug is below:
- [x] VM (#24215) - CL https://codereview.chromium.org/2564623003/ ([old cl](https://codereview.chromium.org/1307363005/))
- [x] dart2js (#24216) - CL https://codereview.chromium.org/1325843003/
- [x] analyzer (#24217)
- [x] analyzer cli (https://github.com/dart-lang/sdk/issues/25141)
- [x] analysis server (https://github.com/dart-lang/sdk/issues/24276)
- [x] DDC (https://github.com/dart-lang/sdk/issues/27342)
- [x] dart_style (dart-lang/dart_style#411)

**Comment by munificent** [comment]
Hey, @jmesserly or @vsmenon, do you want to file a relevant bug for DDC?

**Comment by sethladd** [comment]
@gbracha can you provide any updates from the DEP's discussion on whether the optional param can be type annotated with dynamic or String ?

Thanks!

**Comment by sethladd** [comment]
From a chat with @gbracha : The type annotation for the optional parameter will be a String.

**Comment by sethladd** [comment]
Bumping to 1.14, not a critical 1.13 thing

**Comment by sethladd** [comment]
Not sure what the status of this is.

**Comment by munificent** [comment]
As far as I can tell:

* The landed patch to dart2js allows any object and it is converted to a string when the AssertionError exception is printed.
* The not-landed patch to analyzer reports a static warning if the message is not assignable to a string.

I believe the consensus opinion on the DEP committee is that any object should be allowed.

**Comment by mit-mit** [comment]
Clearing out 1.15 milestone as the last full push to dev has happened. If any changes are required before 1.15 is shipped, please file a merge request

**Comment by bwilkerson** [comment]
Are we leaving the support behind a flag for 1.50, or are we removing the flag?

**Comment by sethladd** [comment]
Curious, what was implemented? https://github.com/sethladd/dep_assert_with_optional_message/blob/master/proposal.md or something else?

**Comment by bwilkerson** [comment]
Something more general. The message is allowed to be any expression (not just a string literal).

**Comment by mit-mit** [comment]
Marking VM complete based on https://codereview.chromium.org/2564623003/

**Comment by munificent** [comment]
Not quite there yet: https://github.com/dart-lang/sdk/issues/24215#issuecomment-266816736

**Comment by mit-mit** [comment]
Moving to 1.22, we need to get this completed.

**Comment by mit-mit** [comment]
Removing *behind a flag* from title also now that we are ready to not have this flagged

**Comment by dgrove** [comment]
Now that #24215 is closed, is there any reason that this should not be closed as well?

**Comment by mit-mit** [comment]
@munificent do we have tests in place?

Also, we should spec somewhere what we actually added (which sounds like it was different from the DEP).

**Comment by mit-mit** [comment]
Is the informal spec? https://gist.github.com/eernstg/50a327addd96035d5393a507c0ea2d9a

**Comment by eernstg** [comment]
That's the spec of 'General expressions in assert', which just allows you to use an `expression` rather than a `conditionalExpression` as the single argument to `assert`. This issue is about passing two arguments to assert, the second of which would be used as a message. The discussions were about the typing of that second argument, I believe, and the evaluation (insist on string? just call `toString()`?).

**Comment by mit-mit** [comment]
Did some basic testing passing this program to [a recent build](http://gsdview.appspot.com/dart-archive/channels/dev/raw/1.22.0-dev.2.0/sdk/):
```
main() {
  assert(2 > 1, 'Math is broken');
  var v;
  assert(v != null, 'v is null');
}
```

- dartanalyzer: OK
- dartfmt: OK
- dart2js: OK
- ddc: OK
- dart: Fails, rejecting the second argument unless passed flag, logged https://github.com/dart-lang/sdk/issues/28136

**Comment by munificent** [comment]
> @munificent do we have tests in place?

They are a little scattered:

* The dartjs folks added tests/compiler/dart2js_extras/assert_with_messages.test
* The VM folks added test/language/assert_message.test
* For DDC, I added test/language_strong/assert_with_messages.test
* Dartfmt, as usual has its own tests.
* Analyzer too.

The latter two make sense to be different. I think we should eventually unify the first three. A lesson I took away from this is that the language team should try to manage testing a new feature so that we don't pawn it off on the implementers and get redundant or spotty tests.

**Comment by stereotype441** [comment]
> A lesson I took away from this is that the language team should try to manage testing a new feature so that we don't pawn it off on the implementers and get redundant or spotty tests.

I like the sound of this.  It would go a long way toward helping to avoid confusion when different teams have different ideas about to interpret the spec, or how corner cases should be handled.

**Comment by munificent** [comment]
> I like the sound of this. It would go a long way toward helping to avoid confusion when different teams have different ideas about to interpret the spec, or how corner cases should be handled.

Yeah, I totally agree. Leaf and I talked about this yesterday.

At the same time, I don't want the language team to implement all of the tests. Aside from having limited bandwidth, I think it's really useful to get help from people such as yourself who are really skilled at coming up with all of the tricky edge cases that we want to test.

So I'm thinking it should be a collaborative process, but the language team should probably own setting up the framework that the implementers can put tests into.

**Comment by stereotype441** [comment]
Sounds good to me.

**Comment by mit-mit** [comment]
Closing this for 1.22 as the last item (https://github.com/dart-lang/sdk/issues/28136) landed!
