### ISSUE TITLE
Eliminate symlinks, phase three

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#24288]
Following on phase 2 work: https://github.com/dart-lang/sdk/issues/24112

Ensure the higher-level tools work great if there is no packages/ directory.
- [x] Flip the default to not generate a packages dir
- [x] IntelliJ plugin - ??? BUG NEEDED
- [x] pub shouldn't generate symlinks (https://github.com/dart-lang/pub/issues/727)
- [ ] update changelog
- [ ] Brainstorm affected packages?
- [ ] others?

**Comment by sethladd** [comment]
cc @mit-mit

**Comment by dgrove** [comment]
What is the plan here?

**Comment by kevmoo** [comment]
Agreed this wasn't urgent for 1.23. Removing milestone.

**Comment by natebosch** [comment]
I think this is done
