### ISSUE TITLE
Update changelog for 1.13

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#24474]
* [x] Getters for StreamController + typedefs: onPause, onListen, onResume, onCancel
* [x] Added base64 to dart:convert

`dart:developer`
  * [x] `ServiceExtensionResponse`: #24793
  * [x] `Timeline` added: #24792 

`dart:io`
* [x] HttpClient added optional SecurityContext param: #24671 
* [x] changes to RawSecureServerSocket: certificateName -> context: #24671 
* [x] new SecurityContext class: #24671 

`dart:core`
* [x] resource is deprecated, scheduled for removal

`dart:isolate`
* [x] changes to spawnUri: added environment argument

**other**
* [x] VM's legacy debug protocol is deprecated, scheduled for removal

**Comment by mit-mit** [comment]
@kevmoo, do you have the change lists that these came from? We need to get the submitters to update the changelog.

**Comment by kevmoo** [comment]
@mit-mit sadly, no. I did some silly github crazy to pull these together.

@lrhn and @whesse cover most of them, I think.

**Comment by mit-mit** [comment]
Opened tracking bugs for the dart:developer changes.

**Comment by mit-mit** [comment]
marking dart:developer changes complete, pick request is #24811

**Comment by mit-mit** [comment]
all tasks completed, marking complete for 1.13.
