### ISSUE TITLE
Analysis is too slow or infinite

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#24690]
Our users report that there are lots of instances where the analyzer can't keep up with editing in order to provide error feedback, auto-complete, auto-imports, etc.

Sometimes restart helps, but often it falls into continuing analysis again.

Related issues:
- [x] https://github.com/dart-lang/sdk/issues/24689
- [x] https://github.com/dart-lang/sdk/issues/24630
- [x] https://github.com/dart-lang/sdk/issues/24655
- [ ] https://github.com/dart-lang/sdk/issues/24613 - deferred to 1.14
- [x] https://github.com/dart-lang/sdk/issues/24601

**Comment by scheglov** [comment]
Related issues:
1. https://github.com/dart-lang/sdk/issues/24689
2. https://github.com/dart-lang/sdk/issues/24630
3. https://github.com/dart-lang/sdk/issues/24655
4. https://github.com/dart-lang/sdk/issues/24613
5. https://github.com/dart-lang/sdk/issues/24601

**Comment by pq** [comment]
> @pq is this something you observe too?

Yep.  And eventually, after a bit of use, DPI seems to basically die altogether.  The following exception is pretty reliably spewed in the logs.

```
NoSuchMethodError: method not found: 'getState'
Receiver: null
Arguments: [Instance of 'ResultDescriptorImpl']
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      AnalysisContextImpl.computeResolvedCompilationUnitAsync. (package:analyzer/src/context/context.dart:657)
#3      PendingFuture.evaluate (package:analyzer/src/context/context.dart:2026)
#4      AnalysisContextImpl._evaluatePendingFutures (package:analyzer/src/context/context.dart:1520)
#5      AnalysisContextImpl.performAnalysisTask. (package:analyzer/src/context/context.dart:1101)
#6      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:149)
#7      AnalysisContextImpl.performAnalysis... (show balloon)
```

**Comment by bwilkerson** [comment]
Do you know whether the version of server you were running included this change (https://codereview.chromium.org/1408393007/)?

**Comment by pq** [comment]
I don't think so. Looking at the version id:

`1.13.0-edge.6c85fe785a85b1a907ce05f440dd08b2fd0fd994`

I think my SDK is an earlier commit.

Rebuilding now and I'll keep you posted.

**Comment by sethladd** [comment]
I've noticed Atom's Dart experience fails to keep up as well. I often need to backspace back to a previous . and then try code completion again. Or, I get a "this import is unknown" for a package that I've installed... but a re-analyze sources fixes it.

How do I tell if this is because "too slow or infinite", in order to help diagnose?

cc @devoncarew

**Comment by bwilkerson** [comment]
Given that everything required for 1.13 is complete, I'm closing this tracking issue.
