### ISSUE TITLE
Please allow a package author to ship configurations for analyzer

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#24733]
This is a meta-tracking issue for allowing package authors (e.g. Flutter) to ship analyzer configurations inside of packages. The analyzer would then auto-discover the configuration file, and turn on: language features, lints/errors/warnings/hints.

* [x] Enable analyzer to auto-discover a configuration file in a package 
  * [x] server (https://github.com/dart-lang/sdk/issues/24943)
  * [x] CLI (https://github.com/dart-lang/sdk/issues/25380)
* [x] Configure which hints are "fatal" (https://github.com/dart-lang/sdk/issues/24452)
* [x] Enable language features via analysis options (e.g. super-mixin is on or off) (https://github.com/dart-lang/sdk/issues/24750)
* [x] Enable hints/warnings configuration (on/off)
* [x] Document what we can put in this file (https://github.com/dart-lang/sdk/issues/25011)

**Comment by pq** [comment]
> Enable hints/warnings configuration (on/off)

First cut in flight: https://codereview.chromium.org/1420363005/

**Comment by sethladd** [comment]
:guitar: on!

**Comment by pq** [comment]
> > Enable hints/warnings configuration (on/off)

> First cut in flight: https://codereview.chromium.org/1420363005/

Landed in https://github.com/dart-lang/sdk/commit/2f9c4af993df48cdd7180dcb79d36dbe6aa462f0.

**Comment by sethladd** [comment]
\o/

**Comment by zoechi** [comment]
Is this only for analyzing code in this dependency package or for the entire application?

**Comment by sethladd** [comment]
The entire application. We're exploring what it means to ship an "embedder" package... it's not documented because we don't know how far this will go. Just making small tweaks to support Flutter at the moment.

**Comment by zoechi** [comment]
Ok, waiting for it to evolve :) 
Thanks for the info.

**Comment by pq** [comment]
> Configure which hints are "fatal" (#24452)

@sethladd : I added a UI proposal to #24452, could you comment?  Also, that's marked as `HIGH` priority.  Is that accurate?

**Comment by kevmoo** [comment]
@pq are we running on this for 1.14?

**Comment by mit-mit** [comment]
Moving to 1.15 per comments in #25380

**Comment by sethladd** [comment]
Here's the script that we're currently using to configure. This issue is done when this script simply calls dartanalyzer: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/analyze.dart

**Comment by mit-mit** [comment]
Clearing out 1.15 milestone as the last full push to dev has happened. If any changes are required before 1.15 is shipped, please file a merge request
