### ISSUE TITLE
Align IDE feedback with flutter CLI

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#25723]
Pre-req: enable whatever analyzer support is needed to make IDE-reported errors and warnings align with those emitted by [`flutter analyze`](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/analyze.dart). This entails server/analyzer:
- [x] Source-level error suppressions (https://github.com/dart-lang/sdk/issues/25685)
- [x] Support for all commandline options in `.analysis_options` (https://github.com/dart-lang/sdk/issues/25983)

With that we can:
- [x] Migrate all `flutter analyze` command-line configuration to options
  - [x] strong
  - [x] supermixin
  - [x] enable-strict-call-checks (bocked until next dev build: https://github.com/dart-lang/sdk/issues/25983)
- [x] Migrate all filtered output to suppressions (via options) or ignores (in source)
  - Status (3/21): _mostly_ there; tracking spreadsheet [here](https://docs.google.com/spreadsheets/d/1WRzim3ozlOPpPMKL24CfQW2ru1c0eDOD0HLHHaOmzmk/edit?ts=56e1d0cf#gid=0)
    - Blocked on `OptionalTypeArgs` annotation support (https://github.com/dart-lang/linter/issues/196)
- [ ] Share all analysis configuration between `flutter analyze` analysis options and sky_engine `_embedder.yaml`

**Comment by devoncarew** [comment]
This is ~the `.analyzer_options` tracking issue?

**Comment by pq** [comment]
> This is ~the .analyzer_options tracking issue?

More specifically configs via flutter lib `_embedder.yaml`.

Essentially this is the "what we need to remove `RegExp`s from flutter `analyze`" punch list.

**Comment by devoncarew** [comment]
Ah, you can use `_embedder.yaml` for analyzer config as well as `.analyzer_options`? I didn't know there was overlap.

**Comment by pq** [comment]
A question for @Hixie: can we replace the need for any of these `RegExp`s with judicious use of source-level suppressions (https://github.com/dart-lang/sdk/issues/25685)?

**Comment by Hixie** [comment]
```
      new RegExp('^\\[(hint|error)\\] Unused import \\(${mainFile.path},'),
```
Could remove that by putting suppressions in the constructed file.

```
      new RegExp(r'\[lint\] Prefer using lowerCamelCase for constant names.'), // sometimes we have no choice (e.g. when matching other platforms)
```
This one is a good candidate for it.

The others are either too common, or in code we don't control. Some can probably be silenced with global per-warning suppression.

**Comment by pq** [comment]
This arc is done.
