### ISSUE TITLE
Repurpose `meta` package for analysis annotations.

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#25741]
To start:
* [x] get @pq in the uploaders list
* [x] add `sdk/pkg/meta` ~~create a `meta` repo on dartlang~~ 

Add metadata for:
* [x] `@required`
* [x] `@protected` (https://codereview.chromium.org/1706993002/)
* [ ] ...

Release:
* [x] tag and publish
* [ ] update `DEPS`

**Comment by pq** [comment]
@jmesserly, @sigmundch : could one of you add me to _uploaders_?

**Comment by sigmundch** [comment]
all set, you should be an uploader now

**Comment by pq** [comment]
Thanks!

**Comment by pq** [comment]
cc @kevmoo for repo creation

**Comment by pq** [comment]
cc @bwilkerson 

Chatting with @kevmoo, he proposed putting this in `sdk/pkg`.  No objection here.

**Comment by donny-dont** [comment]
@pq is this going to be published as a package or in the sdk proper?

**Comment by pq** [comment]
It will be published as a package.

**Comment by donny-dont** [comment]
:+1: looking forward for this happening.

**Comment by pq** [comment]
The `meta` package is now [published](https://pub.dartlang.org/packages/meta), with annotations specified for:

* `@protected`
* `@required`
* `@mustCallSuper`
