### ISSUE TITLE
Strong mode hotlist

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#25812]
This is a hotlist issue for the main stuff the people hacking on strong mode are focusing on right now:

#### Generic methods (@jmesserly)

- [ ] SDK needs to have generic method comments where appropriate
- [ ] comment syntax allows reifying a tighter type than VM supports, e.g. `new List<num/*=T*/>()` (#25637)
- [ ] implement missing warnings/errors (#25200)
- [ ] implement missing AST nodes, e.g. `f<int>` and `o.m<int>` (#25175)
- [ ] declaration and use of generic function types, e.g. `<T>(T) ->T` (#25179)
- [ ] should we allow invalid use of comment form? (#24985)

#### Consistent use of upwards/downwards inference

- [ ] Downwards inference on generic methods (#25477)
- [ ] Upwards inference on constructors (#25220)
- [ ] Upwards inference for list/map literals (#25220)
- [ ] Consider upwards inference for block bodied closure returns & implicit unions (#25322)

#### Function parameter type and dynamic (top vs bottom)

Needs design.

- [x] Top-level function type weirdness (#24507)
- [ ] Instance method overrides -- warning? (#25578)

#### Closure / function parameter and return type inference (@leafpetersen)

- [x] Non-arrow function return (open, easily closable, uninferred closure) (https://github.com/dart-lang/dev_compiler/issues/290)

#### Future / async typing

- [x] `Future<Future<T>>` flattening
- [ ] flattening diverges (https://github.com/dart-lang/sdk/issues/25611)

#### Generics and variance

@vsm: try making DefaultEquality generic, revisit package:collection - do we need this?

- [ ] `B <: A<bottom>` (https://github.com/dart-lang/sdk/issues/25604)
- [ ] Add flag for invariant generics?

#### Ground types and is/as

Needs design.

- [ ] `is` on type parameter? (#24565)

#### Least upper bound

- [ ] is unsound & EfficientLength problem (https://github.com/dart-lang/sdk/issues/25802)

#### Field overrides

- [ ] do we want a `@virtual`?
- [x] Disallow for now? (https://github.com/dart-lang/dev_compiler/issues/52)

#### Error / warning quality

Should work on phrasing.

- [ ] Overhaul categorization
- [x] Rephrase DDC wording
- [ ] Make errors actionable
- [ ] Separate out DDC errors unrelated to soundness

#### No dynamic

- [ ] No reified dynamic (https://github.com/dart-lang/sdk/issues/25573)
- [ ] Inferences fails / no static dynamic
- [ ] No dynamic helpers generated

#### Improve type promotion

Various improvements that would help user productivity:
- [ ] meta bug: https://github.com/dart-lang/sdk/issues/25565

#### Other bugs to fix

- [x] Type of `(x) => null` (https://github.com/dart-lang/dev_compiler/issues/47)
- [ ] F-bounded quantification (https://github.com/dart-lang/sdk/issues/25530)
- [x] Private methods incorrectly treated as overrides even in different libs (https://github.com/dart-lang/dev_compiler/issues/366)
- [ ] assignment in setter (https://github.com/dart-lang/sdk/issues/25642)
- [ ] infer type from parameter default value (https://github.com/dart-lang/sdk/issues/25794)
- [ ] not checking inferred field initializer (https://github.com/dart-lang/sdk/issues/25546)

**Comment by jmesserly** [comment]
I went through and updated this with current bug numbers (at this point, all Strong Mode bugs should be here, not in DDC repo). I tried to add open issues we were missing. Not sure if I captured all of them. I think we are going to want to trim this list down.

**Comment by jmesserly** [comment]
I'm going to close this now that we've gone through and triaged bugs. But we can reopen if needed
