### ISSUE TITLE
Summary integration for IntelliJ

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#26799]
This issue tracks progress on making the benefits of summaries available to users developing Dart applications using IntelliJ.  Tracking bugs for the individual tasks:
- [x] Decide whether to eliminate propagated types from analyzer (#26795)
- [x] Remove propagated types from analyzer (or implement them in AST-based summaries) (#26794)
- [x] Enable AST-based summaries by default (#26793)
- [x] Add to summary format: links to summary files of dependencies (#26796)
- [x] Summary discovery for packages downloaded from pub (#26792)
- [x] Modify IntelliJ handling of line endings to work with summaries (#26800)
- [ ] Enable using pub summaries by default (remove the flag) (#27420)

**Comment by scheglov** [comment]
FYI, all the sub-tasks of this issue are done.

**Comment by devoncarew** [comment]
I believe this is complete.
