### ISSUE TITLE
Summary integration for flutter

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#26791]
This issue tracks progress on making the benefits of summaries available to users developing Flutter applications using Atom.  Tracking bugs for the individual tasks:
- [x] Decide whether to eliminate propagated types from analyzer (#26795)
- [x] Remove propagated types from analyzer (or implement them in AST-based summaries) (#26794)
- [x] Enable AST-based summaries by default (#26793)
- [x] Add to summary format: links to summary files of dependencies (#26796)
- [x] Summary discovery for packages downloaded from pub (#26792)
- [x] Support for summarized SDKs in the presence of embedders (#26467)
- [x] Build summaries for Flutter SDK and core packages (#26798)
- [x] Summary discovery for Flutter SDK and core packages (#26797)
- [ ] Enable using pub summaries by default (remove the flag) (#27420)

**Comment by scheglov** [comment]
FYI, I believe that all the referenced tasks have been implemented.
What's next?
Do we close this issue?

Or do we want tracking for another task - waiting for IntelliJ release with EOLs handling on the client?

**Comment by devoncarew** [comment]
I believe this is now addressed - `flutter analyze` is now based on the analysis server, which does use summaries.
