### ISSUE TITLE
JS Interop 1.0 issues

### ISSUE THREAD

**Issue by jacob314** [dart-lang/sdk#26844]
### Cases where Dartium doesn’t quite match Dart2JS behavior due to possibly hard to fix edge cases in facade Dartium has to maintain that Dart List is a JS Array, etc.
- [x] #26768 JSON.stringify doesn’t return the right thing for Dart Lists
- [ ] #25871 Bug on cross frame access.
- [x] #25658 This sometimes not bound in Dartium when it is in dart2js. Might be fixed.
- [x] #24817 window. doesn't work as expected in Dartium. Hopefully small bug to fix.
### Dart2JS bugs
- [x] Support call method on @JS classes without it upsetting dart2js  #25321
- [x] #25419 Type inference comes to the wrong conclusions after is checks on JS interop types. @johnniwinther
### Missing Dartium functionality.
- [x] #26718 properly escape all $ in property names passed to dartium to avoid bugs due to escaping and $.
- [x] #25038 @JS on a _Private class in Dartium (simple fix)
### Bad error messages.
- [ ] #25053 Attempting to define an [] operator
  Attempting to extend a @JS class
- [ ] #25759 Specifying default values for optional arguments should not be allowed.
  [General Analyzer] better message when using a ctor annotation without parens
### Feature work
- [ ] #24874 codegen from d.ts files
- [ ] #25059 Support JS module import. 
- [x] Expose expose js_util helper library.
### Issues potentially gated on Dart 2.0
- [ ] #24779 Issues solved if we had extension methods.
- [ ] #24623 support rest and varargs
  Issues solved if we didn’t use _ for privates or changed conventions for underscores in named parameters.
- [ ] #25375 Extend JS class from Dart. Really gated on removing dartium dependency not so much Dart 2.0.
### Exporting Dart classes to JS

  We need a general high level design as well. This is simple to implement in DDC, harder in Dart2JS and painful in Dartium.
- [ ]  #24886 Support DART$ as well as JS$ to mangle Dart names.
### Performance Improvements
- [ ] #26247 Caching interceptors for JS object classes  (sra)
### Issues not specific to new interop
- [ ]  #25785 General issue with Dart2JS determining interceptors for DOM classes based on class name (@sra).
