### ISSUE TITLE
Assert in initializers experiment

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#27141]
We are experimenting with allowing asserts in initializer lists.
See the [design document](https://gist.github.com/lrhn/45bdae95e017ebbf7a84bfbe26dffcae).

For this experiment, we need (behind the flag `--assert-initializer`):
- [x] the VM to implement the assertions (Committed: 99439a336a47e)
- [x] the analyzer to parse the assertions (but not necessarily analyze them yet). (https://github.com/dart-lang/sdk/issues/27142)
- [x] the formatter to parse the assertions. (https://github.com/dart-lang/dart_style/issues/522)

That should be sufficient for the people behind issue #24841 to test out the implementation and see if it covers their needs.

**Comment by a14n** [comment]
Could the design document be made public?

**Comment by lrhn** [comment]
My docs-fu is too weak, so I converted the design document it to a gist.

**Comment by a14n** [comment]
thanks

**Comment by bwilkerson** [comment]
The doc defines the assert statement as being `assert(expression)`, but the analyzer accepts an optional second argument. Is the omission an oversight, or should asserts in constructor initializers not allow a message?

**Comment by lrhn** [comment]
We are going to add the second "argument" to `assert`, so keep it for now.

**Comment by dgrove** [comment]
@lrhn can you please provide an update?

**Comment by dgrove** [comment]
@lrhn can you provide an update?

**Comment by jmesserly** [comment]
FYI DDC issue https://github.com/dart-lang/sdk/issues/27809

**Comment by munificent** [comment]
This is not a 1.50 feature, so kicking out of the milestone. (I think we accidentally got it confused with assert *messages*, which are in 1.50).

**Comment by sethladd** [comment]
This is done, right? flutter has this turned on now.

**Comment by munificent** [comment]
I'm not sure if this tracking issue is for the *experiment* or the *feature*. If the former, I guess it's closable? If the latter, no, because we haven't decided if we want to commit to it, remove the flag, etc.

**Comment by jmesserly** [comment]
oh gosh, yeah. Also DDC doesn't implement it yet, which I think nowadays we want for new language features? (it's not hard to implement btw)

**Comment by lrhn** [comment]
This is a Flutter only experiment (which is why it's VM+analyzer only so far, and should perhaps also include the formatter). That is *all* it is at this point. There is no language feature yet, it's not implemented by DDC or dart2js, and unless the experiment is a success, there won't be one.
The exact conditions for considering it a success isn't decided yet, but it should add non-negligible value for the Flutter developers.

**Comment by munificent** [comment]
The experiment has graduated to a feature. Closing out this bug in favor of #30968.

**Comment by sethladd** [comment]
Thanks for the help!
