### ISSUE TITLE
Accepted Features

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#27154]
This bug tracks the accepted features for the language and libraries.
These are tentatively accepted features. This list is bound to change based on implementation complexities, new feedback, or unexpected corner-cases and interactions.
- [x] Read-only access to initializing formals https://github.com/dart-lang/sdk/issues/26655
- [ ] `&&=` and `||=`: https://github.com/dart-lang/sdk/issues/26996
- [x] Assert accepts message. https://github.com/dart-lang/sdk/issues/24213
- [ ] Type instance `is` checks: `o is expr`. https://github.com/dart-lang/sdk/issues/27680
- [x] resolved part-of. https://github.com/dart-lang/sdk/issues/20792, https://github.com/dart-lang/dart_enhancement_proposals/issues/45
- [x] allow incomplete unicode surrogate pairs in string literals. For example `"\ud8xx"`. https://github.com/dart-lang/sdk/issues/26620
- [ ] Take advantage of negative is-checks for type propagation. Work with dart2js and Analyzer teams to get proposal.
- [ ] asserts should allow assignment expressions: `assert(x = true)`. Most implementations already did this.
- [ ] Optional new (see https://gist.github.com/floitschG/0a79d90c7824f3d540163b6ce7623236#file-optional_new-md)
  #20750 
  - [ ] `const` context https://github.com/dart-lang/sdk/issues/4046
  - [ ] constructor tear-offs
- [ ] positional and named optional parameters for the same function. https://github.com/dart-lang/dart_enhancement_proposals/issues/26 - next is requesting feedback from implementors. 
- [ ] Allow "_" in number literals: https://github.com/dart-lang/sdk/issues/26845
- [ ] Allow `void` as generic argument: https://github.com/dart-lang/sdk/issues/27504
- [ ] `?.` should count for the rest of the selectors (`o?.x.y` should be correct) https://github.com/dart-lang/sdk/issues/26240
- [ ] Generic arguments to constructors: https://github.com/dart-lang/sdk/issues/26391

**Comment by munificent** [comment]
@floitschG, are you still using this issue to track anything? If not, want to close it?

**Comment by floitschG** [comment]
It is still used.

**Comment by munificent** [comment]
Closing this because we aren't using this issue to track language work anymore.
