### ISSUE TITLE
Meta issue tracking implementation of generic function type syntax in Dart 1.5

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#27527]
This is a tracking bug for implementing support for generic function type syntax (generic typedef) in Dart 1.5.

**Proposal:** https://gist.github.com/eernstg/ffc7bd281974e9018f10f0cb6cfee4aa

The corresponding individual issues will be listed here:
- [x] Language team decision on syntax (private issue): dart-lang/dart-lang-evolution#88
- [x] Analyzer implementation issue: #27969
- [x] VM implementation issue: #27966
- [x] Dart2js implementation issue: #27967
- [x] DDC implementation issue: #27971
- [x] dartfmt issue: https://github.com/dart-lang/dart_style/issues/563
- [x] dartdoc issue: https://github.com/dart-lang/dartdoc/issues/1321
- [ ] Make sure changelog has an entry for this

* Final specification issue: #27970

***Description***

Dart 2 supports generic methods and generic tear-offs (or anonymous functions). This means that a function can request a function that is generic:

``` dart
// Takes a function `f` that is generic on T.
void foo(A<T> constructorForA<T>()) {
  A<int> x = constructorForA<int>();
  A<String> x = constructorForA<String>();
}
```
It is straightforward to add the syntax to the existing syntax for function types for parameters (as was done in the example). However, we don't have an easy way to do the same for fields or local variables:

``` dart
// Does *not* do what we want it to do:
typedef A<T> ConstructorForAFun<T>();

A f;  // A function that returns an `A<dynamic>`.
```

We already used the most consistent place for the generic method argument as a template argument to the `typedef` itself. If we could go back in time, we could change it as follows:

``` dart
typedef<T> List<T> TemplateTypedef();
TemplateTypedef<int> f;  // A function that returns a List<int>.
TemplateTypedef f;  // A function that returns a List<dynamic>.

typedef List<T> GenericTypedef<T>();
GenericTypedef f;  // A function that is generic.
List<int> f<int>();
List<String> f<String>();
```

Given that this would be a breaking change we have considered alternatives and are now exploring new typedef syntax altogether. The idea is to provide syntax that can also be used for locals and fields at the same time.

For example:
``` dart
typedef F = (int) -> void;  // Function from (int) to void.
typedef F<T> = () -> List<T>;  // Template Typedef.
typedef F = <T>(T) -> List<T>;  // Generic function from T to List<T>.
```

This way we would solve 3 issues at the same time:
- users often forget the parameter name and expect `typedef void F(int)` to be a function that takes an int.
- users can write the function type of fields and locals without needing to write a typedef.
- of course: we can write the type of a generic function.

While investigating different syntax we found that the following points need consideration:
- nullability: the syntax must be nullable without too much hassle:
  ``` dart
    (int)->int?;  // A function that is nullable, or that returns a nullable integer?
   Problem disappears with <-
   int <- (int)? ; vs int? <- (int) 
  ```
- readability
- interactions with union types (if we ever want them).

**Comment by a-siva** [comment]
@crelier

**Comment by floitschG** [comment]
Status update:

I have updated the issue description for more context.
We are still mainly exploring the "how does it look and feel" parts of the syntax (while still paying attention to how the parser should work).

The following CLs show explorations:

https://codereview.chromium.org/2439573003/
https://codereview.chromium.org/2466393002/

**Comment by crelier** [comment]
lgtm with a slight preference for the <- variant.

**Comment by leafpetersen** [comment]
status: Prototyping several options, @floitschG is driving.

**Comment by floitschG** [comment]
Latest proposal:

``` dart
typedef F = void Function(int);

// also works for field or local types:
final int Function(String, bool) myFun = ...;
```

- works nicely with the current `Function` type.
- very similar to the existing parameter types. Hopefully this also means that the parser can reuse parts of the parameter code.
- longer than `<-` or `->`.

Here is a CL that experiments with it: https://codereview.chromium.org/2482923002/

Note: we would still allow `Function(int x)`. However, `Function(int)` should be a function that takes `int` (and not a function that takes a dynamic argument of name `int`).
Eventually we would like to change the old syntax to do the same, but that requires some migration effort.

**Comment by crelier** [comment]
I do not like this latest proposal. The name Function is promoted to some kind of keyword used for parsing. Also, Function is not declared to be generic, therefore, using it to declare a non-generic typedef for a generic function will look like an error.

**Comment by floitschG** [comment]
It's not a perfect choice, but it has its advantages.

Dart already uses `Function` as general type for functions. It is true that `Function` was a real type, and the proposed function-type syntax shifts it into a keyword-like position, but there is a strong connection between the two. It's easy to see and understand that `Function` (without return and parameter types) is just like a reduced function-type syntax. It's not the same (as you correctly state), but it's very close to it.

It's true that the `Function` type/class isn't generic, but it also has no way to declare its return and parameter types. Clearly, the function-type syntax does more than just the `Function` type. It really is an anonymous subtype of `Function`. As such, it doesn't feel wrong to add generic functionality to it.

Personally, I'm not that much concerned about the fact, that `Function` now becomes a keyword for function types. On the contrary, I would expect this to improve the readability, since the new syntax is so close to the existing parameter types, and the meaning of the stand-alone `Function` fits the new interpretation.
  ``` dart
  Function f;  // a function.
  Function(int x) f;  // a function that takes an int.
  double Function(int) f;  // a function that takes an int and returns a double.
  ```

I'm more concerned about the fact that it is longer, and that we intend to interpret one-identifier parameters differently in the new syntax than in parameter types in the old syntax: `Function(int)` is a function that takes an `int` and not a function that takes one dynamic argument of name `int`. However, I believe that the benefits outweigh the cost here. In fact, we would advocate to change the meaning of one-identifier types for old-syntax parameter types, too. This would be a breaking change, though, and would require a careful migration effort.


Just for completeness sake, here are some examples of how the syntax would deal with the different generic arguments (to the typedef or for the function).
``` dart
typedef F = void Function(int);  // Function from (int) to void.
typedef F<T> = List<T> Function();  // Template Typedef.
typedef F = List<T> Function<T>(T);  // Generic function from T to List<T>.
```

**Comment by crelier** [comment]
I agree that having a special marker for function types has advantages and is easier to read. I only find the already defined "Function" a questionable choice for this marker, especially since the formal argument syntax is modified and not what you would expect after an identifier (i.e. regular function signature syntax). That's the reason I'd prefer a symbol rather than an identifier (or keyword), as in the previous proposals.

I agree that "<-" of the previous proposal is a bit hard to read when generic.
`T <- <T>(T)
`
Maybe reusing the just retired # symbol would work better.
`T #<T>(T) 
`

As a side note, you will also need to specify the syntax for optional arguments (no default values allowed), both positional and named, something like:
```
void Function(int, [int, bool]);  // optional positional
void Function(int, {int i, bool b});  // optional named
```

**Comment by floitschG** [comment]
`#` is still used for symbols (which was one of the reasons we didn't like it for tear-offs. For example, it wasn't possible to tear off globals).

Yes. We will have to specify the syntax for the optional arguments. (This is the reason that `Function<R, P1, P2>` isn't even a real option). Your proposal looks right (and I don't think there are any corner-cases that are hiding).

I/We will think about using something else than `Function`, but I doubt that we will find something better. The obvious candidates, `->` and `<-`, have already been considered, and most other choices are probably inferieur.

Personally, I also tend to avoid using symbols for uncommon functionality. Function types are not extremely rare, but they are not common enough to warrant their own symbol.

**Comment by munificent** [comment]
> I/We will think about using something else than Function, but I doubt that we will find something better

Would it be possible to add a new contextual keyword like `function` or `fun` or something? I'm guessing that would be a breaking change, but maybe it's not actually ambiguous in the grammar?

> Personally, I also tend to avoid using symbols for uncommon functionality. 

+1. Punctuation is almost always the wrong choice for new syntax unless it represents something almost all users already know, like using `+` for addition.

**Comment by lrhn** [comment]
The backwards-compatible advantage in using `Function`  is nice, but not essential. If you can't omit the parameters, so that `int Function x` is any function returning an `int`, then the syntaxes will be completely disjoint. If you *can* omit the parameters, then I think we should definitely use `Function` as the keyword - then you can write `Function Function Function x;` and have something thrice callable :)


We can make `Function` no longer be a class. Nobody should `implement Function` anyway, so it's not a loss. The only complication is `Function.apply` which needs a namespace, but if we remove `call` and make function objects completely distinct from class instances, then they can have `apply` as an instance method.

**Comment by eernstg** [comment]
About omitted parameter lists in the `<return-type> Function<formal-parameter-list>` syntax: That would allow developers to specify a return type and leave the parameter list unspecified (that is: anything goes), which is exactly what was requested in, say, https://github.com/dart-lang/sdk/issues/26420.

We might decide to introduce syntax for variadic functions at some point, in which case this will become a shorthand for "the most general argument list", but even at that point it seems likely that such a shorthand would be convenient.

**Comment by eernstg** [comment]
In the [informal spec](https://docs.google.com/document/d/1Djq9vZTNXBHtcAOzWaoXy2oPJ0D3ERCxBEuWPYz7YEw) (which will be made public when it has matured a bit) I've proposed a rename of this feature to 'Generalized type aliases' (because a limitation of this mechanism to handle generic function types only is artificial, and presumably counter productive).

**Comment by a-siva** [comment]
Could we add some tests cases for this so that the implementations can be verified.

**Comment by mit-mit** [comment]
Marking spec complete for implementation purposes based on https://github.com/dart-lang/sdk/issues/27970#issuecomment-266673190

**Comment by mit-mit** [comment]
Moving to 1.22 for implementation.

**Comment by eernstg** [comment]
Made the [informal specification](https://gist.github.com/eernstg/ffc7bd281974e9018f10f0cb6cfee4aa) available as a public gist.

**Comment by munificent** [comment]
Groovy, added a link to it up top in the issue description so it's easy to find.

**Comment by eernstg** [comment]
Based on several requests I've updated the grammar in the [informal spec](https://gist.github.com/eernstg/ffc7bd281974e9018f10f0cb6cfee4aa) to make `int Function(int)` style types a syntax error in various places (e.g., `extends`, `implements`, `with`). This was already a static semantic error, but the fact that it is now also a syntax error may simplify some tasks when dealing with programs as syntax only (that is, where no static analysis is performed).

**Comment by alexander-doroshko** [comment]
The current [informal spec](https://gist.github.com/eernstg/ffc7bd281974e9018f10f0cb6cfee4aa) changes the rule for `type`:
```
type:
    typeName typeArguments? |
    functionType // NEW
```
but `type` is used in other rules in the spec, not related to the typedefs, for example:
```
mixinApplication: type mixins interfaces? 
superclass: extends type
typeTest: isOperator type
```
etc. I guess you are not going to change the syntax of these constructs, are you?

//cc @eernstg

**Comment by alexander-doroshko** [comment]
Sorry, ignore my comment, I see that you updated spec while I was writing it :)

**Comment by alexander-doroshko** [comment]
@eernstg  Well, I think there's still something to fix. `type` is used also in:
```
finalConstVarOrType
varOrType
typeParameter
declaration
returnType
typeList
onPart
typeTest
typeCast
```
I also could miss a couple of cases.
Also, '`It is a compile-time error if a functionType is used as a superclass...`' can now be removed I guess.

**Comment by alexander-doroshko** [comment]
It might be easier to leave `type` as is and change `normalParameterType` and `typedIdentifier` instead:
```
normalParameterType: type | functionType | typedIdentifier
typedIdentifier: type identifier | functionType identifier
```

**Comment by eernstg** [comment]
Hello Alexander, thanks for your input!

Yes, we did intend to change those other locations: A function type wasn't inline expressible until now, but we want to make them expressible, such that developers aren't forced to use a `typedef` to express function types in all cases, they can just go ahead and write them where they need them.

Note that `typedef`s introduce aliases, not new types, so there is no semantic difference between being able to give a new name to a function type and then using that name where that type should be, versus being able to write that function type directly where it is needed.

With `finalConstVarOrType`, `varOrType`, `returnType` you'd get new possibilities like
`int Function(int) myFunction = ...`, and `int Function(int) foo() => ...`, with `typeParameter` and `typeList` you'd get `List<int Function(int)>` (but not `.. extends int Function(int)` nor `.. with MyMixin, int Function(int)`, because that's been defined away with the new grammar rules). If you think that's too unwieldy you can always go back to the old style and `typedef`. Similarly, you can use `f is int Function(int)` and `.. as ..`. So that's a feature rather than a bug. ;-)

You can't remove the sentence about compile-time errors because `class C extends D` could still have a function type as a superclass if `D` is introduced by a `typedef`.

**Comment by eernstg** [comment]
The number of changes in the grammar doesn't differ much if you reorganize: There are several places where we need the general `type` (which includes `functionType`) and several places where we need `typeWithoutFunction`.

**Comment by alexander-doroshko** [comment]
Ok, thanks for the explanation!

**Comment by eernstg** [comment]
Bug fix applied to the [informal spec](https://gist.github.com/eernstg/ffc7bd281974e9018f10f0cb6cfee4aa): Added missing grammar update for `redirectingFactoryConstructorSignature`

**Comment by alexander-doroshko** [comment]
Won't parsers have problems with the recursion `type -> functionType -> returnType -> type ->...`?
```
type: typeWithoutFunction | functionType
functionType: returnType? 'Function' typeParameters? parameterTypeList
returnType: void | type
```

**Comment by lrhn** [comment]
I don't think the return-type/type distinction is a problem to parse.
After parsing any type, you have to check if it's followed by `Function<` or `Function(`, and if so, it's a return type of a function type, otherwise it's just a type by itself. There shouldn't be any ambiguity, and you only need a very short look-ahead.

**Comment by a-siva** [comment]
A breaking change has been detected in google3 code, the following example captures the jist of it
  import 'dart:core' hide Function;
  class X {
    X() { print(1); }
    X.f() { print(2); }
  }
  class Function extends X {
    Function() : super();
    Function.f() : super.f();
  }
  main() {
    new Function();
    new Function.f();
  }
Please clarify

**Comment by floitschG** [comment]
This is an unfortunate consequence of this change. At some point I looked through the Google3 code but didn't see any `class Function` that wasn't in our own code. Maybe that changed...

In any case, please let us know where this happened and we will work on fixing it. Thanks for notifying us.

**Comment by mit-mit** [comment]
Punting to 1.23 per email discussion

**Comment by floitschG** [comment]
We reverted the syntax for 1.22 and add a deprecation warning for `class Function` instead.
1.23 will then feature the actual syntax.

**Comment by leafpetersen** [comment]
Is this still on track for 1.23?

**Comment by bwilkerson** [comment]
I can't speak for anyone else, but I am actively working on the analyzer support.

**Comment by crelier** [comment]
I am not sure who you are asking, but the corresponding VM issue has been closed on January 27.

**Comment by mit-mit** [comment]
@leafpetersen see detailed status in the two unchecked items in the top checklist

**Comment by jcollins-g** [comment]
For dartdoc, it turns out there's no need to do anything directly for the SDK release and the work that does need to be done isn't blocking any longer.   I've dropped the 1.23 label from [dart-lang/dartdoc#1321](https://github.com/dart-lang/dartdoc/issues/1321) accordingly, and there are more details there as to why.

**Comment by jcollins-g** [comment]
I had misunderstood a key piece of the feature, I recommend blocking this feature on dartdoc now.  Dartdoc in the SDK won't crash without the upcoming fix, but it will display the typedef with the generic parameter missing.

**Comment by munificent** [comment]
dartfmt support is [in flight](https://github.com/dart-lang/dart_style/pull/610).

**Comment by munificent** [comment]
dartfmt is fixed and in the repo.

**Comment by mit-mit** [comment]
@leafpetersen looks like this one is still missing in changelog.md?

**Comment by leafpetersen** [comment]
I left it out, since I wasn't 100% sure that it was landing, but it looks like maybe the dartdoc issue is resolved?  If so, I can go ahead and write something up.

**Comment by leafpetersen** [comment]
There seems to still be quite a bit of missing functionality still in the analyzer implementation, see discussion at the end here:  https://github.com/dart-lang/sdk/issues/27969 .

**Comment by mit-mit** [comment]
Can we go ahead and update changelog.md now?

**Comment by dgrove** [comment]
Any updates on this?

**Comment by dgrove** [comment]
@leafpetersen @floitschG can we please finish this for 1.24?
