### ISSUE TITLE
Implement strong mode least upper bound

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#27525]
This is a tracking bug for implementing proper least upper bound (and greatest lower bound) for strong mode in Dart 1.5
- [ ] Language team decision on static semantics (private issue): https://github.com/dart-lang/dart-lang-evolution/issues/108
- [ ] Specification issue: TODO
- [ ] Analyzer implementation issue: TODO

**Comment by floitschG** [comment]
Status update:
This issue is mainly about speccing. We do have a solution, but there is room for improvement. Future changes could result in breakage, and it would be good if we were confident in the solution for 1.50.
This issue might slip for 1.50. Either, we would be stuck with the current (working but not perfect) solution, or we would need to do a breaking change for strong-mode users.

Plan:
- Leaf (assigned) writes down an informal brief approach.
- We will see if we can find someone to spec it out.

**Comment by leafpetersen** [comment]
status: we should have a final decision this week, then will be ready for implementers.  We are planning a pre-submit run to see if we can successfully eliminate the use of LUB from inference.

**Comment by mit-mit** [comment]
I don't seen an update here since the "final decision this week" comment made almost a month ago/ Are we still pursuing this for 1.50, or should we punt it?

**Comment by leafpetersen** [comment]
Removing from 1.5.

**Comment by jmesserly** [comment]
Should we merge https://github.com/dart-lang/sdk/issues/25821 into this issue?

**Comment by nex3** [comment]
Did this get fixed?

**Comment by leafpetersen** [comment]
We didn't find anything satisfactory before Dart 2 shipped.  I'd still like to look for something better here, but it will be a breaking change.  In any case, I don't think this issue is useful for tracking it.

**Comment by nex3** [comment]
Where should I subscribe to get updates for whatever improvement ends up happening?
