### ISSUE TITLE
Move Null to the bottom of nullable types

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#28024]
In Dart 1, `dynamic` was equivalent to both `top` (aka `Object`) and `bottom` (subclass of every type). In strong mode, `dynamic` only stands for `Object` (+ dynamic calls). This means that a `List<dynamic>` is not a subclass of `List<int>` anymore.

Usually, there are ways to replace `dynamic` with a better type, but in some cases, one would actually want to provide a type that is a subtype of all other types. A very common one is, for example, `const <Bottom>[]` where the constant empty list would like to be used for any other list.

Since, in Dart1, all types are nullable, the `null` value dynamically already has the bottom type. With this bug we also change the `Null` type to be at the bottom of the typing hierarchy: `Null <: A` for every `A`. This makes sense: `List<Null>` is a `List<int>` (since `null` is an `int`).

Once we have nullable types we should introduce a non-nullable version of `Null` (called `Nothing`). See https://github.com/dart-lang/sdk/issues/27488

- [x] spec https://github.com/dart-lang/sdk/issues/28028
- [x] analyzer https://github.com/dart-lang/sdk/issues/28027
- [x] dart2js https://github.com/dart-lang/sdk/issues/28026
- [x] vm https://github.com/dart-lang/sdk/issues/28025
- [ ] Make sure changelog has an entry for this

**Comment by a-siva** [comment]
Can we add some negative and positive tests for this feature so that we can verify the implementations.

**Comment by mit-mit** [comment]
Spec is complete, moving this to 1.22 for implementation.

**Comment by mit-mit** [comment]
Siva wrote:
> Can we add some negative and positive tests for this feature so that we can verify the implementations.

@floitschG do we have some shared tests in place?

**Comment by lrhn** [comment]
I have landed a test (language/null_bottom_test) and Johnni has landed some too when he made the dart2js implementation (`null_is_bottom{,_type}_test`).

If you find something that isn't covered, please say so, and I'll add to the tests.

**Comment by leafpetersen** [comment]
Issue to clarify what methods are on `Null` and `bottom` here:

https://github.com/dart-lang/sdk/issues/28430

**Comment by mit-mit** [comment]
Marking dart2js and vm done

**Comment by mit-mit** [comment]
Marking Analyzer done

**Comment by mit-mit** [comment]
Assigning to Florian for getting changelog updated.
