### ISSUE TITLE
Meta issue for implementation of overriding fields in strong mode

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#28117]
Strong mode needs to support overriding a field in a subclass. This meta-issue tracks that.

Blocking implementation issues:
- [x] DDC, support override with @virtual: #27385
- [x] Analyzer, support new mixin restrictions, #28809
- [x] DDC, always assume field overrides: #28119
- [x] Analyzer, remove current restriction: #28120 (blocked on #28119)
- [x] Make sure changelog has an entry for this

Specification work:
* Informal specification for new mixin restrictions
* Specify if we have [@sealed](https://github.com/dart-lang/sdk/issues/27502) or not ([current draft](https://github.com/dart-lang/dart-lang-evolution/blob/27e257dcc7d02233cfce059a331469427dd9ac36/proposals/sealed-members.md))
* Specify any additional restrictions on field/field overrides: #28810
* Full specification (if needed, i.e. if anything changes from the current language)

Cleanup tasks:
* Desupport `@virtual` annotation support on fields (see https://github.com/dart-lang/sdk/issues/28589)

**Comment by leafpetersen** [comment]
Updated initial comment per latest decisions.

**Comment by mit-mit** [comment]
@kasperl @leafpetersen can we update the 'specification' section in the top comment, please? I believe we have that finalized now?

**Comment by jmesserly** [comment]
FYI, after https://github.com/dart-lang/sdk/commit/1c504f89452d52f902a8c3591bde0f172452de21 I think we just need a changelog entry

**Comment by mit-mit** [comment]
Hooray, thanks Jen!

**Comment by jmesserly** [comment]
I have a changelog entry in the works too, FYI! https://github.com/dart-lang/sdk/pull/29183

**Comment by mit-mit** [comment]
Changelog landed, closing!

**Comment by jmesserly** [comment]
\o/
