### ISSUE TITLE
Closure conversion

### ISSUE THREAD

**Issue by karlklose** [dart-lang/sdk#28126]
_From @peter-ahe-google on October 5, 2016 8:56_

Meta issue for tracking known issues in closure conversion.
- [x] VM assertion error: expected: !is_cycle_free() #38.
- [x] for loops #32.
- [x] capture this.
- [x] static tear-off methods #39.
- [x] super calls #35.
- [x] type variables #36.
- [ ] tear-off methods #34.
- [ ] use VM context and function pointers #37.

_Copied from original issue: dart-lang/kernel#33_

**Comment by sjindel-google** [comment]
We don't care to ever transform tear-offs, since their implementation in a backend uses much the same machinery as the MakeClosure primitive we are transforming to, and converting them requires whole-program transformation.

**Comment by sjindel-google** [comment]
The current blocking factor in closure conversion is a variety of failing fringe tests, from debugging to hot reload.

**Comment by natebosch** [comment]
Is this still an issue?
