### ISSUE TITLE
Remove comment-based syntax for generic methods

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#28796]
We currently support and in some places still use the transitional `/*<T>*/` syntax for generic methods. Now that real syntax is supported, we should phase out and then eliminate the old syntax.

I can file tracking bugs for the sub-issues if people want, but, for now, here's the known subtasks:

- [ ] Add a deprecation notice when the old syntax is detected. *(Do we need to do this?)*
- [ ] Remove support in analyzer for parsing the comments and treating them as annotations.
- [ ] Remove uses of the syntax in our core libraries.
- [ ] Remove uses of the syntax in other packages and applications we maintain.

Currently, there are a few places where we still deliberately use the old syntax:

* The LineSplitter class behaves differently depending on if you enable strong mode or not.
* Some 'as' checks are marked as `as Object /*=ConcreteClass*/` for performance reasons because implementations do not currently take advantage of strong mode.

We'll want to ensure those are addressed first before the syntax is removed.

**Comment by bwilkerson** [comment]
We should also remove uses in our own code before removing support from analyzer.

**Comment by munificent** [comment]
Yes! I didn't intend that to be an *ordered* list, but I can see how it looks like it. Re-ordered. :)

**Comment by srawlins** [comment]
That LineSplitter behavior you note, is there an issue for that? Is it an issue?

**Comment by anders-sandholm** [comment]
At least the "Add a deprecation notice when the old syntax is detected" part should be 1.23. 
No?

**Comment by dgrove** [comment]
Is this actually happening for 1.23? I don't think there are open tasks for, say, the analyzer for 1.23.

**Comment by leafpetersen** [comment]
@floitschG how close are we to eliminating this from the core libraries?

@srawlins Is internal code in a good state with respect to this yet?

@kevmoo Do we have a plan for external packages?

**Comment by kevmoo** [comment]
@leafpetersen I'd LOVE if we had a milestone w/ a hint/lint that told folks if they have these anywhere and help folks migrate.

@bwilkerson @pq – possible?

**Comment by floitschG** [comment]
Will be removed when we don't support dart 1.x semantics anymore.

**Comment by bwilkerson** [comment]
It's quite possible to have a hint warning people that this functionality is about to go away, but I'm not sure whether that's the right UX. While it would be nice to be told that these issues exist and to provide help finding all of the places that need to be fixed, having several hundred to thousands of hints in the Dart Analysis view would be annoying.

@jwren @devoncarew Any ideas for a better UX? Maybe we could filter them by default (and explain how to see the rest).

**Comment by kevmoo** [comment]
Better UX: have a tool that auto-converts things.

Even having it as a lint (opt-in) would be great for folks that want to
make sure they've migrated everything.

Otherwise we can just run grep – but that's a less-than-ideal solution for
our external users

**Comment by srawlins** [comment]
@leafpetersen internal code has many examples of using the example syntax, but it should be easy to clean.

I only see a few instances of using `as dynamic /*=MyClass*/`. The SDK definitely has more.

**Comment by devoncarew** [comment]
A hint makes sense - something like a warn on deprecated language features hint.

**Comment by srawlins** [comment]
This is blocked by #28773 (which I think is essentially the 2nd checkmark in this issue's description).

**Comment by srawlins** [comment]
This is also soft blocked by #31091; customers cannot prepare for real-only syntax by migrating methods named `get` to real-only syntax, until there is a dev release with #31091 fixed.

**Comment by rakudrama** [comment]
When I patched https://dart-review.googlesource.com/c/sdk/+/8705, I saw some significant regressions on dart2js and dart2js html benchmarks.

**Comment by srawlins** [comment]
Done?
