### ISSUE TITLE
`void` arrow functions should allow any rhs type

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#28939]
It is no longer a static type warning if an arrow function (declared with `=>`) has a body which is an expression of a type that is not assignable to `void`.

- [x] dart2js https://github.com/dart-lang/sdk/issues/28941
- [x] analyzer https://github.com/dart-lang/sdk/issues/28940
- [x] spec https://github.com/dart-lang/sdk/issues/28942
- [x] changelog #29646.

**Comment by mit-mit** [comment]
Punting to 1.24 per dart-leads discussion.

**Comment by eernstg** [comment]
Punting to 1.25, in agreement with Kasper: The 1.24 release does not depend on the concrete spec change, and the issue is well-understood.
