### ISSUE TITLE
In checked mode, `void` should allow any value.

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#28935]
In checked mode, `void` should allow any value.

- [x] spec https://github.com/dart-lang/sdk/issues/28936
- [x] dart2js https://github.com/dart-lang/sdk/issues/28937
- [x] VM https://github.com/dart-lang/sdk/issues/28938

**Comment by mit-mit** [comment]
Punting to 1.24 per dart-leads discussion.

**Comment by eernstg** [comment]
Punting to 1.25, in agreement with Kasper: The spec part was moved to 1.25 and this meta issue awaits that.

**Comment by sgrekhov** [comment]
What about analyzer, guys? Now, it doesn't support this feature
```dart
void foo() {
  String s = "foo";
  return s;
}

main() {
  foo();
}
```
In a nostrong mode it produces:
`warning - The return type 'String' isn't a 'void', as defined by the method 'foo'`
In a strong mode:
`error - The return type 'String' isn't a 'void', as defined by the method 'foo'`

dartanalyzer version 1.24.0-dev.4.2

**Comment by eernstg** [comment]
> What about analyzer..

That's issue #28940, part of #28939, and it was landed last week. Here's the 1.24.0-dev.2.0 versus most recent commit behavior:
```
> dartanalyzer tests/language/void_arrow_return_test.dart
Analyzing tests/language/void_arrow_return_test.dart...
  warning • The return type 'int' isn't a 'void', as defined by the method 'foo' at tests/language/void_arrow_return_test.dart:7:15 • return_of_invalid_type
1 warning found.
> out/ReleaseX64/dart-sdk/bin/dartanalyzer tests/language/void_arrow_return_test.dart
Analyzing tests/language/void_arrow_return_test.dart...
No issues found!
> git sha1
d91f228766a2c1708bec8f62bbe2756e4a529f5e
```
So the only reason why you don't see it yet is that it is still in the release pipeline.

**Comment by eernstg** [comment]
All done, closing.
