### ISSUE TITLE
Updates to `void`.

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#28943]
`void` will be updated in the following way:

- [x] in checked mode, `void` accepts any value. The old behavior only allowed `null`. https://github.com/dart-lang/sdk/issues/28935
- [ ] an arrow function (declared with `=>`) is allowed to have expressions of any type if the return type is `void`. For example `void foo() => x++;`. https://github.com/dart-lang/sdk/issues/28939
- [ ] `void` is allowed as a type argument to generics. The most common use cases are things like `Future<void>` or `Visitor<void>`. Statically and dynamically, in Dart 1, a generic `void` is treated similar to `Object`, *except* for functions, where the old behavior is maintained. In particular, a `void`-function is not assignable to an `int`-function (or any other non-`void` function). https://github.com/dart-lang/sdk/issues/27504

**Comment by mit-mit** [comment]
Punting to 1.24 per dart-leads discussion.

**Comment by dgrove** [comment]
@floitschG - all of the void changes look unlikely to land for 1.24, from what I see. Can these move to 1.25?

**Comment by terrylucas** [comment]
@dgrove
Dan is this a feature we want post 1.24 Dartium?
