### ISSUE TITLE
we should enhance our CI system so that it's not possible to commit Dart code with analysis errors

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#29318]
See https://github.com/dart-lang/sdk/commit/69fa11d912b5670079d02b0d76c1b5abcbe8a7a7, a fix for a different CL committed several days earlier, introducing analysis errors into the codebase. This happens on a regular basis - developers not using analysis server based products commit broken code, and the CI system doesn't notice or complain.

I believe the steps here are:
- [x] fix the command-line analyzer so that it respects analysis_options.yaml file excludes https://github.com/dart-lang/sdk/issues/26212
- [ ] enhance the CI system so that you can analyze a project as part of the build (currently only code referenced by tests gets analyzed; we want to be able to do something like analyze all of pkg/dev_compiler)
- [ ] change most or all of our packages in `//pkg/` to being analyzed on every commit

/cc @whesse, @bwilkerson

**Comment by bwilkerson** [comment]
We've done most of the work already. We have a try-bot running this analysis of all of the analyzer code (modulo analyzer_cli because we need the first step to be done first), but we need to move it from a try-bot to a regular bot. (There's a separate issue for the second two steps, but I'm not taking the time to look for it right now.)

**Comment by whesse** [comment]
The builder that analyzes packages in /pkg is on the regular waterfall, at https://build.chromium.org/p/client.dart/builders/analyze-linux-be
It is not a try-bot, if by that you mean it is on the dart.fyi waterfall.

**Comment by devoncarew** [comment]
This is mostly done - all the code in `pkg/` is now analyzed, as well as a few other projects in the repo.
