### ISSUE TITLE
publish 0.30.0 of package:analyzer

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#29516]
We want to publish a `0.30.0` of package:analyzer. This will unblock clients like dartdoc and give people access to the 1.23.0 version of the analyzer APIs (including changes to the element model for the new generic function syntax).

- [x] introduce token API changes for better compatibility with fasta @danrubel 
  - [x] backport changes to 0.29.0; publish that version @danrubel 
  - [ ] test changes on the package versions used internally @danrubel 
- [x] validate against package:test, widen package:test's analyzer dep to include 0.30.0 https://github.com/dart-lang/test/issues/592
- [x] send a message to analyzer-discuss@dartlang.org letting them know about the upcoming version rev
- [x] publish `0.30.0`; bump and publish `kernel` and `front_end` at the same commit

/cc @danrubel @bwilkerson @pq @jcollins-g

**Comment by danrubel** [comment]
https://github.com/dart-lang/sdk/pull/29519

**Comment by devoncarew** [comment]
🎆

**Comment by devoncarew** [comment]
(see related PRs in https://github.com/dart-lang/dart_style/pull/625 and https://github.com/dart-lang/dartdoc/pull/1395)

**Comment by devoncarew** [comment]
Published! Closing...
