### ISSUE TITLE
Migrate language and library tests to Dart 2.0

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#30183]
This is the main metabug to track migrating these tests over to be tests of Dart 2.0 (roughly, "strong mode") and not the old Dart 1.0 optional type semantics.

- [x] #30182 Run strong mode analyzer tests on analyzer bot 
- [x] #29794 Update version of d8 in the repo
- [x] #30193 Change DDC bots to use d8 instead of drt
- [ ] #30529 Remove "static type warning" from test.dart

**Comment by munificent** [comment]
This is very done.
