### ISSUE TITLE
Meta Issue - Tracks all issues needed to deploy Dart 2.0

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#30272]
This is a meta-issue to track in one place all pending tasks to ship the shared FE to all of our tools

**Analyzer integration**
  * [ ] resynthesize element model from kernel
     * [ ] convertion of kernel to EM (in progress: 73% 396/536 tests passing)
     * [ ] modify kernel to include `@informational` data
     * [ ] kernel-team: random-access support in kernel

  * [ ] implement type checker in FE
  * [ ] copy FE type-inference results to analyzer ast
  * [ ] complete fasta-parser for analyzer
     * [ ] handle mismatch in low-level error recovery
     * [ ] all of analyzer parser error messages handled in FE
     * [ ] full unit test coverage: analyzer, analysis server, code completion, dartfmt, source_gen, angular

**Error recovery revisited**
  * [ ] design error recovery for analysis purposes
    * Includes https://github.com/dart-lang/sdk/issues/30267, https://github.com/dart-lang/sdk/issues/30266
  * [ ] decisions to make: approach on compile-with-errors and reporting compile-time errors at runtime

**FE features for Dart2js integration**
  * [x] adding platform.dill to the SDK
  * [x] support for `dart:_internal` in native unit tests
  * [x] support for deferred loading (#30273)
  * [x] allow external-const-factory for fromEnvironment (#30157)
  * [x] make unnamed mixin sharing optional

**FE features for bazel integration**
  * [ ] tree shaking implementation #29954

**Kernel Support**
  * [x] inject strong mode type checks in kernel (#30270) 
  * [ ] Kernel mode should retain the existing support we have for Dart API (#29989)
  * [ ] Support for starting up from a core snapshot when using kernel files (#28056)
  * [x] Transform the kernel file directly into Dart VM heap objects when reading the kernel file (#28057)

**Dart VM and Flutter Engine/tools**
  * [x] support for using outline.dill in incremental generator (#29835)
  * [x] add outline.dill to the SDK
  * [x] Implement semantic support for generic functions (#28517)
  * [x] add kernel_service.dill and vmservice.dill to the SDK
  * [x] issues with externals in .dill and with trimmed binaries (#30111)
  * [x] hot reload issues (#30109, #30322)
  * [x] incremental generator can rebuild hot-reload delta when VM reload didn't succeed (#30377)
  * [x] Add support for dart front end when building and deploying apps using flutter tools (#28050)
  * [x] Migrate the hot reload logic to use the incremental compilation model in dart front end (#28051)
  * [x] Ensure all source level debugging works without any regressions when in kernel mode (#28063)
  * [ ] Add support to enable bootstrapping of the Dart Front End in the Dart build (#30374)
  * [x] Strong mode clean patch files for VM (#31052)
  * [x] Handle strong mode annotations in the VM (#31312)

**FE Completeness**
  * [ ] local type variables
  * [ ] other corner cases: #30266, #30258, #30034, #30031, #30196, #30284  
  * [ ] partial support for conditional imports: #30143
  * [ ] revisit existing test discrepancies

**Speed**
  * [x] create benchmark for incremental kernel generator and hot reload
  * [ ] Performance of hot reloading a flutter app with the new front-end is acceptable (#28090)
  * [ ] Performance of initial load and startup of a flutter app with the new front-end (#28089)
  * [ ] Performance of command line dart with new front-end running dart programs is acceptable (#28088)

**Memory footprint**
  *  [ ] Kernel front-end increases memory footprint by over 5x (#28585)

**Maturity & Cleanup**
  * [x] support for libraries.json #29882 
  * [x] support for patching
  * [ ] uniform error handling #30080
  * [ ] prevent missing context in unit tests #30269
  * [ ] track outer package dependencies #30271
  * [ ] provide better error messages for bad options in public API (#30254, #30256)
  * [ ] make FE strong clean #28673

**Comment by zanderso** [comment]
There's also this older issue here: https://github.com/dart-lang/sdk/issues/28048

From there, more specific performance related issues are here:
- [ ] Performance of hot reloading a flutter app with the new front-end is acceptable  https://github.com/dart-lang/sdk/issues/28090,
- [ ] Performance of initial load and startup of a flutter app with the new front-end https://github.com/dart-lang/sdk/issues/28089,
- [ ] Performance of command line dart with new front-end running dart programs is acceptable https://github.com/dart-lang/sdk/issues/28088.

Issues related to memory footprint are also still open here:
- [ ] Kernel front-end increases memory footprint by over 5x https://github.com/dart-lang/sdk/issues/28585,
- [ ] Transform the kernel file directly into Dart VM heap objects when reading the kernel file https://github.com/dart-lang/sdk/issues/28057

If some of these issues are already addressed, please close them.

**Comment by bwilkerson** [comment]
Re: full unit test coverage for the parser. Should we also be testing packages such as 'source_gen' that are heavily dependent on analyzer?

The list above explicitly mentions parser errors and type checking. Do we have a clear road map for generating other errors in FE? Do we have a plan for how we're going to handle discrepancies between the errors produced by FE and those produced by analyzer? (This impacts quick fixes and the "// ignore" feature.

**Comment by sigmundch** [comment]
> Re: full unit test coverage for the parser. Should we also be testing packages such as 'source_gen' that are heavily dependent on analyzer?

yes, added them to the list as well

> Do we have a clear road map for generating other errors in FE? Do we have a plan for how we're going to handle discrepancies between the errors produced by FE and those produced by analyzer? (This impacts quick fixes and the "// ignore" feature.

I'll start a thread offline about this.

**Comment by a-siva** [comment]
I am setting the milestone of this bug as 2.0-Beta1 which is more reasonable as we want all the above to be done before declaring beta complete.

**Comment by chalin** [comment]
Which subitem can I use to track the added support of runtime checks to dart2js and the VM? I see no item for "implement runtime checks" (for strong mode features). I'd like to use such an issue in the Strong mode docs.

cc @kwalrath

**Comment by a-siva** [comment]
issue #31312 was used to track support for runtime checks in the VM

**Comment by chalin** [comment]
@a-siva - thanks. The issue is closed, so will VM support be available in the next dev release (2-dev.27)?

**Comment by a-siva** [comment]
We are consolidating all the Dart 2 features under the --preview-dart-2 flag and this consolidation should happen by the next dev release (2-dev-24).
In 2-dev-23 you should be able to pass the flags 
--preview_dart_2 --strong --reify-generic-functions
to get the strong mode runtime checks.

**Comment by chalin** [comment]
Thanks, `--preview_dart_2 --strong --reify-generic-functions` seems to be doing the trick.

**Comment by chalin** [comment]
@a-siva - when will `--strong` and `--reify-generic-functions` be placed "under" `--preview-dart-2` (so that we need only use one option)? And is there an issue I can follow to track that?

**Comment by a-siva** [comment]
We are one CL away from @sivachandra to get to that point, I have created #32296 to track this

**Comment by dgrove** [comment]
We're now tracking issues needed for Dart2 Stable in the Dart2-Beta 3/Beta4/Stable milestones. Closing this meta-issue.
