### ISSUE TITLE
Remove support for packages directory

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#30384]
Starting on the list

- [ ] `dart:io` `Platform.packageRoot`
- [ ] `dart:isolate` `Isolate.packageRoot`

Related:

- [ ] Remove support from `pkg:package_resolver` – bug needed
- [ ] Remove use from `pkg:test` - bug needed

**Comment by zanderso** [comment]
Why is this P1?

**Comment by Stargator** [comment]
@zanderso I believe its short for "Priority 1" ie Highest priority.

**Comment by kevmoo** [comment]
> Why is this P1?

It's cleanup that would be ideal in v2 – since it'll be easier to get away with breaking changes.

**Comment by dgrove** [comment]
Any updates on this, @kevmoo ?

**Comment by kevmoo** [comment]
There was discussion in email about Fuscia needing/wanting packages directories still.

@zanderso @a-siva ??

**Comment by dgrove** [comment]
@kevmoo will follow up on this to see what users would be affected.

**Comment by dgrove** [comment]
@MichaelRFairhurst any updates here?

**Comment by dgrove** [comment]
Any updates on the plan here?

**Comment by MichaelRFairhurst** [comment]
Strawman CL, which seems to have no issues internally: https://dart-review.googlesource.com/#/c/sdk/+/59100

**Comment by dgrove** [comment]
Can this issue be closed at this point?

**Comment by kevmoo** [comment]
Should we leave it open to actually remove the APIs? They are just
deprecated + noop now...

**Comment by dgrove** [comment]
Once this CL lands, I suggest that we remove the milestone. Landing the noop version of this is enough to allow the VM team to shed the underlying code.

**Comment by MichaelRFairhurst** [comment]
Agreed -- now that https://dart-review.googlesource.com/c/sdk/+/60062 is landed, the packages/ directory won't work with or without dart 2. And the deprecations have already been published.

Its now clear -- as far as I can tell -- to be cleaned up at anyone's whim!

**Comment by whesse** [comment]
This issue is marked closed, but nobody has ever done the work described, of actually removing the APIs. Shouldn't it be reopened until somebody does?

**Comment by kevmoo** [comment]
These are all done a long time ago!
