### ISSUE TITLE
Meta: Static requirements on type annotations for initializing formals

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#30816]
### Intention to implement

In Dart 2, an initializing formal can have an explicit type annotation. It is a compile-time error if such a type annotation is not a subtype of the static type of the corresponding instance variable.

Example:

```dart
class C {
  num a;
  C.sameType(num this.a);
  C.subType(int this.a);
  C.superType(dynamic this.a);  // Compile-time error
  C.unrelatedType(String this.a);  // Compile-time error
}
```

### Tool specific issues

- [ ] Fasta (#TBA)
- [ ] analyzer (#TBA)
- [ ] vm (#TBA)
- [ ] dart2js (#TBA)
- [ ] dartdevc (#TBA)
- [ ] dartfmt (dart-lang/dart_style#TBA)
- [ ] IntelliJ plugin (#TBA)
- [ ] Language specification  (#TBA)

### Background

In Dart 1.x, it is allowed for an initializing formal `x` to have a type annotation, which is then used for static type checks on the corresponding actual arguments. If there is no such type annotation, the static type of the initializing formal (say, `x`) is taken to be the same as the static type of the corresponding instance variable (which is also named `x`).

It may seem counter-intuitive that it is allowed to have a different type annotation on the initializing formal than the one on the instance variable, but it allows for certain invariants to be established that the language cannot otherwise express:
```dart
class AddablePair {
  final Object x, y;
  AddablePair.ofInts(int this.x, int this.y);
  AddablePair.ofStrings(String this.x, String this.y);
}
```
In Dart 1.x, it is also possible to use a supertype of the instance variable type:
```dart
class UselessTypeCheck {
  int i;
  UselessTypeCheck(num this.i);
}
```
We may then have `new UselessTypeCheck(3.14)` which will be allowed statically and fail dynamically.

The language discussed the situation and agreed that no _useful_ call sites will be enabled by allowing any other types than subtypes for such a type annotation.
