### ISSUE TITLE
Add unsigned shift operator.

### ISSUE THREAD

**Issue by floitschG** [dart-lang/sdk#30886]
Together with fixed-size integers, Dart gains the `>>>` operator (unsigned shift).

The operator has the same precedence as `>>`. 
The expression `e1 >>> e2` is a compile-time constant expression if both `e1` and `e2` are compile-time constant expressions evaluating to integers (and `int` will implement the operator).
The symbol `#>>>` is valid, as is `x >>>= e` as an expression.

Adding the new operator is non-breaking.

- [x] specification
- [ ] Frontend https://github.com/dart-lang/sdk/issues/30888
- [ ] dart2js https://github.com/dart-lang/sdk/issues/30890
- [ ] DDC https://github.com/dart-lang/sdk/issues/30891
- [ ] VM https://github.com/dart-lang/sdk/issues/30892

**Comment by rashedmyt** [comment]
waiting for this operator to be in release

**Comment by kevmoo** [comment]
@lrhn what's the story with this?

@aadilmaan @mit-mit – are we tracking this somewhere?

Related: https://stackoverflow.com/questions/57190508/does-dart-have-operator/57210971

**Comment by mit-mit** [comment]
This is now tracked in https://github.com/dart-lang/language/issues/120. Closing the present historical issue.
