### ISSUE TITLE
Optional `new` and `const` for Dart 2 (meta issue)

### ISSUE THREAD

**Issue by lrhn** [dart-lang/sdk#30921]
Dart 2 will make `new` and `const` operators optional in some cases. The feature is described in https://github.com/dart-lang/sdk/blob/master/docs/language/informal/implicit-creation.md.

This feature needs support from, at least, the common front-end. The kernel compiler can, and likely will, generate the same kernel code whether an optional `new` or `const` is present or not, so back-ends should be unaffected. Effectively, the kernel (or even the parser) can perform automatic "new/const" insertion on the program, as soon as it can recognize an invocation as referring to a constructor rather than a static method.

The feature extends the grammar with syntax that wasn't previously valid, so the formatter likely needs to be prepared for it. 
The analyzer may need to be prepared for the different syntax as well.

We will not back-port this feature to non-kernel based backends.

- [x] Front-end (#30922)
- [x] Formatter (https://github.com/dart-lang/dart_style/issues/652)
- [x] Analyzer (#30923)
- [ ] Angular: https://github.com/dart-lang/sdk/issues/33221
- [ ] Communication when the feature is ready
- [ ] Remove new and optional const from SDK code 
- [ ] Specification (#30924) - this is dartLangSpec.tex, the [feature specification](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/implicit-creation.md) has already been landed.

**Comment by peter-ahe-google** [comment]
We will not start implementation of this feature until the front-end is on par with the VM in terms of test passes.

**Comment by bwilkerson** [comment]
@munificent I don't think there's any work for the formatter, but it would be good to double check that.

**Comment by eernstg** [comment]
About the need to adjust the formatter, and possibly other tools: The grammar had to be extended with support for a new construct, namely
```
constructorInvocation ::=
    typeName typeArguments '.' identifier arguments
```
and that construct is then used in a couple of places. The point is that we can now have things like `C<int>.someName(42)`, and the ability to have actual type arguments after the class name is new. So every tool that has a parser which hasn't already been updated to handle this will need an update.

**Comment by bwilkerson** [comment]
Yep, but the formatter uses the analyzer parser, so I think it's probably fine.

**Comment by munificent** [comment]
Turns out there is one case the formatter needs to handle:

```dart
SomeGenericClass<int>.someNameConstructor();
```

I added support for that in https://github.com/dart-lang/dart_style/commit/b89b572673c30d6124d61bda69710ac4d25c2e56.

**Comment by dgrove** [comment]
Moving this to Dart2-Beta 3 milestone https://github.com/dart-lang/sdk/milestone/53 .

**Comment by dgrove** [comment]
Actually, since this is the meta issue that has the spec as the long pole, moving to the Dart2 Stable milestone.

**Comment by leafpetersen** [comment]
The formal spec bug is the only remaining issue, so closing this out.

**Comment by stevenroose** [comment]
Should this also work for factory constructors? I'm getting
```
NoSuchMethodError: No static method 'from' declared in class 'BigInt'.
``` 
when calling `BigInt.from(5)`, f.e.

`BigInt.from` is an `external factory` constructor.

**Comment by lrhn** [comment]
It should work for all constructors. How are you running the code?

**Comment by stevenroose** [comment]
@lrhn I have Dart v2 installed at `/opt/dart-v2` and I run `/opt/dart-v2/bin/pub run test`. 

I could be that `pub test` runs the `dart` executable in `PATH` instead of the one in the same directory.. Can I pass to pub which Dart executable to use?

**Comment by zoechi** [comment]
@stevenroose perhaps https://github.com/dart-lang/pub/issues/1807

**Comment by leafpetersen** [comment]
Re-opening to track Angular implementation + communication and validation.

**Comment by matanlurey** [comment]
Good news. AngularDart has verified, mostly thanks to @MichaelRFairhurst, that optional new/const works at the latest dev SDKs, including in metadata annotations. Here is a sample PR where we removed it from all example applications: https://github.com/dart-lang/angular/pull/1408.

**Comment by jodinathan** [comment]
great news indeed!

Atenciosamente, 

Jonathan Rezende

**Comment by dgrove** [comment]
@kwalrath is the docs part of this complete?

**Comment by kwalrath** [comment]
It depends on what you mean by "complete". The [language tour](https://www.dartlang.org/guides/language/language-tour) has a note that `new` is optional.

I'm working on a PR to improve on that (making optional `new` the default in the tour, and adding an example for optional `const`).

For the rest of the docs and examples, we're planning to wait until `dartfmt --fix` is out.

Tracking issue: dart-lang/site-www#870

**Comment by leafpetersen** [comment]
Nothing left here is blocking for Dart 2 here, I think.   As soon as `dartfmt --fix` is available for general use, we should announce this, and encourage people to migrate.  

@munificent should we consider adding this to the dartfmt presubmit for the SDK now to start migrating and shaking out bugs?  We probably *really* don't want to do that for tests though, so we'd need some way to exclude them.  So maybe better to just start manually converting SDK code?

**Comment by munificent** [comment]
> So maybe better to just start manually converting SDK code?

Yeah, I think running `--fix` manually is a better first step.

**Comment by natebosch** [comment]
Does the Dart VM read SDK code when you run with `dart --no-preview-dart-2`?

Does dart2js read SDK code when you compile with `dart2js --no-preview-dart-2`?

If so, dropping `new` and `const` from the SDK is blocked on removing those flags.

**Comment by sigmundch** [comment]
> Does dart2js read SDK code when you compile with dart2js --no-preview-dart-2?

dart2js does - we use the CFE even in Dart1 mode, and the CFE will parse with the missing new/consts always (it is not hidden under a flag).

**Comment by mit-mit** [comment]
@lrhn what remains before we can close this as completed?

**Comment by lrhn** [comment]
SDK and specification still missing. I guess communication is part of communicating Dart 2.0.

**Comment by srawlins** [comment]
Should "Remove new and optional const from SDK code" still be part of this task? This meta issue was a planned feature for Dart 2.0, which has completed. AFAIK, no one intends to do this task any time soon. Especially with all of the work being done on the SDK libraries; this would cause a lot of churn if it landed any time in the next few months.

Close this meta issue?

**Comment by Stargator** [comment]
@srawlins I would say keep it here as a means of tracking it. That doesn't mean it has to be prioritized higher than the current work on the SDK libraries.

**Comment by munificent** [comment]
I'm not sure when it happened, but a quick search in the core libraries for `new` doesn't seem to turn up much outside of docs and JS interop code. I think this is done.
