### ISSUE TITLE
Asserts in initializers

### ISSUE THREAD

**Issue by munificent** [dart-lang/sdk#30968]
Flutter likes it, so the language team considers [the experiment](https://github.com/dart-lang/sdk/issues/27141) a success and will ship [asserts in constructor initialization lists](https://github.com/dart-lang/sdk/blob/master/docs/language/informal/assert-in-initializer-list.md) in Dart 2.0.

Work remaining to be done:

- [x] Support it in dart2js (#30038)
- [x] Support it in dartdevc (#27809)
- [x] Support in front-end (#30914)
- [x] Specify it (#30967)
- [x] Enable it by default and remove flag in VM (#30976)
- [x] Enable it by default and remove flag in analyzer (#30977)
- [ ] Document and announce it

**Comment by dgrove** [comment]
@munificent @kwalrath is there any more to do on the docs/announce front? If not, let's close this.

**Comment by kwalrath** [comment]
The language tour should cover asserts in initializers (and probably have more initializer coverage, in general). I've added this to dart-lang/site-www#507.

**Comment by munificent** [comment]
Yeah, aside from what Kathy said, I don't see any need to trumpet this feature from the heavens. It's pretty minor.

**Comment by rkj** [comment]
Any documentation? I just tried to use it, but cannot use foreach in the assert body, which makes it less usable than I would like (I wanted to verify that a map passed to the constructor doesn't have null values)

**Comment by munificent** [comment]
No doc that I know of. The spec changes landed here https://github.com/dart-lang/sdk/commit/609d26a2274ccde0f74725f4df7e081ebc8ea020, https://github.com/dart-lang/sdk/commit/a72f46def8899b6f1a7fc5609f3b503c5d79b16f.
