### ISSUE TITLE
tracking issue for shipping managed imports on paste

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#31456]
This is the overall tracking issue for shipping managed imports on paste.

- [ ] disable until P1s resolved
- [ ] misc update imports on Paste issues #31238
- [ ] issues when copying entire file #31240
- [ ] offered to add imports when copy and pasting in the same file #31373
- [ ] re-enable
- [ ] streamlined IntelliJ UI (fewer model dialogs) https://github.com/dart-lang/sdk/issues/31239

@kevmoo @bwilkerson

**Comment by JamesMcIntosh** [comment]
Has this fallen off the priority list?
It is an incredibly unsatisfying, annoying waste of time having to continuously recreate imports when copying code around.
It's even more confusing that there is a "Update imports on paste" option in the preferences which doesn't do anything.

**Comment by cbenhagen** [comment]
@devoncarew / @kevmoo any chance that this get's re-enabled soon? If not, maybe the option should be removed from the plugin.
