### ISSUE TITLE
Support full type inference in the analyzer

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#31638]
This list might be incomplete. To help avoid missing cases we should test all the cases in pkg/front_end/testcases/inference and pkg/front_end/testcases/inference_new.

- [ ] Top-level type inference: report errors when analyzer and front_end types would differ, such as
 - Unrestricted top level inference
 - Circularity detected
 - Inconsistent inheritance
- [ ] Infer Object arguments instead of Null - https://github.com/dart-lang/sdk/issues/31546
- [ ] Fix type inference of closures using ‘=>’ syntax: https://github.com/dart-lang/sdk/issues/31436
- [ ] Improve for-in statement inference: https://github.com/dart-lang/sdk/issues/31440
- [ ] Improve compound assignment inference (cded10154cad729a3b26ead74f739779e1cfd344)
- [ ] Use “bool” as the downward inference context for assert conditions (ae4cbb50af4d1c6055a3cf66c4992f1e91df4ce7), while/do loops (213c2080a53d3c9ef2a9ade8ef083aba0777e544), and logical operators (3b6f276c843f9d42d32d901627fe805b01a5ba5e)
- [ ] Use the type of the switch expression as the context for case expressions (b94fdceadceff70622673bc57d0f1e9c9d0ab011)
- [ ] Correctly infer list/map types when outside a method body (a7ab70eb06424e610f340d19c105599aa7b15056)
- [ ] Fix inference of methods returning “void” outside of a method body (c4ecf098aadf92155a2654a01ffe0b82628ce7f4)

**Comment by devoncarew** [comment]
@stereotype441 can you please vet this and make sure this tracks the work we want to do?

**Comment by stereotype441** [comment]
SGTM as a starting point.  We may decide to skip some of the subtasks if their impact is minimal, but I think for now we should plan on doing all of them.

**Comment by stereotype441** [comment]
I'm going to start working on this now.  If others would like to help, please let me know so that we can divide up sub-tasks.

**Comment by vsmenon** [comment]
@stereotype441 @devoncarew 

Re "Make it an error if a class includes in its super-interfaces the same generic interface twice with different type parameters":

This is an internal try at it on top of dev 16: cl/184080428

That's not for landing, just for an internal global test run.  It appears to catch the right errors.

**Comment by stereotype441** [comment]
@vsmenon thanks!  We'll use your CL as a starting point.

**Comment by bwilkerson** [comment]
@stereotype441 I'm guessing that this issue is now obsolete and can be closed. Can you close it if that's true?

**Comment by stereotype441** [comment]
No, it's not ready to close yet.  #32156 is unfinished.
