### ISSUE TITLE
Support 2.0 in the analyzer independent of the new front end

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#31640]
This is a tracking issue for supporting the Dart 2.0 semantics in analyzer without using the new front end.
- [x] Decide whether and how best to use flags to enable the below features
     update: we'll use `--preview-dart-2` to mean 'enable Dart 2.0 syntax', and use `--use-cfe` to mean use the CFE
  - [x] Create a new `--use-cfe` flag to replace current uses of `--preview-dart-2`. @jwren
- [x] Support implicit new and const in the analyzer (#31633) @jwren @bwilkerson 
- [x] Support assert in initializers in the analyzer (#31634) @bwilkerson 
- [x] Support fixed-sized integers that are limited to 64 bits in the analyzer (#31635) @bwilkerson 
- [x] Support generalized void in the analyzer (#30177) @MichaelRFairhurst
- [ ] Support full type inference in the analyzer (#31638) [meta] @stereotype441 @scheglov 
- [x] re-evaluate deferred work for supporting generic function type syntax (#30761) [meta] @MichaelRFairhurst 
- [x] Start async functions synchronously (no work required)

---
Moved to post alpha2:
- [ ] Remove support for fuzzy arrows from the analyzer (#31637) @leafpetersen
  - likely extending past March 1st; mitigating existing usages; all Flutter usages should be eliminated by March 1st
- [ ] Analyzer type system fixes:
  - [ ] Instantiate to bound errors for constructors issued prematurely. #28539 (not a blocker for March 1st)
  - [ ] Raw types in bounds should be allowed when the raw type bound is ground #28580 (not a blocker for March 1st)
- [ ] Disallow returning void within a dynamic function (#32161)

**Comment by devoncarew** [comment]
@MichaelRFairhurst, I added a line above for `re-evaluate deferred work for supporting generic function type syntax` (discussed in person).

**Comment by devoncarew** [comment]
Updated the first line item with a resolution re: using flags to enable these features.

**Comment by MichaelRFairhurst** [comment]
Updated to show that #30177 is closed

**Comment by bwilkerson** [comment]
I believe that this issue is now obsolete. Please re-open if that's not true.

**Comment by stereotype441** [comment]
The checkbox for #31638 is not yet checked.  That bug is incomplete because its checkbox for #32156 is not yet checked.  #32156 is still being worked on by @jmesserly - see https://dart-review.googlesource.com/c/sdk/+/45141.  I'm going to ping that CL in the hopes that it can be landed soon, and I'll adjust #32156's priority to P1 to match this bug.
