### ISSUE TITLE
[out of date] Analyzer ready for Dart 2.0

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#31642]
This is a meta issue for tracking getting the analyzer ready for Dart 2.0.

__Dart 2.0 support in the current front end:__
- [ ] Support 2.0 in the analyzer independent of the new front end #31640 [meta]

__Analyzer integrated with the new front end:__
- [x] Scanner integration
- [ ] Parser integration
  - [x] parser completeness measured by a [script](https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/tool/fasta_migration_progress.sh)
  - [x] build AST with FE's parser [status: ast_builder w/ error recovery in progress]
  - [ ] Full coverage of parser error messages in FE
     - [ ] Every message produced by analyzer's parser should also be produced by FE's parser
   - [ ] Error recovery [status: in progress]
     - [ ] all error recovery scenarios modeled in analyzer's parser also handled by FE's parser
     - [ ] run all analyzer, analysis server (including code-completion), and dartfmt tests
- [ ] Error integration
  - [ ] spec errors copied from the FE; lints and hints from the analyzer
  - [ ] previously calculated errors are available to analyzer
- [ ] Element model and type-system integration
  - [ ] Synthesize element-model from kernel outline files
    - [ ] Implement synthesis for non-erroneous input
    - [ ] Implement synthesis for erroneous input: this requires kernel-format changes to represent erroneous code
  - [ ] Full coverage of type-system error messages
    - [ ] Every type-system error detected by analyzer's type checker are covered by FE's type-checker as well
  - [ ] Analyzer uses FE’s local type-inference information inside method bodies
- [ ] Compile time constants
  - [ ] evaluation of compile-time constants
- [ ] Benchmarking
  - [x] analysis server benchmarks support the --preview-dart-2 flag
  - [ ] fix exceptions when running the benchmark with --preview-dart-2 #31554
  - [ ] add `benchmarks.dart run --preview-dart-2 ...` to tools/bots/try_benchmarks.sh
  - [ ] add a new target analysis server to our performance benchmarking system
- [ ] Analysis server integration tests
  - [x] tests converted over to run both with and without --preview-dart-2
  - [ ] test failures addressed #31571 [meta]
- [ ] Command line analyzer (dartanalyzer supports --preview-dart-2)
  - [x] --preview-dart-2 flag added
  - [ ] dartanalyzer tests duplicated to run both with and without --preview-dart-2
  - [ ] preview-dart-2 tests triaged and failures addressed #31655
  - [ ] determine whether dartanalyzer build mode requires porting to --preview-dart-2
    - [ ] port dartanalyzer build mode to work with --preview-dart-2
- [ ] Kythe support ready for Dart 2.0 #31645 [meta]

**Comment by devoncarew** [comment]
@jwren, is there known work or investigation to ensure that our kythe support continues to work after the new FE integration? If so, can you create a meta issue to track that work and link it back to here?

**Comment by jwren** [comment]
Created #31645

**Comment by devoncarew** [comment]
@bwilkerson @sigmundch re: `evaluation of compile-time constants` above - just confirming that we currently expect that this will need to be re-implemented in analyzer?

**Comment by devoncarew** [comment]
@scheglov @MichaelRFairhurst can you vet the `Error integration` section items above? If those look good, we could link to issues for each item.

**Comment by devoncarew** [comment]
@danrubel can you review the `Parser integration` section?

**Comment by danrubel** [comment]
Parser integration section LGTM

**Comment by sigmundch** [comment]
re: compile-time constants, yes, that's my understanding too. Dart2js had to do it too.

**Comment by devoncarew** [comment]
I'm going to re-purpose this for the new AnalyzerCFE milestone, and likely break it out into new issues.

**Comment by bwilkerson** [comment]
I'm guessing that this is no longer useful, so I'm closing it.
