### ISSUE TITLE
tracking issue for dartanalyzer CLI test failures with --use-cfe

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#31655]
### ExitCodesTest_UseCFE
- [x] test_enableAssertInitializer
- [x] test_fatalErrors
- [x] test_fatalHints
- [x] test_fatalWarnings
- [x] test_missingOptionsFile
- [x] test_notFatalHints
- [x] test_notFatalWarnings
- [x] test_partFile
- [x] test_partFile_extra

### LinterTest_UseCFE
- [x] test_defaultLints_generatedLints
- [x] test_defaultLints_getsDefaultLints
- [x] test_lintsInOptions_generatedLints
- [x] test_lintsInOptions_getAnalysisOptions
- [x] test_noLints_lintsDisabled
- [x] test_noLints_noGeneratedWarnings
- [x] test_noLints_noRegisteredLints

### OptionsTest
- [ ] test_useCFE

### OptionsTest_UseCFE
- [ ] test_analysisOptions_excludes
- [ ] test_analysisOptions_excludesRelativeToAnalysisOptions_explicit
- [ ] test_analysisOptions_excludesRelativeToAnalysisOptions_inferred
- [x] test_analyzeFilesInDifferentContexts
- [ ] test_basic_filters
- [x] test_basic_language
- [x] test_basic_strongMode
- [ ] test_includeDirective
- [ ] test_previewDart2
- [x] test_strongSdk
- [x] test_todo
- [ ] test_withFlags_overrideFatalWarning

**Comment by devoncarew** [comment]
out of date

**Comment by devoncarew** [comment]
updated

**Comment by devoncarew** [comment]
more updates

**Comment by bwilkerson** [comment]
The CFE integration work is suspended, so this will not be addressed.
