### ISSUE TITLE
Dart 2.0 core lib update tracking issue

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#31812]
This is the tracking issue for the Dart 2.0 core lib changes and migration.

More detailed overview of the proposed changes (internal only) here: https://docs.google.com/document/d/1VOJYN557gB6i64-hdrbl2mUYPW7IJA7QOthVWNOmCTY/ .  

See the tracking issues below for additional detail.

This will be rolled out in three waves.

- [ ] Wave 1: Rename constants to use camel case
  - [x] Introduce new names, deprecate old names
  - [x] Implement migration tooling: https://github.com/dart-lang/sdk/issues/31822
  - [ ] Remove old deprecated names: https://github.com/dart-lang/sdk/issues/31813
- [x] Wave 2:  
  - [x] 2.1: New methods and signature changes in interfaces of `Iterable`, `List`, `Set`, and `Map` and `Timer`
     - [x] Add stubs to packages: https://github.com/dart-lang/sdk/issues/31664
     - [x] Fix internal code: Track internally
     - [x] Roll fixes to flutter: https://github.com/dart-lang/sdk/issues/31814
  - [x] 2.2: New methods and signature changes in interfaces of `Stream`, `StreamTransformer`, and `Converter`
     - [x] Add stubs to packages: https://github.com/dart-lang/sdk/issues/31847
     - [x] Fix internal code: Track internally
     - [x] Roll fixes to flutter: https://github.com/dart-lang/sdk/issues/31816
     - [x] Remove defaultValue: https://github.com/dart-lang/sdk/issues/32401
  - [x] ~~2.3: Tighten signatures of `List | Set | Map | Queue | ListQueue .from`~~ No longer planned
     - [x] Implement change in a branch: https://github.com/dart-lang/sdk/issues/31820
     - [x] Fix external packages: https://github.com/dart-lang/sdk/issues/31819
     - [x] Fix internal code: Track internally
     - [x] Roll fixes to flutter: https://github.com/dart-lang/sdk/issues/31818
- [x] Wave 3: Miscellaneous changes
  - [x] Add  `Invocation.typeArguments` member: https://github.com/dart-lang/sdk/issues/32402
  - [x] Add `Bigint` class to `dart:core`

- [ ] Wave 4: (Non-breaking, land anytime)
  - [ ] Add `int.clampInt` and `double.clampInt`
  - [ ] Add  `math.max` to `num.min` and `num.max`
  - [ ] Add static methods `int.min`, `int.max`,  `double.min`, `double.max`
  - [ ] Add `int.>>>` instance member

**Comment by leafpetersen** [comment]
cc @lrhn @anders-sandholm @keertip @grouma @matanlurey @srawlins @floitschG @vsmenon @dgrove @kevmoo @mit-mit @Hixie
