### ISSUE TITLE
Tracking issue for removal of deprecated SDK constant names

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#31813]
The old all caps names for constants in the SDK have been deprecated in favor of camel case versions.  This issue tracks the removal of the of old deprecated names.

TODO:
- [x] Implement tooling https://github.com/dart-lang/sdk/issues/31822
- [x] Follow up on breaking change announcement
- [x] Clean up flutter and internal package dependencies
  - https://github.com/dart-lang/sdk/issues/32749
- [x] Clean up flutter code (if required)
- [x] Clean up internal code
- [x] Remove deprecated constants

This is part of the larger Dart 2.0 corelib changes tracked here:  https://github.com/dart-lang/sdk/issues/31812 .

**Comment by Hixie** [comment]
As part of this we should have a script that automatically ports old code. We should use that to port Flutter, as a proof of concept. We should then hook that script into `flutter upgrade` to upgrade everyone's code.

**Comment by leafpetersen** [comment]
I'll file an issue for that.  We may want to consider whether we can do that for at least some of the wave 3 changes as well.

**Comment by matanlurey** [comment]
The difficulty is this would (likely) require analysis-driven refactoring.

We have an internal that is near completion for this task. We could spend a couple weeks and open source it, but this needs to be a P1 directive and coordinated ASAP, and not just be a "oh it's <some date>, we need it <this week>".

**Comment by leafpetersen** [comment]
@Hixie @mit-mit is this something we should aim to have done by March 1st, or (assuming we have an automated migration path) is this something that can be pushed into Q2?

**Comment by Hixie** [comment]
It's something we should have before we remove the uppercase constants; I'm not aware of anything that's driving us to remove them by a particular date.

**Comment by leafpetersen** [comment]
cc @lrhn @anders-sandholm @keertip @grouma @matanlurey @srawlins @vsmenon @dgrove @kevmoo

**Comment by leafpetersen** [comment]
@Hixie Is the infrastructure for upgrading user code via flutter upgrade built out already?  That is, is there an existing system which identifies user files to be updated etc can just call out to an appropriate tool?  Or does all of that need to be figured out as part of this?

**Comment by Hixie** [comment]
@xster was working on something related to this, not sure how far he got. @xster?

**Comment by leafpetersen** [comment]
Fix it package here:  https://pub.dartlang.org/packages/dart2_fix

**Comment by leafpetersen** [comment]
I'll prepare some docs and an announcement email and follow up on the relevant email lists today.

**Comment by dgrove** [comment]
What's the next step here, @leafpetersen ?

**Comment by dgrove** [comment]
dart:io is complete. What is remaining?

**Comment by lrhn** [comment]
Removal of usages in packages.
I have the non-dart:io constants removed from all SDK package dependencies. Now it's the rest of the world.
Google code can remove the constants at any time, but it'll be easier if we have a compilable CL for the SDK which removes the declarations.

**Comment by leafpetersen** [comment]
Once we have a roll to flutter this can be closed.

**Comment by leafpetersen** [comment]
We've rolled flutter, this is done.

**Comment by natebosch** [comment]
Why did we close this? The deprecated constants in at least `dart:io` still exist. Do we have another issue open to track their removal in Dart 3.0?

https://github.com/dart-lang/sdk/blob/55aa031404f36d181daf5f5b27424da431ee2e3e/sdk/lib/_http/http.dart#L568

**Comment by kevmoo** [comment]
https://api.dartlang.org/stable/2.0.0/dart-io/HttpHeaders-class.html

That's...embarrassing...

**Comment by natebosch** [comment]
SGTM considering non-dart:io constants complete and opening a new issue for dart:io constant.
