### ISSUE TITLE
Packages failing w/ 64-bit int change

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#31870]
- [x] https://github.com/dart-lang/typed_data/issues/10
- [x] https://github.com/dart-lang/googleapis_auth/issues/29
- [x] https://github.com/dart-lang/html/issues/64
