### ISSUE TITLE
Meta issue tracking analyzer Dart 2.0 type system inconsistencies

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#32395]
This issue is a meta-issue to track places where the new front end and the analyzer (using the analyzer driver's resolution) disagree. 

Update: Open issues 
  - [x] Instantiate to bounds usage is self-inconsistent: https://github.com/dart-lang/sdk/issues/32114
  - [ ] type parameters on const values https://github.com/dart-lang/sdk/issues/32918
  - [x] Generic function types shouldn't be type arguments: https://github.com/dart-lang/sdk/issues/33343
  - [ ] Carry over of 33343 (generic function types): https://github.com/dart-lang/sdk/issues/33661
  - [x] Subtyping on type bounds: https://github.com/dart-lang/sdk/issues/29014 @michaelrfairhurst
  - [x] Reserve `mixin` and `identifier`: https://github.com/dart-lang/sdk/issues/33131
  - [x] Type variable conflation: https://github.com/dart-lang/sdk/issues/33159
  - [ ] Bad typing with generic call method: https://github.com/dart-lang/sdk/issues/33194
  - [x] Future flattening shouldn't be recursive: https://github.com/dart-lang/sdk/issues/32881
  - [ ] Missing error when awaiting a void expression: https://github.com/dart-lang/sdk/issues/33415
  - [x] Error with function type syntax in generics: https://github.com/dart-lang/sdk/issues/32933
  - [ ] Partial instantiations in default values: https://github.com/dart-lang/sdk/issues/32913
  - [ ] Inconsistent call method tearoffs: https://github.com/dart-lang/sdk/issues/32864
  - [ ] Prefix scoping: https://github.com/dart-lang/sdk/issues/32248
  - [ ] Invalid Function syntax is allowed https://github.com/dart-lang/sdk/issues/33398
  - [ ] Super bounded types: https://github.com/dart-lang/sdk/issues/32903
  - [ ] Methods on null https://github.com/dart-lang/sdk/issues/27273
  - [ ] Restrict partial instantiation to known targets: https://github.com/dart-lang/sdk/issues/28162
  - [ ] Abstract super calls: https://github.com/dart-lang/sdk/issues/33662 
  - [x] Top types and LUB: https://github.com/dart-lang/sdk/issues/33341

Blocking issues (in the beta 3 timeframe):
- [x] Top level inference doesn't work with optional new: https://github.com/dart-lang/sdk/issues/32397
- [x] Analyzer summary type logic doesn't do downward type inference #32525
  - [x] Silent top level inference inconsistency: https://github.com/dart-lang/sdk/issues/32394
- [x] move flutter analyze off the task model: https://github.com/dart-lang/sdk/issues/32478 @devoncarew
- [x] Restrict behavior of callable classes - analyzer implementation #32156 @jmesserly

Non-blocking open issues:
- [x] Inference of generic tearoff on field: https://github.com/dart-lang/sdk/issues/32396
- [x] Redirecting constructors: https://github.com/dart-lang/sdk/issues/30855
- [x] Inconsistencies in downwards inference: https://github.com/dart-lang/sdk/issues/32305
- [x] Instantiate to bounds at ground type: https://github.com/dart-lang/sdk/issues/28580 @michaelrfarhurst
- [x] .call is not checked: https://github.com/dart-lang/sdk/issues/27098
- [x] Remove support for fuzzy arrows from the analyzer #31637
- [x] Try to make returning void within dynamic an error #32161

--

cc @devoncarew @stereotype441 @scheglov @bwilkerson

**Comment by leafpetersen** [comment]
I'm doing some preliminary triage above, feel free to adjust or move around.

**Comment by devoncarew** [comment]
This will likely be needed by mid-April.

**Comment by dgrove** [comment]
Note that blocking issues #32305 and #32156 are targeted at Dart 2-Beta 4, while this issue is targeted at Beta 3.

**Comment by leafpetersen** [comment]
I'm putting stable as the milestone for the meta-issue.

**Comment by bwilkerson** [comment]
@leafpetersen Is this list complete? Is it up to date? Is everything on it still needed for stable? What priority should it have?

**Comment by leafpetersen** [comment]
@bwilkerson @devoncarew I just did a quick triage pass on open issues looking for 2.0 type system issues and added bullets above in approximate priority order.  I'll do some more triage next week.  I wouldn't say any of these are strictly blockers, but the top few at least would be good to fix before 2.0.

**Comment by bwilkerson** [comment]
@leafpetersen This issue is out of date. I have made sure that all of the still open issues listed above have the 2.1 milestone associated with them. Given that, I'm going to close it, but feel free to re-open it if you think it's still useful.
