### ISSUE TITLE
Tracking issue for disallowing implementing inconsistent interfaces

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#32457]
In Dart 2, it is an error to implement the same generic interface multiple times with inconsistent type arguments.

For example, in Dart 1 the following code was allowed:

```dart
abstract class Box<T> {
  T get x;
}
abstract class IntBox extends Box<int> {}
abstract class DoubleBox extends Box<double> {}
class NullBox implements IntBox, DoubleBox {
  NullBox(this.x);
  final Null x;
}
```

This is no longer allowed in Dart 2, since `NullBox` implements the `Box` interface with inconsistent generic parameters (`int` and `double`).

It is still permitted to implement an interface multiple times with consistent generic parameters.

```dart
abstract class Box<T> {
  T get x;
}
abstract class IntBox extends Box<num> {
  int get x;
}
abstract class DoubleBox extends Box<num> {
  double get x;
}
class NullBox implements IntBox, DoubleBox {
  NullBox(this.x);
  final Null x;
}
```

This issues tracks the landing of this Dart 2 feature.

TODO:
  - [x] Breaking change announcement
  - [x] Land the restriction
    - Landed in 2.0.0-dev.33.0 
  - [x] Fix up internal code
  - [x] Fix up flutter code

**Comment by leafpetersen** [comment]
Closing this, the change has landed and been rolled.
