### ISSUE TITLE
Deprecate `dart:isolate` on the web

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#32684]
The plan is to provide a highly functional alternative with web workers that will provide users with similar capabilities on the web.

Concrete steps:
* [x] create a package to use web_workers
  * and make it usable today before we remove dart:isolate APIs #32438
* [x] make it a runtime error to use dart:isolate APIs in DDC #32293
* [x] make it a runtime error to use dart:isolate APIs in dart2js

**Comment by donny-dont** [comment]
@sigmundch will there be different packages for different functionalities within Dart HTML apps? I've wanted to see if I could get `http` working in a web worker but I'm really not sure what state things are in.

**Comment by sigmundch** [comment]
@donny-dont - I honestly don't know - there are still discussions going on about what such a solution should be like.

I'll let @matanlurey and @kevmoo follow up, they should know better than me :)

**Comment by matanlurey** [comment]
@donny-dont: Nothing specific at this time.

FWIW, we (AngularDart) are dropping the recommendation to use the `http` package:
https://github.com/dart-lang/site-webdev/issues/1434

**Comment by dgrove** [comment]
@vsmenon this is close - can you drive from here?

**Comment by vsmenon** [comment]
@sigmundch @kevmoo does matan's package (https://github.com/matanlurey/web_worker_channel) suffice for item 1 in the original comment?

**Comment by kevmoo** [comment]
@matanlurey should update to the latest Dart SDK. @terrylucas has fixed a number of these...

**Comment by sigmundch** [comment]
This should now be complete. We landed a change in dart2js that deletes support for dart:isolate. Together with that we did several fixes that make it possible to use the output of dart2js in a web worker.

I validated that this works locally and with @matanlurey `web_worker_channel` example.

**Comment by 4F2E4A2E** [comment]
Libs are broken now, because there is no recommended alternative. Just why!? 

Please, for the love of the web, don't let this get the same way as angular.

**Comment by kevmoo** [comment]
This was decided 2 years ago. The implementation of `dart:isolate` on the web was broken in subtle ways.

Having to support the web also limited what we could do on the VM.

We have long list of things we want to fix in the worker space: https://github.com/dart-lang/sdk/labels/library-html-worker

We'd like to start looking at them one null safety is out
