### ISSUE TITLE
Meta Issue for Optional New and Const

### ISSUE THREAD

**Issue by JekCharlsonYu** [dart-lang/sdk#32798]
This is just a meta issue to track overall progress and bugs tied to pushing optional new and const in Dart & Flutter.
- [x] [Optional new and const crash during compilation on Flutter 0.2.7-pre.6] 
 (https://github.com/dart-lang/sdk/issues/32737)
- [x] [Finish implementation of optional new and const] (https://github.com/dart-lang/sdk/issues/32729) - moved to 32737
- [x] [Dart compiler exception with Flutter master] (https://github.com/dart-lang/sdk/issues/32729) - moved to 32737
- [x] Optional new combined with generic constructor fails (https://github.com/dart-lang/sdk/issues/32802) - duplicate of 30922
- [x] [Front-end handling of optional `new` and `const`.] (https://github.com/dart-lang/sdk/issues/30922)
- [x] [Test Analyzer optional new/const on large code bases] (https://github.com/dart-lang/sdk/issues/32821)
- [x] [Test CFE optional new/const on large code bases] (https://github.com/dart-lang/sdk/issues/32820)
- [x] [Disable automatic const insertion in analyzer] (https://github.com/dart-lang/sdk/issues/32819)

**Comment by Hixie** [comment]
We should probably also track the long-term work regarding what people are calling "magic const", which is to say, automatically implying "const" instead of "new" where possible.

**Comment by Hixie** [comment]
Also, will the analyzer have a lint that recommends removing `new` and `const` where they would be implied?

**Comment by eernstg** [comment]
Drive-by comment: A lint that recommends omitting a `const` which occurs in a constant context is completely safe (presumably, nobody would have a good reason to have it there), but insisting that you omit all `new` keywords just because you can may be overly strict: During discussions in the language team about this feature it was noted several times, by several parties, that a well-placed `new` may serve to document that a particular object is fresh, and that this could improve the readability of the code.

With a possibly upcoming generalization that reintroduces "magic" const, it would again serve to insist that a given object is created at run time, which might otherwise not be expressible. E.g., when `new Object()` is used to obtain an object reference which is different from all other object references (e.g., to be used as a key in a map), it cannot be left as a plain `Object()` because that would mean `const Object()` (at least at some point in the future).

**Comment by a14n** [comment]
@Hixie do you mean something like https://github.com/dart-lang/linter/pull/936 ?

**Comment by Hixie** [comment]
@eernstg In all likelihood for Flutter at least we'd probably just create special non-const constructors for those rare cases where calling "new" instead of "const" makes sense.

@a14n Yeah that seems good.

**Comment by JekCharlsonYu** [comment]
@Hixie will create a separate issue for the long term "magic const"

For now, I'll close this as this was a meta issue to track to work that we need to get all the issues for our next flutter roll.
