### ISSUE TITLE
Support metadata on enum values

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#33082]
As of 2f781e46b01e22541cd74ab82e57e72bdea3793e, the language specification includes support for metadata on each of the values of an `enum` declaration:
```dart
enum WeekDays {
  Monday,
  Tuesday,
  @deprecated Wednesday,
  Thursday,
  Friday,
  Saturday,
  Sunday,
}
```
This issue is concerned with getting that feature implemented.

---

### Tasks

Any tool that includes the common front end would get this feature for free because `enum` declarations are expanded to regular classes by the CFE.

- [x] Common front end (#33083).
- [x] Analyzer - landed https://github.com/dart-lang/sdk/commit/74db253d3460207f86c11e08efc4e1ff174b45ee
- [x] dartfmt (dart_style issue [688](https://github.com/dart-lang/dart_style/issues/688)).

We may add further subtasks here if an implementation is needed, say, for the non-CFE analyzer.

**Comment by leafpetersen** [comment]
I think we should have an analyzer task for this (and probably dartfmt, just to be sure).

**Comment by bwilkerson** [comment]
The analyzer work is ready to commit (https://dart-review.googlesource.com/c/sdk/+/54621) when someone tells me that it's appropriate to do so.

**Comment by stefantsov** [comment]
I believe the CFE part of this is done as of https://github.com/dart-lang/sdk/commit/7dc4fbf5a27dffd974fa4a170b213df270b2112f.

**Comment by eernstg** [comment]
Closing: All subtasks have been marked done.
