### ISSUE TITLE
Meta issue for platforms specific tooling

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#33347]
This is the language meta issue tracking tooling support for platform specific compilation and analysis.

See https://github.com/dart-lang/sdk/issues/32960 for the background discussion.

Tracking issues:
  - [ ] DDK entry in libraries.json: https://github.com/dart-lang/sdk/issues/33198
  - [ ] Codegen support: https://github.com/dart-lang/build/issues/1436
  - [ ] Build support: https://github.com/dart-lang/build/issues/1430
  - [ ] Analyzer support: https://github.com/dart-lang/sdk/issues/33346

**Comment by natebosch** [comment]
Do we have an issue to specify the new format for config specific imports where only `dart.library.*` conditions are supported?

**Comment by jakemac53** [comment]
@leafpetersen can you add an action item as @natebosch mentioned for fully specifying exactly what the syntax is and exactly what identifiers are supported? Is it all libraries present in libraries.json? If so then we also need flutter to ship with a valid libraries.json file and in a consistent place with the regular dart sdk.

**Comment by natebosch** [comment]
In https://github.com/dart-lang/sdk/issues/34262#issuecomment-416920870 @lrhn indicates that the spec should not constrain it even if the tools do.

I think on another issue @matanlurey mentioned that if we're taking this approach we should consider adding a "tool spec" that indicates the subset of the language that the published SDK ships.

**Comment by matanlurey** [comment]
+1 on tool specification. If say, Fuischa, wants to ship their own compiler that supports arbitrary conditional imports, go for it - but we should be clear the tools _we_ provide (including the analyzer) do not.

**Comment by leafpetersen** [comment]
Is a "tool spec" different from documentation? 

What remains in question about the syntax?

**Comment by natebosch** [comment]
> Is a "tool spec" different from documentation?

It would be centralized.

**Comment by Levi-Lesches** [comment]
Hi -- what about dartdoc support? I recently found myself having to flip between misleading documentation and the corresponding files on github. Should I open an issue there? Judging by https://github.com/dart-lang/dartdoc/issues/1980, it didn't seem like they have any plans to implement it.
