### ISSUE TITLE
meta issue to track analyzer language2 test failures when switching the parser to fasta

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#33994]
@danrubel

**Comment by bwilkerson** [comment]
Are there failures to track here, or can we close this?

**Comment by devoncarew** [comment]
I see only one reference in the sdk, in `language_2/language_2_analyzer.status`, for the `vm/reflect_core_vm_test` test.

**Comment by danrubel** [comment]
After the switch, these issues still need to be addressed:
- [ ] `vm/reflect_core_vm_test` in `language_2/language_2_analyzer.status`
- [ ] compile­time error if a name N is re­exported https://github.com/dart-lang/sdk/issues/12916
- [ ] implement case labels https://github.com/dart-lang/sdk/issues/29352
- [ ] support generalized void https://github.com/dart-lang/sdk/issues/30177

**Comment by devoncarew** [comment]
@danrubel, I moved a few from the list above (which didn't seem necessarily language_2 related) to https://github.com/dart-lang/sdk/issues/34395.

**Comment by danrubel** [comment]
The `reflect_core_vm_test.dart` appears to parse and build an AST correctly. It generates a error stating `Evaluation of this constant expression throws an expression`.

**Comment by srawlins** [comment]
Closing as stale
