### ISSUE TITLE
[breaking change] Discontinue deprecated core library APIs, part I

### ISSUE THREAD

**Issue by natebosch** [dart-lang/sdk#34233]
The following Dart core library APIs, which are all currently deprecated, are now being fully removed.

**NOTE**: This plan is tentative and not yet fully signed off.

This issue tracks APIs to be discontinued prior to Dart 3.0. Issue https://github.com/dart-lang/sdk/issues/49529 tracks further APIs that will be discontinued in Dart 3.0.

# Phase one (pre 3.0)

The following APIs are being removed prior to 3.0, as they are no longer functional and thus their removal is expected to have minimal effect.

### `dart:convert`
- [x] [`DEFAULT_BUFFER_SIZE`][] (use `**TBD**`):

CL: https://dart-review.googlesource.com/c/sdk/+/247741

[`DEFAULT_BUFFER_SIZE`]: https://api.dart.dev/stable/2.17.6/dart-convert/JsonUtf8Encoder/DEFAULT_BUFFER_SIZE-constant.html

### `dart:mirrors`
The following are removed in Dart 2.19; they were experimental / only used internally in Dart2js (https://github.com/dart-lang/sdk/issues/32507):

- [x] [`MirrorsUsed`][] class
- [x] [`Comment`][] class

CL : https://dart-review.googlesource.com/c/sdk/+/248003

[`MirrorsUsed`]: https://api.dart.dev/stable/2.17.6/dart-mirrors/MirrorsUsed-class.html
[`Comment`]: https://api.dart.dev/stable/2.17.6/dart-mirrors/Comment-class.html

### `dart:io`

The following are removed in Dart 2.18:
- [x]  SCREAMING CASE constants from core IO: https://github.com/dart-lang/sdk/issues/34218
- [x]  Additional constants related to io's http: https://github.com/dart-lang/sdk/issues/49140

CLs: https://dart-review.googlesource.com/c/sdk/+/235701, https://dart-review.googlesource.com/c/sdk/+/246962

### `dart:developer`
The following are removed in Dart 2.19:

- [x] `kInvalidParams`, `kExtensionError`, `kExtensionErrorMax`, and `kExtensionErrorMin` in [`ServiceExtensionResponse`][] (use `invalidParams`, `extensionError`, `extensionErrorMax`, and `extensionErrorMin`)

CL: https://dart-review.googlesource.com/c/sdk/+/251767

[`ServiceExtensionResponse`]: https://api.dart.dev/stable/2.17.6/dart-developer/ServiceExtensionResponse-class.html#constants

The following will be deprecated in Dart 2.19, and then removed in Dart 3.0:

- [`MAX_USER_TAGS`][] in `UserTag`

[`MAX_USER_TAGS`]: https://api.dart.dev/stable/2.17.6/dart-developer/UserTag/MAX_USER_TAGS-constant.html

# Phase II, Dart 3.0

See list in https://github.com/dart-lang/sdk/issues/49529

**Comment by lrhn** [comment]
Most of these are intentionally left in for Dart 2 (I think `DeferredLibrary` was the only one we believed we could remove, we just didn't want to take a chance late in the process).

I would want to remove them in Dart 3.0 (or when they have been deprecate for at least some amount of time, like six months, but Dart 3.0 probably won't happen before that).

**Comment by mit-mit** [comment]
> Another thing we should consider deprecating soon and then deleting for Dart 3.0 is [dart:web_sql](https://api.dartlang.org/stable/2.0.0/dart-web_sql/dart-web_sql-library.html)

This was removed a little while back.

**Comment by jakemac53** [comment]
If possible it would be good if we could analyze `pub.dev` for usages of these apis before removing them, there is a thread on the dart-lang gitter because somebody got broken by a usage of `MirrorsUsed` in package:mustache. I filed an issue for them to drop the usage, but it would be better if we could do that prior to actually removing the APIs.
