### ISSUE TITLE
tracking issue for known issues with the analyzer switch to --use-fasta-parser

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#34395]
This collects the known failures from the switchover (without any particular prioritization):

- [ ] analyzer test failures when switching the parser to fasta #33992
- [x] ~analyzer language2 test failures when switching the parser to fasta #33994~</br>The above issue appears to be a const evaluation issue
- [x] ~analyzer co19_2 test failures when switching the parser to fasta~ #33995
  - fixed the parser related issues and many (all?) of the remaining are pre-existing issues
- [x] ~DDC test failures related to moving the analyzer to --use-fasta-parser~ #34041
  - expected to be resolved by the move to DDK
- [ ] support generalized void https://github.com/dart-lang/sdk/issues/30177

cc @danrubel @bwilkerson @kmillikin
