### ISSUE TITLE
(Set Literals) Analyzer Issue

### ISSUE THREAD

**Issue by JekCharlsonYu** [dart-lang/sdk#35120]
***** Request: 
As per implementation Plan:
Task3 : Task1 (Analyzer implementation)
The analyzer implements static checking for set literals (errors and wrarnings, constant evaluation).
****************
Tracked in this [Issue](https://github.com/dart-lang/language/issues/90)
[Implementation Plan](https://github.com/dart-lang/language/blob/63d164fa7a507b28aace20fffe31db2c3c9baa2d/accepted/future-releases/set-literals/implementation-plan.md), see ETA in this issue too.
[Full proposal](https://github.com/dart-lang/language/blob/master/accepted/future-releases/set-literals/feature-specification.md)

Tasks:
- [x] AST representation
- [x] parser integration (AstBuider)
- [x] production of errors and warnings
- [x] constant evaluation
- [x] type checking and AST rewrite of `{}` (blocked by #35300) (turns out analyzer was correct and the tests were not)
- [x] Address #35230 for set literals
- [x] Enable the shared tests for set literals
- [x] Address failing co19 tests #35615
- [x] Analyzer tests need to be updated once set literals are enabled by default #35870

**Comment by bwilkerson** [comment]
There is one bug left, which I believe is more general than the set literals feature, in which some type inference cases are not being handled correctly.

**Comment by stereotype441** [comment]
Note: the one remaining language_2 test failure should be fixed by https://dart-review.googlesource.com/c/sdk/+/88601

**Comment by stereotype441** [comment]
Analyzer work is done.

**Comment by stereotype441** [comment]
Reopening as a reminder to fix failing tests once the feature lands

**Comment by stereotype441** [comment]
Failing tests have been fixed.
