### ISSUE TITLE
Analyzer non-nullability experiments, phase 0

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#35586]
- [x] Parser support
- [ ] Make type system changes to support non-nullability #35582
- [ ] Make changes to error verifier to catch new null-related error conditions #35583
- [x] Propagate experimental flags through analysis server #35584
- [ ] Propagate parsed “?”s to the type system #35585
- [ ] Add nullability support to summaries #35596
- [ ] Explore some literature about nullability inference in other languages (e.g. Java)
- [ ] Try marking up some code manually, see what happens

**Comment by srawlins** [comment]
Err... clooooooose?
