### ISSUE TITLE
dart:ffi resolve outstanding design decisions

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#35764]
Make decisions on open design decisions:

- [ ] https://github.com/dart-lang/sdk/issues/35756 representation of C null
- [x] https://github.com/dart-lang/sdk/issues/35757 Uint64 store/load
- [ ] https://github.com/dart-lang/sdk/issues/35782 signature allocate/fromAddress
- [x] https://github.com/dart-lang/sdk/issues/35787 int8 etc truncate vs exception
- [x] https://github.com/dart-lang/sdk/issues/35840 struct representation
- [ ] https://github.com/dart-lang/sdk/issues/35841 const / indexable / castable Pointers
- [ ] https://github.com/dart-lang/sdk/issues/35844 restrict fromAddress and address
- [ ] https://github.com/dart-lang/sdk/issues/35879 void size
- [ ] https://github.com/dart-lang/sdk/issues/35881 Library extends Pointer
- [ ] https://github.com/dart-lang/sdk/issues/35883 remove Pointer.offsetBy
- [ ] https://github.com/dart-lang/sdk/issues/35903 asFunction static vs instance method
- [ ] https://github.com/dart-lang/sdk/issues/36140 support `int`, `long`, etc?

**Comment by dcharkes** [comment]
Closing this issue because we have adopted the "type-design" label for ffi design decisions.

**Comment by sensuikan1973** [comment]
> "type-design" label for ffi design decisions.

⇒ https://github.com/dart-lang/sdk/projects/13?card_filter_query=label%3Atype-design
