### ISSUE TITLE
Analyzer non-nullability work - phase 1

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#35827]
This issue is a placeholder for non-nullability work we want to do in the analyzer that doesn't necessarily belong in phase 0 (#35586).

- [ ] Add definite assignment analysis for local variables #21811
- [ ] Analyzer's printing of function types will need to change to support nullability #35818
- [ ] Verify that no failures occur if `IsEnabledByDefault.non_nullable` is set to `true`.
- [ ] Logic to produce nullability fixes should be moved into analyzer_plugin #35872

**Comment by srawlins** [comment]
I believe this can be closed.

**Comment by stereotype441** [comment]
Agreed
