### ISSUE TITLE
dart2js backend support for spreads and control flow features [meta bug]

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#36313]
Both features are supported by the same work:
* [x] migrating to use the CFE constants
  * [x] Add js semantics to CFE constants (https://github.com/dart-lang/sdk/issues/36179)
  * [x] Integrate CFE constants in the compiler (https://github.com/dart-lang/sdk/issues/36178)
* [x] implement block expressions (https://github.com/dart-lang/sdk/issues/36177)

-----
**current status**: updated April 2, 2019
* js-semantics CL reviewed and expected to land today [April 2, 2019]
* believe integration of constants is done, waiting for confirmation to close the bug.
* block expressions: done!
