### ISSUE TITLE
CFE: Implement "Control Flow Collections"

### ISSUE THREAD

**Issue by kmillikin** [dart-lang/sdk#36333]
There are three main strands of work: non-const collections, const collections, and type inference:

- [x] [Compile non-const control-flow-collections](https://github.com/dart-lang/sdk/issues/36274)
- [x] [Support UI as code constructs in const collections](https://github.com/dart-lang/sdk/issues/36278)
- [x] [Implement type inference for control-flow collections](https://github.com/dart-lang/sdk/issues/36276)

**Comment by askeksa-google** [comment]
When https://github.com/dart-lang/sdk/issues/36387 is fixed, const support is feature complete (though still missing some error checks).

**Comment by stefantsov** [comment]
I've just landed the last part of it.  Please, re-open if anything is missing.
