### ISSUE TITLE
Reduce startup latency and Sustain 60 fps for ephemeral UI apps

### ISSUE THREAD

**Issue by a-siva** [dart-lang/sdk#36428]
This issue captures all the issues being worked on for reducing startup latency and to sustain 60 fps for ephemeral UI apps

- [ ] Improve Quality of unoptimized code https://github.com/dart-lang/sdk/issues/36409
- [ ] Bridge all differences being seen in optimized JIT between the AST based version and the bytecode based version https://github.com/dart-lang/sdk/issues/36429
- [ ] Investigate more optimal method dispatch mechanism https://github.com/dart-lang/sdk/issues/36426
- [ ]  Further improvements to the kernel reader to speed up initial load times
- [ ] Move debugging functionality out from unoptimized code to the interpreter https://github.com/dart-lang/sdk/issues/36427
- [x] Separate the unoptimized and optimized background compilation queues
- [x] Investigate and implement protobuf tree shaking of apps https://github.com/dart-lang/sdk/issues/36406
- [ ] Explore possibility of AOTing framework code in a modular fashion https://github.com/dart-lang/sdk/issues/36408
- [ ] Consider having a zygote process https://github.com/dart-lang/sdk/issues/36407
- [ ] Optimize interpreter execution https://github.com/dart-lang/sdk/issues/36410
- [ ] Switch default execution mode to be bytecode based https://github.com/dart-lang/sdk/issues/36425

**Comment by a-siva** [comment]
ephemeral UI apps is not being worked on.
