### ISSUE TITLE
Meta: DDC methods to support the webdev vm service proxy 

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/sdk#36802]
Going to use this as somewhat of a grab-bag for ddc blocking issues for the vm service. Some may also be tracked elsewhere and we can either close or link them here.

Sticking this in the D24 milestone for now, but we will 

- [ ] ~~Enable `getStaticMethods` in the dart utils library - #37071~~
- [ ] ~~Enable `getStaticFields` in the dart utils library - #37071~~
- [ ] Expose whether fields/methods are const (we only get an isFinal bool right now for fields)
- [ ] Add some way of linking back from an instance to its library (fine if we have to go to the class first, and then from class to library).
- [ ] Add support for evaluating dart code provided as a String, we need enough to support the [evaluate](https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md#evaluate) and eventually we probably want [evaluateInFrame](https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md#evaluateinframe) to work as well.
  - We can technically compile separately if necessary, but it will be a lot less efficient than if we can do it directly in the running app.
- [ ] Add support for `getObject` in the vm service, there are several types of Objects:
  - Breakpoint https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md#breakpoint
  - Class https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md#class
  - Context https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md#context
  - Error https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md#error
  - Field https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md#field
  - Function https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md#function
  - Instance https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md#instance
  - Library https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md#library
  - Script https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md#script
  - TypeArguments https://github.com/dart-lang/sdk/blob/master/runtime/vm/service/service.md#typearguments

cc @Markzipan @vsmenon @nshahan @grouma @alan-knight

**Comment by natebosch** [comment]
@jakemac53 @grouma - Have we hit any other requirements for DDC here?

**Comment by grouma** [comment]
Not really. This issue is quite generic so it covers everything we have run into. From my perspective, we are mainly missing metadata around certain `getObject` return types. It would be nice to be able to properly provide complete details for `Function` and `Field` types.

**Comment by jakemac53** [comment]
We also still don't know what we want to do with regards to eval
