### ISSUE TITLE
dart2js modular FE and analysis support

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/sdk#36814]
Meta issue to track tasks related to modular support in dart2js.

This includes:
* [x] support generating dart2js kernel in kernel_worker used by bazel and build runner
* [ ] add support for running dart2js modular tests in the SDK
* [x] add support in dart2js to load multiple `.dill` files and assemble the full program in memory
* [ ] add support in dart2js to emit modular analysis data
* [ ] enable constant-update-2018, so that dart2js can use the kernel-ir by default to represent constants.
* [ ] add support to load modular analysis data files.

Not tracked here, but necessary:
* starlark and build_runner hooks to invoke the dart2js compiler modularly.

**Comment by vsmenon** [comment]
@sigmundch - anything left that you want to land in D24 (here or in the other D24 bug)?

**Comment by sigmundch** [comment]
moved to a later milestone
