### ISSUE TITLE
Dart VM Support for NNBD

### ISSUE THREAD

**Issue by aadilmaan** [dart-lang/sdk#37479]
Here is a list of items that need to get done for this:

Phase 1 will deal with supporting NNBD in weak mode (D28 milestone)
- [x] Build the VM with the forked NNBD SDK https://github.com/dart-lang/sdk/issues/38663
- [x] Migrate patch files in core libraries and dart:io to be NNBD clean https://github.com/dart-lang/sdk/issues/39754
- [x] Late Fields and variables https://github.com/dart-lang/sdk/issues/38841
- [x] Non-Null Assertions in VM https://github.com/dart-lang/sdk/issues/38840
- [x] Implementation of runtime checks for weak mode support https://github.com/dart-lang/sdk/issues/39755
- [x] Migrate dart:ffi library to NNBD https://github.com/dart-lang/sdk/issues/39144

Phase 2 will deal with supporting NNBD with strong mode checks
- [ ] Implementation of runtime checks for strong mode support https://github.com/dart-lang/sdk/issues/38845

Phase 3 will deal with NNBD performance/code size issues

Links:
[NNBD specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md)
[NNBD in Dart VM](go/nnbd-vm)
[dart-vm-nnbd-tracking](go/dart-vm-nnbd-tracking)

**Comment by mkustermann** [comment]
The CFE team has started working on non-nullable types and late fields. See the [NNBD feature specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md) for more information. Both of those features will require VM support.

* There is already a [DartType.nullability](https://github.com/dart-lang/sdk/blob/master/pkg/kernel/lib/ast.dart#L4975) in the Kernel AST (though not serialized in the binary yet).

* The CFE issue https://github.com/dart-lang/sdk/issues/37686 tracks adding the late bit.

@a-siva  The VM work could probably start soon on this, even if the CFE is not done.

**Comment by johnniwinther** [comment]
Serialization of nullability just landed (https://dart-review.googlesource.com/c/sdk/+/112085). The values are still not added to types during parsing, though, so nothing is set yet.

**Comment by mkustermann** [comment]
@a-siva okrs mention @aartbik / @liamappelbe  might be looking at the new language features, is that still the plan?

/cc @leafpetersen

**Comment by a-siva** [comment]
@kustermann to answer your question above, @crelier is going to start working on the initial phase of this (accounting for non nullable types in the VM type system representation and type checks). A second phase of this would be to use the type information to potentially eliminate runtime null checks which generating code.

**Comment by a-siva** [comment]
Closing this as we have another Epic https://github.com/dart-lang/sdk/issues/41131 tracking the samething.
