### ISSUE TITLE
[dart2js] New rti tracking issue

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/sdk#37715]
This is a general tracking issue for new rti implementation tasks.

- [ ] Pass new rti for element type to generator bodies
- [ ] Lower is-tests for simple types
- [ ] Lower as-checks for simple types
