### ISSUE TITLE
Analyzer needs to handle @optionalTypeArgs w/ static extensions

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#38105]
Take this example from [the static extension spec](https://github.com/dart-lang/language/blob/master/accepted/future-releases/static-extension-methods/feature-specification.md#syntax):

```dart
import "all.dart";  // exposes extensions `Foo`, `Bar` and `Baz`.
// ...
main() {
  // ...
  Baz("ok").baz();  // Explicit reference to `Baz` extension.
  // ...
}
```

1. [x] Can the extension, `Baz`, be marked [`@optionalTypeArgs`](https://pub.dev/documentation/meta/latest/meta/optionalTypeArgs-constant.html)? (I think so)

In the context of linter rules which take [`@optionalTypeArgs`](https://pub.dev/documentation/meta/latest/meta/optionalTypeArgs-constant.html) under consideration, and the `strict-raw-types` static analysis mode:

2. [ ] If `Baz<T>` is an extension on a class, `C<T>`, ~~then I think `Baz("ok")` is not ok; analyzer/linter should hint/lint where appropriate~~ then `Baz("ok")` is fine; inference takes place here, similar to how it does on constructors.
3. [x] The extension, `extension Baz on C`, where C is generic (e.g. `C<T>`), should be considered a raw type; analyzer/linter should hint/lint where appropriate.
4. [x] The extension, `extension on C`, where C is generic (e.g. `C<T>`), should be considered a raw type; analyzer/linter should hint/lint where appropriate.

Any of the above can be suppressed with `@optionalTypeArgs`.

CC @pq

**Comment by bwilkerson** [comment]
I think it makes sense to allow `@optionalTypeArgs` on extensions. We should also allow it on mixins, and update the comment to reflect all of these options.

Should we also allow the annotation on generic methods?

**Comment by pq** [comment]
>  I think it makes sense to allow @optionalTypeArgs on extensions. 

👍 

@srawlins: have you done a survey of what lints will be affected here?  Happy to help fix up (but . haven't taken a look yet...)

**Comment by srawlins** [comment]
> We should also allow it on mixins, and update the comment to reflect all of these options.

> Should we also allow the annotation on generic methods?

Ah, yes, and yes. We might already have the mixin support, but we'd still need to update the comment.

> have you done a survey of what lints will be affected here?

Ah, I thought it was several lint rules; it appears to be just `always_specify_types`. 🎉

**Comment by pq** [comment]
> Ah, I thought it was several lint rules; it appears to be just `always_specify_types`

Great!  Do you want to open a tracking issue on the linter?  Feel free to assign to me if you're not already planning to tackle it.

Thanks!

**Comment by srawlins** [comment]
@pq Done: https://github.com/dart-lang/linter/issues/1706

**Comment by pq** [comment]
Thanks @srawlins!

**Comment by srawlins** [comment]
Implemented.
