### ISSUE TITLE
Migrate core test packages to null safety

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#41171]
- [x] async, @jakemac53
- [x] boolean_selector, @jakemac53 
- [x] charcode
- [x] collection, @jakemac53 
- [x] matcher, @jakemac53 
- [x] meta, @jakemac53 
- [x] path, @munificent 
- [x] pedantic
- [x] pool
- [x] source_span, @jakemac53
- [x] stack_trace, @munificent
- [x] stream_channel, @natebosch 
- [x] string_scanner, @jakemac53
- [x] term_glyph, @jakemac53
- [x] test, @jakemac53
- [x] test_api, @jakemac53
- [x] test_core, @jakemac53

All packages have null-safe branches.

- [x] tests pass? No! Tests don't run on 3 of them. Teste failures on ~5 othres
- [x] published? Not yet. Watch https://github.com/dart-lang/sdk/issues/41398

Maps to (Google) internal sheet http://sheets/1eTLiYw1ylopt7loBvKDv9cSRwpNIBsHX9FjfNOAk1nY

**Comment by mit-mit** [comment]
@kevmoo what remains here?

**Comment by franklinyow** [comment]
@kevmoo Please update, and move to [#41611](https://github.com/dart-lang/sdk/issues/41611) when it's done for TP2

**Comment by jakemac53** [comment]
See page 2 of the sheet linked above which I added to track the merging into sdk/internal and publishing. All packages are now tested and merged into google3, and we should be able to begin publishing tomorrow.

**Comment by mit-mit** [comment]
@kevmoo @jakemac53 from the tracking sheet, looks like this is done now?
