### ISSUE TITLE
Discontinue `--package-root=`

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#41197]
Dart tools have historically supported two flags for specifying the location of packages:

```console
--package-root=<path> or -p<path>
--packages=<path>
```

The first option (`--package-root=`) does not support language versioning, and has very lacking test coverage (and thus likely is already broken), so we should remove it.

It should be removed from all tools that support it:

  - [x] `dart` https://github.com/dart-lang/sdk/issues/41246
  - [x] `dartanalyzer` https://github.com/dart-lang/sdk/issues/41244
  - [x] `dartaotruntime` https://github.com/dart-lang/sdk/issues/41245
  - [ ] [source code](https://github.com/search?q=org%3Adart-lang+package-root&type=Code)

**Comment by mit-mit** [comment]
cc @franklinyow can you help with a breaking change notification for this + log tracking bugs for the three issues listed in the checklist above?

**Comment by kevmoo** [comment]
Should also look at dart2js + DDC?
Would be nice to get this in w/ 2.8 – or are we cutting things too close there?

**Comment by kevmoo** [comment]
No references in DDC source that I could see.

For dart2js I did https://dart-review.googlesource.com/c/sdk/+/140980 quick (let's see if it's correct!)

**Comment by franklinyow** [comment]
I'll send breaking change and log bugs.  I don't think this has high priority enough to do it in 2.8

**Comment by mit-mit** [comment]
@franklinyow did we get a breaking change note out for this?

**Comment by kevmoo** [comment]
We updated the changelog for the dart2js part of this – https://github.com/dart-lang/sdk/commit/bdedd7a574743bac72269dfbcad39e4d770e28bc

No email to announce@ though

**Comment by franklinyow** [comment]
Announced 
https://groups.google.com/a/dartlang.org/g/announce/c/Yvx3oRVnW60/m/VDbYTXwRAQAJ

Does this require breaking change review?

**Comment by kevmoo** [comment]
> Announced
> https://groups.google.com/a/dartlang.org/g/announce/c/Yvx3oRVnW60/m/VDbYTXwRAQAJ
> 
> Does this require breaking change review?

Yup!

**Comment by franklinyow** [comment]
cc @Hixie @matanlurey @dgrove @vsmenon for review and approval.

**Comment by vsmenon** [comment]
lgtm

**Comment by scheglov** [comment]
Is this just removal of the option `--package-root=`, or complete removal of support for `packages` directories?

**Comment by mit-mit** [comment]
cc @lrhn, just `--package-root=`, right?

**Comment by lrhn** [comment]
Complete removal of support for packages directories. 

I hope that it will amount to the same thing, because without a `--package-root` flag, there is no way to specify the directory, and the currently specified algorithm for finding the package configuration does not look for `packages` directories. It should be impossible to actually use a packages directory without the flag.

I'm not sure the front-end supports package directories at all.

**Comment by franklinyow** [comment]
Ping @Hixie @matanlurey, any concern?

**Comment by Hixie** [comment]
Should be fine... cc @jonahwilliams in case the tool still uses this?

**Comment by a-siva** [comment]
Are we good on removing support for the --package-root option?

**Comment by jonahwilliams** [comment]
We do not use this in the flutter tooling, though we do have an error message that refers to it that should be cleaned up.

In flutter/engine there is a reference to --package-root in a gn template: https://github.com/flutter/engine/blob/master/build/dart/rules.gni#L95 . This is in-turn depended on https://github.com/flutter/engine/blob/034a6302208278550042b12f06e85b5dfc214808/tools/generate_package_files.py.

This reference will need to be replaced before it can be removed

**Comment by matanlurey** [comment]
@franklinyow lgtm

**Comment by jonahwilliams** [comment]
False alarm, unrelated command line flag also called package_root. LGTM

**Comment by franklinyow** [comment]
Mark Approved

**Comment by franklinyow** [comment]
Completed
