### ISSUE TITLE
Further improvements to UTF-8 decoding

### ISSUE THREAD

**Issue by askeksa-google** [dart-lang/sdk#41734]
This is a meta-issue for collecting ideas and observations regarding further improving the speed of UTF-8 decoding for the [new decoder](https://dart-review.googlesource.com/c/sdk/+/142025).

- [ ] [Intrinsify UTF-8 scanning function](https://github.com/dart-lang/sdk/issues/41702).
- [ ] [Fast path Uint8List to _OneByteString conversion](https://github.com/dart-lang/sdk/issues/41703).
- [ ] [Write UTF-8 result directly to strings](https://github.com/dart-lang/sdk/issues/41704).
- [ ] Support unboxed indices for [loads, stores](https://github.com/dart-lang/sdk/issues/39432) and [bounds checks](https://github.com/dart-lang/sdk/issues/32165).
