### ISSUE TITLE
Update highlighters to grok Null Safety changes to Dart

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#41882]
Various syntax highlighters should be updated to understand the new `late` and `required` keywords, as well as the new `Never` built-in type.

* [x] [highlight.js](https://github.com/highlightjs/highlight.js) (used by the migration tool) (PR [#2551](https://github.com/highlightjs/highlight.js/pull/2551))
* [x] [pygments](https://github.com/pygments/pygments) (PR [#1449](https://github.com/pygments/pygments/pull/1449))
* [x] [CodeMirror](https://github.com/codemirror/CodeMirror) (used by Cider, Dartpad) (PR [#6269](https://github.com/codemirror/CodeMirror/pull/6269))
* [x] [dart-lang/dart-syntax-highlight](https://github.com/dart-lang/dart-syntax-highlight/blob/master/grammars/dart.json) (child issue https://github.com/dart-lang/sdk/issues/38569) - powering github and VS Code
* [ ] Google internal devtools/search parser
* [x] [Dart Vim plugin](https://github.com/dart-lang/dart-vim-plugin) (PR [#107](https://github.com/dart-lang/dart-vim-plugin/pull/107))
* [ ] Chrome devtools?

**Comment by srawlins** [comment]
CC @MichaelRFairhurst who I think has worked on the internal parser before

**Comment by franklinyow** [comment]
Could you put a priority label on it?
Also, Michael is no longer working on this

**Comment by srawlins** [comment]
I'll just mark this as finished.
