### ISSUE TITLE
revert the change to add `unawaited` to package:meta

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#42635]
This is a general tracking issue for the work to revert the change to add `unawaited` to package:meta. We'll want to:
- [x] re-add the definition of `unawaited` to package:pedantic (https://github.com/dart-lang/pedantic/issues/62)
- [x] rev the semantic version of `package:meta` (to something greater than the current `1.2.1`) and re-publish
- [x] email [dart announce](https://groups.google.com/a/dartlang.org/g/announce)

**Comment by devoncarew** [comment]
See https://github.com/dart-lang/test/issues/1294 and others for context.

**Comment by franklinyow** [comment]
https://groups.google.com/a/dartlang.org/g/announce/c/7mWT9oXbdyM/m/fOwsr7xMBgAJ

**Comment by franklinyow** [comment]
Closing
