### ISSUE TITLE
Meta-issue for "why not promoted" functionality

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/sdk#44897]
This is a meta-issue for tracking progress towards "why not promoted" functionality for the Dart toolchain.  It comprises the following arcs of work:
- [x] core flow analysis API to provide non-promotion reasons to front ends (implemented in a42244f73b27256eca44def4daa552e91c2dbc55)
- [ ] full implementation of core algorithm (provide non-promotion reasons in all circumstances)
- [ ] explore the possibility of showing the user promotion *attempt* locations
- [ ] establish documentation links for non-promotion reasons
- [ ] make "why not promoted" information more discoverable in IntelliJ
- [ ] expose "why not promoted" information in VSCode
- [ ] expose "why not promoted" information in DartPad
- [ ] expose "why not promoted" information in Cider
- [ ] make "why not promoted" information more discoverable in command-line analyzer
- [ ] expose "why not promoted" information during internal builds
- [ ] add JSON output format to command-line analyzer
