### ISSUE TITLE
Tracking issue for Q1 2021 small features release.

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#44911]
This meta-issue tracks the Q1 2021 small features release.  Implementation plan and feature specification [here](https://github.com/dart-lang/language/tree/master/accepted/future-releases/small-features-21Q1).  This release consists of three sub-features, as described in the feature specification. 

Implementation issues
- [ ] Issue for core library implementation
- [ ] Issue for implementation in dart2js:
- [ ] Issue for implementation in the VM:
- [ ] Issue for implementation in DDC:
- [ ] Issue for implementation in CFE:
- [ ] Issue for implementation in Analyzer:
- [ ] Issue for implementation in Intellij:
- [ ] Issue for external syntax highlighting support
- [ ] Issue for internal tooling support
- [ ] Issue for implementation in Dartfmt:
- [ ] Issue for implementation in Dartdoc:
- [ ] Issue for implementation in build systems and Angular compiler:
- [ ] Issue for VM Service support:
- [ ] Issue for web debugging support:
- [ ] Issue for language tests:
- [ ] Issue for documentation:

**Comment by athomas** [comment]
@sgrekhov please add links to relevant co19 issues here.

**Comment by franklinyow** [comment]
Implementation completed
