### ISSUE TITLE
Implement the Q1 2021 small features release in the Analyzer

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#44917]
This tracks implementation work for [this feature set](https://github.com/dart-lang/sdk/issues/44911).

cc @devoncarew @srawlins @scheglov @franklinyow 

Individual feature tracking:
  - [x] Support for type arguments on annotations:  https://github.com/dart-lang/sdk/issues/44838 (@scheglov)
  - [x] Allow generic function types as type arguments and bounds: https://github.com/dart-lang/sdk/issues/44929 (@srawlins)
  - [x] Handle the unsigned shift, triple-shift, `>>>` operator: https://github.com/dart-lang/sdk/issues/44908 (@srawlins)

**Comment by leafpetersen** [comment]
@devoncarew @scheglov @stereotype441 any updates?

**Comment by devoncarew** [comment]
@srawlins for statue on the 2nd and 3rd items

**Comment by srawlins** [comment]
Generic function typedefs and triple-shift are both looking good. The implementations have landed. I need to check with language tests and co19 tests though to see if we're missing anything.

**Comment by stereotype441** [comment]
Regarding generic annotations, last month I implemented parser and AST support, but wasn't able to get to the remainder of the feature (resolution, constant evaluation, and summary support).  It's looking like between working on https://github.com/dart-lang/sdk/issues/44897 and addressing the migration bugs that have started coming in since the stable release, I'm not going to have much time available to complete work on generic annotations for the next few weeks.  @devoncarew would it be possible to hand the rest of this task off to someone on the analyzer team (@scheglov perhaps)?

**Comment by devoncarew** [comment]
Hey - @scheglov and I discussed this - he's happy to take over the remaining work. Can you sync with him to make sure we're aware of the current state and what's left to do? I'll update the owners of the features in the summary message at the top of this issue to reflect who's working on which feature.
