### ISSUE TITLE
Implement the Q1 2021 small features release in dartdoc.

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#44922]
This tracks implementation work for [this feature set](https://github.com/dart-lang/sdk/issues/44911).

cc @devoncarew @jcollins-g @franklinyow 

Individual feature tracking:

- [x] Type arguments on annotations: https://github.com/dart-lang/dartdoc/issues/2516
- [x] `>>>` as an overridable operator: https://github.com/dart-lang/dartdoc/issues/2518
- [x] Generic function types as type arguments: https://github.com/dart-lang/dartdoc/issues/2517

**Comment by leafpetersen** [comment]
@jcollins-g any updates here?

**Comment by jcollins-g** [comment]
This work is just starting.

**Comment by jcollins-g** [comment]
This is unlikely to be complete within one week; at most, code will be landed for 1 or 2 out of three by this point.

**Comment by devoncarew** [comment]
@leafpetersen - do you have a sense for in which order we should tackle these in?

**Comment by leafpetersen** [comment]
What's the existing status for each of them?  That is, does dartdoc crash, or just generate sub-optimal docs or something else? It looks like unsigned shift is documented on [int](https://api.dart.dev/dev/2.13.0-178.0.dev/dart-core/int-class.html) now, but the link doesn't work?  How about the rest?

**Comment by devoncarew** [comment]
dartdoc support is still in progress; generally:

- generic functions as type arguments does not crash but isn't yet fully functional
- generic-metadata support seems to be "fine" on first inspection and does not crash; some bits landing now will help it approach something more stable
- triple shift seems to be fine; we're less worried here

**Comment by jcollins-g** [comment]
> dartdoc support is still in progress; generally:
> 
> * generic functions as type arguments does not crash but isn't yet fully functional
> * generic-metadata support seems to be "fine" on first inspection and does not crash; some bits landing now will help it approach something more stable

This assumes we get another analyzer publish on time; currently published analyzer does crash here.

> * triple shift seems to be fine; we're less worried here

**Comment by leafpetersen** [comment]
Tentatively marking triple shift and generic metadata as done since the linked bugs have been closed, any remaining work on those two?

**Comment by jcollins-g** [comment]
Yes.  dartdoc must be published and rolled through the ecosystem (working on that today).  The analyzer must also be published.

**Comment by jcollins-g** [comment]
The urgency on this has decreased somewhat, but here are the CLs for the SDK and flutter.  The first two checkmarks can be considered "done" at the point these land.
https://dart-review.googlesource.com/c/sdk/+/194011 : CL for dartdoc in SDK
https://github.com/flutter/flutter/pull/79795 : CL for dartdoc in flutter

**Comment by leafpetersen** [comment]
Any updates?  FYI, the flag flip CLs have now landed in master (this doesn't affect the timing of this issue, just FYI).

**Comment by jcollins-g** [comment]
https://github.com/dart-lang/dartdoc/pull/2625 brings dartdoc back to where it was before the feature was punted out.  No further updates for now.

**Comment by franklinyow** [comment]
Any update?

**Comment by jcollins-g** [comment]
I'll look into this this week; remaining work is expected to be small.

**Comment by franklinyow** [comment]
@leafpetersen Looks like the last pieces is done.  Ready to close this?

**Comment by jcollins-g** [comment]
@franklinyow The change just landed inside Dartdoc; I would prefer it to propagate to the Dart SDK and Flutter before closing this issue.  That will likely happen Monday.

**Comment by jcollins-g** [comment]
Going to close this as it looks likely that Flutter will finish landing shortly.  Small features is done for dartdoc.
