### ISSUE TITLE
Tracking issue for non-function type aliases

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#44951]
This issue is for tracking implementation of the [non-function type aliases](https://github.com/dart-lang/language/blob/master/accepted/2.13/nonfunction-type-aliases/feature-specification.md) feature.

The implementation plan for this issue is [here](https://github.com/dart-lang/language/blob/master/accepted/2.13/nonfunction-type-aliases/implementation-plan.md).

## TODO:

- [x] [Issue](https://github.com/dart-lang/sdk/issues/44952) for implementation in dart2js.
- [x] [Issue](https://github.com/dart-lang/sdk/issues/44953) for implementation in DDC.
- [x] [Issue](https://github.com/dart-lang/sdk/issues/44954) for implementation in the VM.
- [x] [Issue](https://github.com/dart-lang/sdk/issues/42430) for implementation in CFE.
- [x] [Issue](https://github.com/dart-lang/sdk/issues/44078) for implementation in Analyzer.
- [x] [Issue](https://github.com/dart-lang/sdk/issues/44955) for implementation in IntelliJ.
- [x] [Issue](https://github.com/dart-lang/sdk/issues/44956) for implementation in syntax highlighters
  - [Github syntax highlighting](https://github.com/dart-lang/dart-syntax-highlight/).
  - Github grammar for use with VS Code.
  - [highlight.js support](https://github.com/highlightjs/highlight.js) (api.dart.dev, api.pub.dev, Dartdoc):
  - [CodeMirror support](https://github.com/codemirror/CodeMirror/) (DartPad).
- [x] [Issue](https://github.com/dart-lang/linter/issues/2509) for support in linter.
- [x] [Issue](https://github.com/dart-lang/sdk/issues/44957) for implementation in Kythe.
- [x] [Issue](https://github.com/dart-lang/sdk/issues/44958) for implementation in Cider.
- [x] [Issue](https://github.com/dart-lang/sdk/issues/44959) for implementation in Dartfmt.
- [x] [Issue](https://github.com/dart-lang/sdk/issues/44960) for implementation in Dartdoc.
- [x] [Issue](https://github.com/dart-lang/sdk/issues/44961) for implementation in build systems and Angular compiler.
- [x] [Issue](https://github.com/dart-lang/sdk/issues/44962) for VM Service support.
- [x] [Issue](https://github.com/dart-lang/sdk/issues/44963) for web debugging support.
- [x] [Issue](https://github.com/dart-lang/sdk/issues/44964) for language tests written.
- [x] [Issue](https://github.com/dart-lang/sdk/issues/44965) for documentation.
- [x] [Issue](https://github.com/dart-lang/sdk/issues/44966) for tests validated as passing.
- [x] [Issue](https://github.com/dart-lang/sdk/issues/44967) for core library updates.

**Comment by leafpetersen** [comment]
cc @franklinyow @mit-mit @vsmenon @pcsosinski

**Comment by iapicca** [comment]
> This issue is for tracking implementation of the [non-function type aliases](https://github.com/dart-lang/language/blob/master/accepted/future-releases/generalized-typedef-2018/feature-specification.md) feature.

this link seems dead

**Comment by eernstg** [comment]
Links fixed.

**Comment by leafpetersen** [comment]
Landed in master, should go to beta shortly.
