### ISSUE TITLE
Add quick fixes for more lints

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/sdk#45932]
The following is a partial list of lints that could have fixes but don't. Each code is linked to an issue describing the fixes that have been proposed.

- [x] [avoid_function_literals_in_foreach_calls](https://github.com/dart-lang/sdk/issues/45918)
- [x] [avoid_null_checks_in_equality_operators](https://github.com/dart-lang/sdk/issues/45919)
- [x] [avoid_returning_null_for_void](https://github.com/dart-lang/sdk/issues/45920)
- [x] [avoid_print](https://github.com/dart-lang/sdk/issues/45921)
- [x] [avoid_unnecessary_containers](https://github.com/dart-lang/sdk/issues/45922)
- [x] [exhaustive_cases](https://github.com/dart-lang/sdk/issues/45923)
- [x] [prefer_const_literals_to_create_immutables](https://github.com/dart-lang/sdk/issues/45924)
- [x] [prefer_initializing_formals](https://github.com/dart-lang/sdk/issues/45925)
- [x] [prefer_typing_uninitialized_variables](https://github.com/dart-lang/sdk/issues/45926)
- [x] [prefer_void_to_null](https://github.com/dart-lang/sdk/issues/45927)
- [x] [sized_box_for_whitespace](https://github.com/dart-lang/sdk/issues/45928)
- [x] [unnecessary_getters_setters](https://github.com/dart-lang/sdk/issues/45929)
- [x] [unnecessary_string_escapes](https://github.com/dart-lang/sdk/issues/45930)
- [x] [use_key_in_widget_constructors](https://github.com/dart-lang/sdk/issues/45931)
