### ISSUE TITLE
Tracking issue for constructor tearoffs

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#46228]
This issue tracks the implementation of the [constructor tearoffs](https://github.com/dart-lang/language/blob/master/accepted/future-releases/constructor-tearoffs/feature-specification.md) [feature](https://github.com/dart-lang/language/issues/216).

## Prerequisite Tasks
- [x] [Issue](https://github.com/dart-lang/language/issues/1663) for acceptance of [constructor tearoffs feature specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/constructor-tearoffs/feature-specification.md).

## Implementation Tasks

- [x] [Issue](https://github.com/dart-lang/sdk/issues/46242) for language tests written.
- [x] [Issue](https://github.com/dart-lang/sdk/issues/46245) for core library updates.
- [x] [Issue](https://github.com/dart-lang/sdk/issues/46232) for implementation in CFE.
- [x] [Issue](https://github.com/dart-lang/sdk/issues/46230) for implementation in DDC.
- [x] [Issue](https://github.com/dart-lang/sdk/issues/46231) for implementation in the VM.
- [x] [Issue](https://github.com/dart-lang/dart_style/issues/1028) for implementation in Dartfmt.
- [x] [Issue](https://github.com/dart-lang/sdk/issues/46239) for implementation in build systems and Angular compiler.
- [x] [Issue](https://github.com/dart-lang/sdk/issues/46240) for VM Service support.
- [x] [Issue](https://github.com/dart-lang/dartdoc/issues/2655) for implementation in Dartdoc.
- [x] [Issue](https://github.com/dart-lang/sdk/issues/46235) for implementation in syntax highlighters
  - [Github syntax highlighting](https://github.com/dart-lang/dart-syntax-highlight/).
  - [highlight.js support](https://github.com/highlightjs/highlight.js) (api.dart.dev, api.pub.dev, Dartdoc):
  - [CodeMirror support](https://github.com/codemirror/CodeMirror/) (DartPad).
- [x] [Issue](https://github.com/dart-lang/linter/issues/2693) for support in linter.
- [x] [Issue](https://github.com/dart-lang/sdk/issues/46234) for implementation in IntelliJ.
- [x] [Issue](https://github.com/dart-lang/sdk/issues/46237) for implementation in Cider.
- [x] [Issue](https://github.com/dart-lang/sdk/issues/46244) for tests validated as passing (this is managed via the constructor-tearoffs spreadsheet).
- [x] [Issue](https://github.com/dart-lang/sdk/issues/46241) for web debugging support.
- [x] [Issue](https://github.com/dart-lang/sdk/issues/46229) for implementation in dart2js.
- [x] [Issue](https://github.com/dart-lang/sdk/issues/46236) for implementation in Kythe.
- [x] [Issue](https://github.com/dart-lang/sdk/issues/46020) for implementation in Analyzer.
- [ ] [Issue](https://github.com/dart-lang/sdk/issues/46243) for documentation.

**Comment by jcollins-g** [comment]
Added dart-lang/language#1663 and a reference here since many teams/individuals are using these bugs as a signal for when to start implementing as well as tracking issues once implementation begins -- feel free to move that around/correct wording if need be.

**Comment by lrhn** [comment]
The proposal is accepted and available as a [feature specification](https://github.com/dart-lang/language/tree/master/accepted/future-releases/constructor-tearoffs) in the "accepted/" directory.

The experiment flag is called "constructor-tearoffs" even if there are other related features included.

**Comment by devoncarew** [comment]
Note that the github project we're using to track this work is here: https://github.com/orgs/dart-lang/projects/27.

**Comment by devoncarew** [comment]
An update - all work here (modulo documentation) is complete.
