### ISSUE TITLE
☂ [tracking] linter 1.8.0 roll blockers

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#46663]
Issues blocking a linter 1.8.0 roll.

See: https://dart-review.googlesource.com/c/sdk/+/207401

- [x]  `avoid_classes_with_only_static_members` diagnostics in flutter: https://github.com/dart-lang/linter/issues/2784
- [x]  new `curly_braces_in_flow_control_structures` lints in Google3
- [x]  `linter:tests_experiments_test` [failures](https://fusion2.corp.google.com/invocations/0e8d03dc-b880-40a3-99a5-db3f1802c56b/targets/%2F%2Fthird_party%2Fdart%2Flinter:tests_experiments_test/tests) due new `package:meta` resolution issues in experiment tests (hotfix identified by @michalt 👍 )

**Comment by pq** [comment]
@michalt: curious if you have insight into the `linter:tests_experiments_test` failures?

**Comment by michalt** [comment]
@pq Looking at the test log, I see an error with the import of `package:meta`:
```
linter/test_data/rules/experiments/nonfunction-type-aliases/rules/always_specify_types.dart 7:8 [compile time error] Target of URI doesn't exist: 'package:meta/meta.dart'.
import 'package:meta/meta.dart';
       ^^^^^^^^^^^^^^^^^^^^^^^^
```
I'm familiar with the test and how it's invoking the analyzer; but I don't see any BUILD dependency on `package:meta`, so perhaps the analyzer doesn't have access to `package:meta`, fails analysis due to that, and consequently the linter doesn't produce the right output?

If this is urgent/blocking, it's possible to update the BUILD file to exclude the test internally (we already do that for a few tests; feel free to ping me if you're unsure how to do that).

**Comment by pq** [comment]
Thanks!  I'll dig in a bit.  Unfortunately the linter tests (at least as run externally) don't fail on compilation errors in test data[1] so this may be a red herring.  (I notice that other tests have similar dependencies and are possibly not running as expected... 🤔 )

I'll ping you Monday if I don't get anywhere (or probably regardless 😉 ).

[1] This is kinda-sorta by design but has come up for reconsideration recently.  See: https://github.com/dart-lang/linter/issues/2760

**Comment by pq** [comment]
Looking at that test failure, here are some of the spots getting linted that shouldn't be:

```dart
@optionalTypeArgs
class P<T> { }


{
  ...
  P p = new P(); //OK (optionalTypeArgs)
}

P doSomething(P p) //OK (optionalTypeArgs)
{
  return p;
}

```

I'm guessing this is indeed failing due to lack of resolution for `package:meta`.  Interestingly we're actually "mocking" meta

https://github.com/dart-lang/linter/blob/1e1300a9dcfaa3e4df1fe26fd00c3c5e44e81b77/lib/src/test_utilities/test_resource_provider.dart#L24-L25

https://github.com/dart-lang/linter/blob/master/test_data/rules/.mock_packages
https://github.com/dart-lang/linter/tree/master/test_data/mock_packages

@michalt: can you think of any reason this wouldn't work internally?

**Comment by michalt** [comment]
@pq I poked around a bit and it seems that the test tries to access `<bazel paths>/test_data/rules/experiments/nonfunction-type-aliases/rules/.mock_packages`, but `.mock_packages` is in `test/rules/.mock_packages` AFAICS. So I'm a bit confused how this works: looking at [1], it seems to me that we're just taking the directory of the test and assume that `.mock_packages` is in the same directory, but that doesn't seem to be the case for `experiments_test.dart` [2]. Perhaps I'm missing something?

[1] https://github.com/dart-lang/linter/blob/4c4312400c21c523c9036edbb8e8937582cb917d/lib/src/test_utilities/test_resource_provider.dart#L24

[2] https://github.com/dart-lang/linter/blob/c743f88197a14f5236a28fc63af8e1ea68c256a2/test/experiments_test.dart#L32

**Comment by pq** [comment]
Thanks for taking a look @michalt!

This is definitely confusing and we should probably re-think package resolution for tests. 

>  I poked around a bit and it seems that the test tries to access <bazel paths>/test_data/rules/experiments/nonfunction-type-aliases/rules/.mock_packages, but .mock_packages is in test/rules/.mock_packages AFAICS.

There's also one in `nonfunction-type-aliases/rules/`

https://github.com/dart-lang/linter/blob/master/test_data/rules/experiments/nonfunction-type-aliases/rules/.mock_packages

which is why I'd expect it _should work_.

(But also why this is **confusing**!)

**Comment by pq** [comment]
This is close to unblocked.  The last 🤞 change to close out the new diagnostics is out for review and then I'll land.

When this roll gets pulled in a hotfix (cheers @michalt) will need to be applied to get the experiment tests working.

Cheers all for the help!

**Comment by pq** [comment]
Some new flutter engine failures:


https://logs.chromium.org/logs/dart/buildbucket/cr-buildbucket.appspot.com/8840538605305830000/+/u/analyze_flutter_engine/stdout

```
Analyzing web_ui...

   info - lib/src/engine/html/path/path_utils.dart:29:1 - Avoid defining a class that contains only static members. - avoid_classes_with_only_static_members
   info - lib/src/engine/html/shaders/vertex_shaders.dart:73:1 - Avoid defining a class that contains only static members. - avoid_classes_with_only_static_members
   info - lib/src/engine/text/word_breaker.dart:17:1 - Avoid defining a class that contains only static members. - avoid_classes_with_only_static_members
   info - lib/src/ui/hash_codes.dart:16:1 - Avoid defining a class that contains only static members. - avoid_classes_with_only_static_members
```

(FYI @goderbauer.)

**Comment by goderbauer** [comment]
I think these can all be fixed by adding a private constructor to mark them as non-instantiable. (cc @yjbanov since this is all in web_ui).

**Comment by pq** [comment]
FWIW @iinozemtsev, @michalt: blockers addressed and this is landed.  The only thing (🤞) on your end should be to land the experiments patch.

**Comment by pq** [comment]
(Landed.)
