### ISSUE TITLE
Implement enhanced support for constant factory constructors

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#46984]
Cf. the specification change in https://github.com/dart-lang/language/pull/1764, based on the discussions in https://github.com/dart-lang/language/issues/1763 and https://github.com/dart-lang/sdk/issues/46758:

It is no longer an error to have a constant factory constructor (which is then necessarily redirecting<sup>1</sup>) in a class that has an instance variable which is `late` and `final`. Note that the [constraints](https://github.com/dart-lang/language/blob/fbb89fca0a0691163f35871ec9f914d878e15342/specification/dartLangSpec.tex#L4204) on classes derived from the existence of a constant constructor only apply in the case where that constructor is non-redirecting and generative, and hence the `late final` instance variable is just one of the members that a class can have, in the case where every constant constructor in the class is a factory (so we're never going to have a "constant object" which is an instance of that class, we're just using its interface).

This issue is concerned with the implementation of this feature. This change should be applied regardless of language version, since it brings the analyzer in line with pre-existing CFE behavior.

Subtasks:

- [x] [Analyzer issue](https://github.com/dart-lang/sdk/issues/46985).
- [x] [CFE issue](https://github.com/dart-lang/sdk/issues/46986).
- [x] [VM issue](https://github.com/dart-lang/sdk/issues/46989).
- [x] [dart2js issue](https://github.com/dart-lang/sdk/issues/46987).
- [x] [DDC issue](https://github.com/dart-lang/sdk/issues/46988).
- [x] [Test CL](https://dart-review.googlesource.com/c/sdk/+/211140).
- [x] [Specification PR](https://github.com/dart-lang/language/pull/1764).

Footnote 1: The system classes contain some external constant factory constructors. This is not a language feature, and hence we will ignore them here.

Edits:
- Aug 26: The change is no longer part of the constructor-tearoffs feature; adjusted the text above accordingly.
