### ISSUE TITLE
Implement named arguments anywhere feature

### ISSUE THREAD

**Issue by chloestefantsova** [dart-lang/sdk#47451]
This issue is for implementing https://github.com/dart-lang/language/issues/1072 and referencing it in the related CLs.

The language flag here is `named-arguments-anywhere`, and the github project for this feature is https://github.com/orgs/dart-lang/projects/33.

## Spec and test tasks
- [x] https://github.com/dart-lang/language/issues/1948
- [x] https://github.com/dart-lang/sdk/issues/47576
- [x] co19 tests https://github.com/dart-lang/co19/issues/1228

## Implementation tasks
- [x] CFE implementation: fcd684e
- [x] Analyzer implementation: https://github.com/dart-lang/sdk/commit/82dc2cf2557de18500b8a1500350dbdb9a5e116d
- [x] syntax highlighters implementation (https://github.com/dart-lang/dart-syntax-highlight/, https://github.com/highlightjs/highlight.js, https://github.com/codemirror/CodeMirror/); assumed no-op
- [x] DDC implementation (assumed no-op)
- [x] dart2js implementation (assumed no-op)
- [x] VM implementation (assumed no-op)
- [x] build systems implementation (assumed no-op)
- [x] web debugging support (assumed no-op)
- [x] https://github.com/dart-lang/sdk/issues/47577
- [x] https://github.com/dart-lang/sdk/issues/47816
- [x] https://github.com/dart-lang/dartdoc/issues/2850
- [x] https://github.com/dart-lang/sdk/issues/47578
- [x] https://github.com/dart-lang/dart_style/issues/1072
- [x] https://github.com/dart-lang/sdk/issues/47580
- [ ] https://github.com/dart-lang/sdk/issues/47579
- [x] https://github.com/dart-lang/linter/issues/3050
- [x] https://github.com/dart-lang/sdk/issues/47591
- [x] https://github.com/dart-lang/sdk/issues/47592
- [x] https://github.com/dart-lang/site-www/issues/3653
- [ ] tests validated as passing (tracking via a google sheet)

**Comment by eernstg** [comment]
Perhaps `--enable-experiment=named-arguments-anywhere`?

**Comment by devoncarew** [comment]
I'm going to start creating sub-issues here to scope of the work.

**Comment by devoncarew** [comment]
@sigmundch - I assume the DDC and dart2js implementations are no-ops here. Can you confirm that (or ask someone else to)? Thanks!

**Comment by devoncarew** [comment]
@a-siva / @mkustermann - can you confirm that the VM implementation for this is a no-op? Otherwise we'll create a tracking bug for the VM work.

**Comment by a-siva** [comment]
> @a-siva / @mkustermann - can you confirm that the VM implementation for this is a no-op? Otherwise we'll create a tracking bug for the VM work.

Is the spec for this feature complete? Also I noted there were some tests in
https://dart-review.googlesource.com/c/sdk/+/217013
but I presume we are going to get more co19 tests for this?
Once we have these it should be possible to confirm that no work would be needed in the VM.

**Comment by sigmundch** [comment]
Agree, I believe nothing is needed for DDC and dart2js directly. /cc @nshahan @fishythefish 

The only open question is whether there is work needed for the web debugger integration, which may entail some work in DDC. At a glance, I would be surprised if we needed anything special for that either, but it's good to double check. /cc @nshahan @annagrin

**Comment by mkustermann** [comment]
@a-siva / @mkustermann - can you confirm that the VM implementation for this is a no-op? Otherwise we'll create a tracking bug for the VM work.

It seems this is purely a use-site only feature, so one wouldn't need to worry about observing mixed positional and named parameters on declaration site with `dart:mirror`s.

If the CFE desugars use-sites to existing Kernel AST constructs with the correct evaluation order, then there is indeed no work for the VM team here. (@chloestefantsova guess this is true?)

**Comment by devoncarew** [comment]
@jakemac53 - do we expect any implementation work for this wrt build systems? If so we'll file an issue to track.

**Comment by jakemac53** [comment]
Nothing major that jumps to mind other than general language versioning support which we already have in place.

Internally language versioning is weird (we don't expose actual versions to users), so some amount of work will have to happen to allow users to enable this (similar to how null safety is enabled internally).

**Comment by annagrin** [comment]
> The only open question is whether there is work needed for the web debugger integration, which may entail some work in DDC. At a glance, I would be surprised if we needed anything special for that either, but it's good to double check. 

We would need to at least add tests for newly allowed expressions to evaluate correctly. The debugging support depends on whether there are any changes in the vm service API (@bkonyi) or significant changes to support the compilation in DDC (@nshahan) but most likely nothing needed to be done for the debugger.

**Comment by devoncarew** [comment]
@bkonyi - can you speak to Anna's question above wrt any service protocol changes to support this feature?

**Comment by bkonyi** [comment]
Sorry for the delay. No, I don't think there's anything special we'd need to change from the service's perspective.

**Comment by devoncarew** [comment]
Thanks!

**Comment by devoncarew** [comment]
I'll keep a task for the vm service protocol to cover Anna's comment above - 'we would need to at least add tests for newly allowed expressions to evaluate correctly'. It sounds like no protocol / api changes however, so nothing that would leak through to other clients.

@nshahan - for Anna's other question - `The debugging support depends ... or significant changes to support the compilation in DDC`; I'm guessing that there would be no such?

**Comment by nshahan** [comment]
@devoncarew My assumption was that there would be little to no implementation on the DDC side. I will take a look at the feature tests that are failing to get an idea of what will be required. I'll report back if I find any significant issues.

**Comment by nshahan** [comment]
It looks like the failing tests in DDC are all related to redirecting constructors that apply named arguments anywhere in the redirection. We are not correctly creating the temporary variables created by the CFE lowering. I'll investigate a fix but it doesn't look like it will be very big.

**Comment by rakudrama** [comment]
dart2js has an existing bug (#47047) which is tickled by the new tests. I'll fix it (WIP https://dart-review.googlesource.com/c/sdk/+/223381)

**Comment by munificent** [comment]
I have this implemented in dart_style now, but not yet released and rolled into the Dart SDK. I'll roll it in once I get enhanced enums done too.

**Comment by chloestefantsova** [comment]
@devoncarew Can this issue be closed now, given the unchecked boxes in the top posting?

**Comment by devoncarew** [comment]
Yes, I think we can close (and track any remaining work in separate issues).

@leafpetersen @mit-mit - I lost track of this issue when I switched away from TPM style work. Not sure what the new project management process for language features looks like going forward.
