### ISSUE TITLE
Implement enhanced enums

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#47849]
This issue is for implementing [dart-lang/language#1072](https://github.com/dart-lang/language/issues/158) and referencing it in the related CLs.

The language flag is `enhanced-enums`, the spec is [enhanced-enums/feature-specification.md](https://github.com/dart-lang/language/blob/master/accepted/future-releases/enhanced-enums/feature-specification.md) and the github project is https://github.com/orgs/dart-lang/projects/36.

## Spec and test tasks
- [x] write the spec for enhanced enums ([enhanced-enums/feature-specification.md](https://github.com/dart-lang/language/blob/master/accepted/future-releases/enhanced-enums/feature-specification.md))
- [x] #48088
- [x] https://github.com/dart-lang/co19/issues/1258

## Implementation tasks

- [x] https://github.com/dart-lang/sdk/issues/47453
- [x] https://github.com/dart-lang/sdk/issues/47857
- [x] https://github.com/dart-lang/sdk/issues/47858
- [x] https://github.com/dart-lang/sdk/issues/47859
- [x] https://github.com/dart-lang/sdk/issues/47860
- [x] https://github.com/dart-lang/sdk/issues/47861
- [x] https://github.com/dart-lang/sdk/issues/47862
- [x] https://github.com/dart-lang/sdk/issues/47863
- [x] https://github.com/dart-lang/sdk/issues/47864
- [x] https://github.com/dart-lang/sdk/issues/47865
- [x] https://github.com/dart-lang/dart_style/issues/1075
- [x] https://github.com/dart-lang/dartdoc/issues/2859
- [ ] https://github.com/dart-lang/sdk/issues/47866
- [x] https://github.com/dart-lang/sdk/issues/47867
- [x] https://github.com/dart-lang/linter/issues/3090
- [x] https://github.com/dart-lang/sdk/issues/47868
- [x] https://github.com/dart-lang/sdk/issues/47869
- [x] https://github.com/dart-lang/site-www/issues/3699
- [x] https://github.com/dart-lang/sdk/issues/47870
- [ ] tests validated as passing (tracking via a google sheet)
