### ISSUE TITLE
[vm/ffi] Debugger `Pointer` inspect value.

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/sdk#48882]
When using the Dart debugger on `Pointer<X extends Struct/Union>` it would be useful if the `.ref` was available as a getter to inspect the memory that the `Pointer` points to.

We could do the same with pointers to integers for the first value.

cc @timsneath thanks for the suggestion.

However, for invalid pointers this would lead to a segfault. We could prevent the segfault for `nullptr` by recognizing address 0, but for pointers created by users we can't.

**Comment by Piero512** [comment]
About the segfault, couldn't you allow in debug mode to intercept the segfault and throw some kind of virtual exception, just like a native (C code) debugger would do? I would love to see it working on devtools, too.

**Comment by DynamicProdBreaker** [comment]
The documentation states that for a pointer ptr declared in Dart source code

> Currently, ptr only shows its memory address in the debugger.

However even this doesn't appear to be true, since when I hover over ptr in the devtools debugger the only thing I get back is the text "Pointer", meaning it doesn't even print the memory address, only its type. To check whether my devtools was buggy I also declared an integer and set it to a random value, and the debugger correctly prints out the integer value of that variable, so I doubt it's anything to do with an issue on my end. It appears pointers in general for the debugger could use a little love.

**Comment by dcharkes** [comment]
> Currently, ptr only shows its memory address in the debugger.

That might have been true at the time of writing. (But we landed some VM-internal representation in the meantime which might have broken that.)

They are getting a bit more love as we speak ❤️ 

* https://dart-review.googlesource.com/c/sdk/+/486460
* https://github.com/dart-lang/sdk/blob/main/docs/gsoc/Dart-GSoC-2026-Project-Ideas.md#idea-inspect-native-memory-in-dart-devtools

**Comment by DynamicProdBreaker** [comment]
> > Currently, ptr only shows its memory address in the debugger.
> 
> That might have been true at the time of writing. (But we landed some VM-internal representation in the meantime which might have broken that.)
> 
> They are getting a bit more love as we speak ❤️
> 
> * https://dart-review.googlesource.com/c/sdk/+/486460
> * https://github.com/dart-lang/sdk/blob/main/docs/gsoc/Dart-GSoC-2026-Project-Ideas.md#idea-inspect-native-memory-in-dart-devtools

Hi! I had found this issue through GSoC and so thought to mention this here. Funnily enough the GSoC native memory inspection project is actually the very thing that makes that claim that ptr shows the memory address in the debugger. I was initially going to ask about certain things pertaining to the GSoC project here (Given I can't reply to anything on dart\-gsoc for some reason, everything I send just gets deleted instantly, I can only make new threads on that group and nothing else. I actually tried to reply to you on dart\-gsoc when you helpfully answered my questions but the message just got dropped) but decided against it since this is not the best place for that.

**Comment by TheNourhan** [comment]
**Supported:**
1. [x] `Pointer<Struct>` (no nesting)
2. [ ] `Pointer<Struct>` (nested struct) [CL#537380 in progress](https://dart-review.googlesource.com/c/sdk/+/537380)
3. [x] Struct
4. [x] `Pointer<Int8>`
5. [x] TypedData-backed struct
6. [ ] `Pointer<Union>` (no nesting) [CL#537380 in progress](https://dart-review.googlesource.com/c/sdk/+/537380)
7. [ ] `Pointer<Union>` (nested union) [CL#537380 in progress](https://dart-review.googlesource.com/c/sdk/+/537380)
8. [ ] Union [CL#537380 in progress](https://dart-review.googlesource.com/c/sdk/+/537380)
9. [x] `Array<Uint8>`
10. [x]  `Array<Array<Uint8>>`
11. [ ] `Array<MyStruct>` [CL#537380 in progress](https://dart-review.googlesource.com/c/sdk/+/537380)
