### ISSUE TITLE
Tracking: External ecosystem preparedness

### ISSUE THREAD

**Issue by nuritzi** [dart-lang/sdk#49846]
**Goal**: We'd like to track progress on the % of flutter run sessions that are fully sound. This will help us track progress towards our next Dart major version. 

**Frequency**: we'd like to pull these stats on a weekly basis.

### How to

Here's the [analytics query](https://analytics.google.com/analytics/web/#/report/app-content-event-events/a67589403w118070018p123509034/_u.date00=20210111&_u.date01=20220809&_r.drilldown=analytics.eventCategory:null-safety,analytics.eventAction:runtime-mode&explorer-table.plotKeys=%5B%5B%22NullSafetyMode.unsound%22%5D,%5B%22NullSafetyMode.sound%22%5D%5D&explorer-graphOptions.selected=analytics.nthWeek/); must manually adjust end-date of query

## Todos
 * [ ] **Measure:** % of flutter run sessions that are fully sound
 * [ ] **Document** how you pulled this information (can be in a doc or in this issue). 
 * [ ] **Automate** a weekly report if possible.

**Comment by nuritzi** [comment]
@devoncarew would you be able to help with this issue, or is there someone else on the ecosystem who can?

**Comment by devoncarew** [comment]
Given that we're already tracking the data and have a query to measure what we want, I see two reasonable solutions here:

1) manually check in on the % of flutter run sessions every week; populate that info in a spreadsheet for historical data
1) use a PLX dashboard to query the analytics data and populate an automated dashboard


I suspect that 1. is something that TPgM would drive. For 2., @jayoung-lee (on the UXR team) has lots of PLX experience and could help set this up. Given the shorter timeframe we care about this data, I think 1. would be sufficient for what we need - a little more manual work per week but we'd just need to do it for a quarter or two.

**Comment by jayoung-lee** [comment]
I think you can use Google Sheet add-on for Google Analytics for 1. to minimize manual work. See https://developers.google.com/analytics/solutions/google-analytics-spreadsheet-add-on

Happy to help with 2. as well!

**Comment by khyati82** [comment]
Thanks Jayoung for the link. I have created this sheet that generates Google analytics report reflecting data from last 90 days.
The report is scheduled to run daily. 

On the third tab, I have also added a visualization chart that should get updated automatically as well.

https://docs.google.com/spreadsheets/d/1IBrwsMk_mkZVP4_GaCJ9hwjxV09U8OgVo955-EekaHM/edit#gid=0

**Comment by khyati82** [comment]
Created the dashboard as well
https://dashboards.corp.google.com/_7c0b9e33_0972_4f1e_ac1c_49b1b1be337e
Who/When are we looking at these progress metrics?

**Comment by nuritzi** [comment]
@mit-mit can you please take a look at what Khyati has so far?
