### ISSUE TITLE
Tracking: Internal ecosystem preparedness

### ISSUE THREAD

**Issue by nuritzi** [dart-lang/sdk#49849]
**Goal**: We'd like to track progress on % of google3 code migrated. This will help us track progress towards our next Dart major version. 

**Frequency**: we'd like to pull these stats on a weekly basis.

## Todos
 * [ ] **Measure:** % of google3 code migrated. 
 * [ ] **Document** how you pulled this information (can be in a doc or in this issue). 
 * [ ] **Automate** a weekly report if possible.

**Comment by nuritzi** [comment]
I think the stats in [go/dart-null-safety-stats](https://goto.google.com/dart-null-safety-stats) should have what's needed for this.
