### ISSUE TITLE
Tracking: Dart team package support

### ISSUE THREAD

**Issue by nuritzi** [dart-lang/sdk#49847]
**Goal**: We'd like to track progress on % of packages under dart-lang github org which are soundly null safe (meaning a) lower SDK >= 2.12, and b) no @dart=x markers where x <2.12)

This will help us track progress towards our next Dart major version. 

**Frequency**: we'd like to pull these stats on a weekly basis.

## Todos
 * [ ] **Measure:** % of packages under dart-lang github org which are soundly null safe
 * [ ] **Document** how you pulled this information (can be in a doc or in this issue)
 * [ ] **Automate** a weekly report if possible

**Comment by nuritzi** [comment]
@devoncarew is this something that the ecosystem team can help with?

**Comment by devoncarew** [comment]
The info on the repos w/ some migration work remaining is at https://github.com/dart-lang/sdk/issues/49169. It may be sufficient to manually poll that issue in order to determine the weekly doneness %?

If more automation is desired, I have a local tool which will scan all the dart-lang/ repos and determine which are unmigrated, or, migrated but have a few files excluded. I could help productionize that tool a bit more so that other people could run it / it was slightly more general if that were helpful (however, I don't think we would take on the automation / weekly report aspect of this issue).
