### ISSUE TITLE
Tracking: Dart SDK Support

### ISSUE THREAD

**Issue by nuritzi** [dart-lang/sdk#49848]
**Goal**: We'd like to track progress on the number of lines of code in the dart-lang/sdk repo that isn't soundly null safe (@dart=x markers where x <2.12). This will help us track progress towards our next Dart major version. 

**Frequency**: we'd like to pull these stats on a weekly basis.

## Todos
 * [ ] **Measure:** Number of lines of code in the dart-lang/sdk repo that isn't soundly null safe (@dart=x markers where x <2.12)
 * [ ] **Document** how you pulled this information (can be in a doc or in this issue). 
 * [ ] **Automate** a weekly report if possible.

**Comment by nuritzi** [comment]
@leafpetersen or @davidmorgan do you know who might be able to help us pull this kind of report?

**Comment by a-siva** [comment]
Created https://github.com/dart-lang/sdk/issues/50093 to track the Dart VM flag flipping progress.
