### ISSUE TITLE
Error on any use of non-sound null safety in Dart 3

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#49925]
In Dart 3 [only sound null safety will be allowed](https://github.com/dart-lang/sdk/issues/49530). 

This work items describes the gradual roll-out of this change.

### Dart 2.19

- [x] Print an info message in the `dart` tool about the upcoming change: 
https://github.com/dart-lang/sdk/issues/49924
- [x] Print an info message in the `flutter` tool about the upcoming change:
https://github.com/flutter/flutter/pull/110998). 

### Dart 3.0 alpha

After the Dart + Flutter development branches (`main`/`master`) have branched for Dart 3, we need to make the following changes:

- [x] Update the `pub` solver to support [backwards compatibility](https://github.com/dart-lang/sdk/issues/49530) with Dart 2.12 and later packages:
https://github.com/dart-lang/pub/issues/3554
- [x] Change the Dart major version number to `3.0`: 
https://dart-review.git.corp.google.com/c/sdk/+/271922
- [x] Update templates for 3.0:
  - [x] Dart: https://github.com/dart-lang/sdk/issues/50635
  - [x] Flutter: https://github.com/flutter/flutter/issues/116583
- [x] Dart analyzer (whether running in an IDE, in `dart analyze` or `flutter analyze`: Error on any library that has a language version below 2.12, except when the flag `--no-sound-null-safety` is passed
https://github.com/dart-lang/sdk/issues/50694
- [x] `dart run` and `dart compile`: Error on any library that has a language version below 2.12, except when the flag `--no-sound-null-safety` is passed
- [x] `flutter run` and `flutter build`: Error on any library that has a language version below 2.12, except when the flag `--no-sound-null-safety` is passed
- [x] `dart compile js`: ditto
https://github.com/dart-lang/sdk/issues/50345

**Comment by mit-mit** [comment]
cc @leafpetersen @johnniwinther for the part about extending the message/error to cover all tools, is this something we can handle in the CFE and then that would cover all `dart` and `flutter` commands related to Dart source code?
