### ISSUE TITLE
Dart 3 tools changes

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#50707]
This is a meta-issue to discuss, triage, and track tools changes in the Dart 3 release. A core theme of this release is getting rid of historical bagage, so we should look at cleaning up historical tooling artefacts.

# Included in Dart 3
- [x] Deprecate historical CLI tools, and combine everything into the [`dart`](https://dart.dev/tools/dart-tool) tool: 
https://github.com/dart-lang/sdk/issues/46100
- [x] Remove support for `.packages`, now replaced with `.dart_tool/package_config.json`:
https://github.com/dart-lang/sdk/issues/48272
- [x] Hide `dart format --fix` (now `dart fix`):
https://github.com/dart-lang/dart_style/issues/1153
- [x] Cleanup web dev compiler files shipped in the SDK:
https://github.com/dart-lang/sdk/issues/50700
- [x] Remove lints from the linter no longer relevant:
  - [x] https://github.com/dart-lang/linter/issues/3880
  - [x] https://github.com/dart-lang/lints/issues/95
- [x] Remove Dart null safety migration tools, and require using Dart 2.19 for migrations:
https://github.com/dart-lang/sdk/issues/50319, 
https://github.com/dart-lang/pub/pull/3713
  - [x] `dart migrate`
  - [x] `dart pub upgrade --null-safety`
  - [x] `dart pub outdated --mode=null-safety`
- [x] Remove deprecated "strong mode" analyzer mode:
https://github.com/dart-lang/sdk/issues/50679
- [x] Cleanup of various `dart` CLI tool commands:
https://github.com/dart-lang/sdk/issues/50973
- [x] Disable Observatory by-default (should use DevTools):
https://github.com/dart-lang/sdk/commit/edead9cfd17d45dc082715472aef28e2da1fdd5d
- [x] JS compiler flags:
https://github.com/dart-lang/sdk/issues/50711
- [x] Implicit `get` command:
https://github.com/dart-lang/sdk/issues/50422

# Postponed
~~- [ ] Standardized location for user-level SDK files. Currently these are scattered across `~/.pub-cache`, `.dartServer`, `.dart`, `.flutter`,  `.flutter-devtools`, etc.~~
     ~~- [ ] Some `dart` subcommand for managing this location (viewing size, pruning it, etc.)~~
     ~~- [ ] Consider using OS-standard locations for these (e.g. on Windows)~~

**Comment by munificent** [comment]
I started an email to discuss this, but to track it on the issue too:

How about removing `dart format --fix` in favor of `dart fix`?

**Comment by vsmenon** [comment]
@mit-mit - anything we need to land here for the beta?  We still have one item unchecked.

**Comment by vsmenon** [comment]
@pq - only open item here is https://github.com/dart-lang/lints/issues/95.  I assume we don't need that for the beta cut.  Is this something we want for Dart 3 stable?

**Comment by pq** [comment]
@vsmenon: correct. We only want that for stable.

**Comment by mit-mit** [comment]
Yeah, we're good here for beta!

**Comment by vsmenon** [comment]
Anything we need for stable?

**Comment by mit-mit** [comment]
Last issue is https://github.com/dart-lang/lints/issues/95. I'll ping on that.

**Comment by mit-mit** [comment]
All done 🥳
