### ISSUE TITLE
Dart 3 alpha non-SDK blockers

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#50724]
This is a meta-issue used solely to keep track of non-SDK blockers for Dart 3.0 alpha, i.e. issues tracked in other repos.

SDK blockers are tracked [the 3 alpha milestone](https://github.com/dart-lang/sdk/milestone/105).

## pub

- [x] https://github.com/dart-lang/pub/issues/3686, https://dart-review.googlesource.com/c/sdk/+/276780

- [x]  https://github.com/dart-lang/pub/issues/3697
- [x]  https://github.com/dart-lang/pub/issues/3717
- ~~https://github.com/dart-lang/pub/issues/3698~~

## pub.dev
- [x]  https://github.com/dart-lang/pub-dev/pull/6269

**Comment by mit-mit** [comment]
All done 🎆
