### ISSUE TITLE
[Meta] Dart 3.0 CLI Cleanup

### ISSUE THREAD

**Issue by bkonyi** [dart-lang/sdk#50973]
Tracking issue for the Dart 3.0 CLI cleanup effort.

- [x] https://github.com/dart-lang/sdk/issues/50969
- [x] ~~https://github.com/dart-lang/sdk/issues/50970~~ (Not relevant for Dart 3.0)
- [x] https://github.com/dart-lang/sdk/issues/50971
- [x] https://github.com/dart-lang/sdk/issues/50972

**Comment by bkonyi** [comment]
cc @mit-mit

**Comment by mit-mit** [comment]
@bkonyi are you working on these for beta 2?
