### ISSUE TITLE
[Sealed class] Implement the Sealed Class feature

### ISSUE THREAD

**Issue by itsjustkevin** [dart-lang/sdk#51278]
[Feature spec](https://github.com/dart-lang/language/blob/master/accepted/future-releases/sealed-types/feature-specification.md)

- [x] [[Sealed class] Language tests](https://github.com/dart-lang/sdk/issues/51279)
- [x] [[Sealed class] Implement feature in the CFE](https://github.com/dart-lang/sdk/issues/51280)
- [x] [[Sealed class] Analyzer implementation](https://github.com/dart-lang/sdk/issues/51281)
- [x] [[Sealed class] Tests validating as passing(Tracking Via Google Sheet)](https://github.com/dart-lang/sdk/issues/51282)
- [x] [[Sealed class] Syntax highlighters implementation](https://github.com/dart-lang/sdk/issues/51283)
- [x] [[Sealed class] DDC implementation](https://github.com/dart-lang/sdk/issues/51284)
- [x] [[Sealed class] Dart2js implementation](https://github.com/dart-lang/sdk/issues/51286)
- [x] [[Sealed class] VM implementation](https://github.com/dart-lang/sdk/issues/51287)
- [x] [[Sealed class] Build system support](https://github.com/dart-lang/sdk/issues/51288)
- [ ] [[Sealed class] Web debugging support](https://github.com/dart-lang/sdk/issues/51289)
- [x] [[Sealed class] Core library updates](https://github.com/dart-lang/sdk/issues/51290)
- [x] [[Sealed class] Analysis server / IDE support work](https://github.com/dart-lang/sdk/issues/51291)
- [x] [[Sealed class] Cider support](https://github.com/dart-lang/sdk/issues/51292)
- [ ] [[Sealed class] Kythe implementation](https://github.com/dart-lang/sdk/issues/51293)
- [x] [[Sealed class] Angular compiler implementation](https://github.com/dart-lang/sdk/issues/51294)
- [x] [[Sealed class] IntelliJ implementation](https://github.com/dart-lang/sdk/issues/51295)
- [x] [[Sealed class] VM service protocol support](https://github.com/dart-lang/sdk/issues/51296)
- [x] [[Sealed class] VM debugging support](https://github.com/dart-lang/sdk/issues/51297)
- [x] [[Sealed class] Parser implementation](https://github.com/dart-lang/sdk/issues/51298)
- [ ] [[Sealed class] Language feature docs](https://github.com/dart-lang/site-www/issues/4581)

**Comment by vsmenon** [comment]
@leafpetersen - anything you see here as blocking?

**Comment by leafpetersen** [comment]
Nothing here is release blocking.  All of the remaining items should be ticked off before we close this, and preferably before stable.

**Comment by mit-mit** [comment]
cc @itsjustkevin, I think this can be closed?
