### ISSUE TITLE
Dart 3.0 cleanup: Flutter

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#51813]
This is a placeholder in the [Dart 3 cleanup milestone](https://github.com/dart-lang/sdk/milestone/110) to list cleanups that need to happen in Flutter post dart 3.0:

- [x] https://github.com/flutter/flutter/issues/123170
- [x] https://github.com/flutter/flutter/issues/123171
- [x] https://github.com/flutter/flutter/issues/123172
- [x] https://github.com/flutter/flutter/issues/123243
- [x] https://github.com/flutter/flutter/issues/123603

**Comment by goderbauer** [comment]
cc @itsjustkevin

**Comment by goderbauer** [comment]
We've cleaned all known remaining known issues up. I am going to close this.
