### ISSUE TITLE
Analyzer: static warning support for extension types

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#53434]
warnings based on meta annotations:

* [x] `@experimental`, `@internal`, `@protected`, `@visibleForTesting` - does it work on a method declared in an extension type? does it work on a method "implemented" (exposed) via an extension type? If an extension type itself is annotated with any of these, does enforcement work when referencing the extension type? Does enforcement work when referencing/calling the primary constructor?
  * [x] `@experimental` (@pq)
  * [x] `@internal` (@pq)
  * [x] `@protected` (@pq)
  * [x] `@visibleForTesting`  (@pq)
* [x] `@factory` (@pq) 
* [x] `@immutable` (@pq)
* [x] `@literal` - (@pq)
* [x] `@mustBeOverridden` - should be disallowed on methods declared in extension types (and extensions if not already) (@pq)
* [x] `@mustCallSuper` - should be disallowed on methods declared in extension types (and extensions if not already) (@pq)
* [x] `@nonVirtual` - should be disallowed on methods declared in extension types (and extensions if not already) (@pq)
* [x] `@optionalTypeArgs` - can annotate a type extension (@pq https://github.com/dart-lang/sdk/commit/8a5ddecfb3468c9531dd8f1261f50ecec5814ff6)
* [x] `@reopen` - cannot annotate a type extension (or an extension, if not already banned) (@pq)
* [x] `@sealed` - cannot annotate a type extension (or an extension, if not already banned) (@pq)
* [x] `@visibleForOverriding` - cannot annotate a type extension or extension type member (@pq)

other warnings:

* [x] `DEPRECATED_MEMBER_USE` - test against extension type, member declared in extension type, member "implemented" (exposed) by extension type
* [ ] `DIVISION_OPTIMIZATION` - what if x or y are an extension type on int?
* [ ] `INFERENCE_FAILURE_ON_*` - I think tests are needed both for expressions passed to extension type constructor, and extension typed expressions passed elsewhere
* [x] `OVERRIDE_ON_NON_OVERRIDING_*` - for anything declared in an extension type
* [ ] `RETURN_OF_INVALID_TYPE_FROM_CATCH_ERROR` and `RETURN_TYPE_INVALID_FOR_CATCH_ERROR` - return type being an extension type on Future should be ok.
* [x] `STRICT_RAW_TYPE` - should be reported for an extension type missing type arguments. (@pq)
* [x] `UNNECESSARY_TYPE_CHECK` (@pq)
* [x] `UNUSED_ELEMENT` - https://github.com/dart-lang/sdk/issues/53520 (@pq)

**Comment by srawlins** [comment]
Any updates, @pq? Is this still P1?

**Comment by srawlins** [comment]
Closing as more-or-less complete. The remaining work is not worth tracking.
