### ISSUE TITLE
Desupport Windows 7 & 8

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/sdk#54509]
Dart's [system requirements](https://dart.dev/get-dart) currently state that only Windows 10 & 11 are supported. However, we don't currently prevent the `dart` tool and the Dart VM from running on Windows 7 & 8, as a few Flutter customers were still using that support. The Flutter team is now [considering](https://github.com/flutter/flutter/issues/140830) increasing their minimum to Windows 10, so with that, we can go ahead and fully de-support Windows 7 & 8 in Dart too. See the linked Flutter issue for more details.

### Work items

Once we've de-supported these older versions, we can take some steps to further clean up our code base:

* [ ] Announce on Dart Announce
* [x] Put in a check for min Windows 10 when the VM runs, and exit if not
* [x] Reland [fix](https://github.com/dart-lang/sdk/commit/7bdbc0560ed5cd0026bfc57a99583f7ba19a0245) for [vm crash Platform.localHostname Chinese Windows](https://github.com/dart-lang/sdk/issues/52701)
* [x] Clean up unwinding record [dynamic loading](https://github.com/dart-lang/sdk/blob/59b02ea3a1b6d119bfd0c02898786f4cf33ca0f1/runtime/platform/unwinding_records_win.cc#L63) of Windows API functions introduced in Windows 8.
* [x] Remove `IsWindows10OrGreater` check in https://github.com/dart-lang/sdk/blob/main/runtime/bin/eventhandler_win.cc#L155

**Comment by brianquinlan** [comment]
There are some path functions (e.g. PathCchRemoveFileSpec, PathCchCombineEx) that I'd like to use to make our symlink handling more robust on Windows. These functions are only available in Windows 8+.

**Comment by a-siva** [comment]
Once https://github.com/flutter/flutter/issues/140830 is done we can take this up.

**Comment by mit-mit** [comment]
This breaking change has been approved and announced, so you are clear to begin changes for this.

**Comment by mit-mit** [comment]
@itsjustkevin can you help with an announcement post on Dart Announce too (similar to the Flutter one you posted)?

**Comment by aam** [comment]
Check for minimum version was implemented via https://github.com/dart-lang/sdk/commit/74baf5e75a754edff091785586214549124c0c18

**Comment by a-siva** [comment]
https://dart-review.googlesource.com/c/sdk/+/369860 accounts for 'Remove IsWindows10OrGreater check '

**Comment by a-siva** [comment]
@itsjustkevin the only issue left to be resolved is the  announcement post on Dart Announce

**Comment by itsjustkevin** [comment]
Thanks @a-siva ill cook something up tomorrow

**Comment by mit-mit** [comment]
@itsjustkevin was this completed?

**Comment by a-siva** [comment]
Can this issue be closed as done ?

**Comment by Neustradamus** [comment]
Have you tested the support with VxKex?

**Comment by a-siva** [comment]
> Have you tested the support with VxKex?

No and there are no plans to test that configuration.
