### ISSUE TITLE
[Wildcard Variables] [meta] Wildcard variables implementation

### ISSUE THREAD

**Issue by kallentu** [dart-lang/sdk#55673]
## Wildcard Variables
This issue tracks the implementation of the wildcard variables feature.

### References
* [Original issue](https://github.com/dart-lang/language/issues/3712)
* [Feature specification](https://github.com/dart-lang/language/blob/main/working/wildcards/feature-specification.md)
* [Project](https://github.com/orgs/dart-lang/projects/88)
* Test tracking sheet (TBD)

### Work Items (WIP)

- [x] https://github.com/dart-lang/sdk/issues/55661
- [x] https://github.com/dart-lang/sdk/issues/55652
- [x] https://github.com/dart-lang/co19/issues/2641
- [x] https://github.com/dart-lang/sdk/issues/55653
- [x] https://github.com/dart-lang/sdk/issues/55654
- [x] https://github.com/dart-lang/sdk/issues/55655
- [x] https://github.com/dart-lang/sdk/issues/55680
- [x] https://github.com/dart-lang/sdk/issues/55681
- [x] https://github.com/dart-lang/sdk/issues/55750
- [x] https://github.com/dart-lang/sdk/issues/55751
- [x] https://github.com/dart-lang/sdk/issues/55752
- [x] https://github.com/dart-lang/sdk/issues/55765
- [x] https://github.com/dart-lang/dartdoc/issues/3769
- [x] https://github.com/dart-lang/sdk/issues/59471
- [ ] https://github.com/dart-lang/sdk/issues/55706
- [x] https://github.com/dart-lang/sdk/issues/55708
- [x] https://github.com/dart-lang/sdk/issues/55725
- [x] https://github.com/dart-lang/sdk/issues/55726
- [x] https://github.com/dart-lang/sdk/issues/55727
- [x] https://github.com/dart-lang/site-www/issues/5833
  - Deadline: Nov 1st, merge Nov 13th.
* Parser/scanner implementation not necessary.
* VM work not necessary. (Updated May 22)
* VM service protocol support not necessary. (Updated May 15)
* Build system support not necessary. (Updated May 15)
* Angular compiler implementation not necessary. (Updated May 15)
* Dart style support not necessary. (Updated May 16)
* Dart2Wasm implementation not necessary (Updated May 29)

**Comment by kallentu** [comment]
Closing this issue. 🚀 If any other bugs arise, I'll keep track of those, but in general -- we're good to go here.
Wildcard variables are in Dart 3.7!
