### ISSUE TITLE
☂️ Digit separators

### ISSUE THREAD

**Issue by srawlins** [dart-lang/sdk#56188]
We're adding support for digit separators in number literals. For example:

```none
100__000_000__000_000__000_000  // one hundred million million millions!
0x4000_0000_0000_0000
0.000_000_000_01
0x00_14_22_01_23_45  // MAC address
555_123_4567  // US Phone number
```

See the [feature specification](https://github.com/dart-lang/language/blob/main/working/digit-separators/feature-specification.md) for full details.

* [x] Introduce the feature flag (https://dart-review.googlesource.com/c/sdk/+/365181)
* [x] Implement in analyzer and CFE (https://dart-review.googlesource.com/c/sdk/+/365181)
* [x] Update analyzer's `INTEGER_LITERAL_OUT_OF_RANGE` and `INTEGER_LITERAL_IMPRECISE_AS_DOUBLE` reporting (https://dart-review.googlesource.com/c/sdk/+/377861)
* [x] ~~Update analyzer's `from_environment_evaluator`~~ not needed
* [x] Existing lints and quick fixes
  * [x] Test `prefer_int_literals` with separators ([CR 375741](https://dart-review.googlesource.com/c/sdk/+/375741))
  * [x] Update `convert_to_int_literal` to handle separators ([CR 375741](https://dart-review.googlesource.com/c/sdk/+/375741))
  * [x] Update `replace_with_eight_digit_hex` to handle separators ([CR 375780](https://dart-review.googlesource.com/c/sdk/+/375780))
* [x] Add quick fix that removes illegal underscores, as in `100_`, `12_._34`, `12_e_34`.
* [x] Support in IntelliJ (see https://youtrack.jetbrains.com/issue/IDEA-356065/Support-Dart-digit-separators-in-number-literals)
* [x] https://github.com/dart-lang/sdk/issues/56467
* [x] https://github.com/dart-lang/sdk/issues/56187
* [x] Other DAS work
  * [x] Document Colors - Test that hex values with separators are interpreted correctly (https://dart-review.googlesource.com/c/sdk/+/380621)
  * [x] Syntax highlighting (both legacy and LSP) - Test that numbers (ints, doubles, hex, and exponential) with separators are highlighted the same (https://dart-review.googlesource.com/c/sdk/+/380640)
  * [x] Signature Help (VS Code) - If parameter default values are shown, let them be shown with separators.

**Comment by srawlins** [comment]
Done.
