### ISSUE TITLE
:memo: Data Assets Tracker

### ISSUE THREAD

**Issue by mosuem** [dart-lang/sdk#56217]
This issue tracks the progress of adding support for loading assets in Dart at runtime. The assets are added using build and link hooks.

- [ ] Create a library `dart:asset`, containing the API for loading assets.
- [ ] Support web backends
- [ ] Support other embedders (i.e. Flutter)
- [ ] Support storing assets in executables

**Comment by dcharkes** [comment]
Closing as duplicate of:

* https://github.com/dart-lang/sdk/issues/54003
