### ISSUE TITLE
[Null-aware elements] Analyzer implementation

### ISSUE THREAD

**Issue by chloestefantsova** [dart-lang/sdk#56836]
This meta issue tracks all the analyzer implementation work items. Referenced from: https://github.com/dart-lang/sdk/blob/main/pkg/analyzer/doc/process/new_language_feature.md

## Work Items

- [X] AST enhancements (`AstBuilder`)
- [ ] Element model
- [x] ~~Type system updates~~ (should not be affected)
- [ ] Summary support
- [x] ~~Resolution~~ (should not be affected)
  - [x] ~~`ResolutionVisitor`~~ (should not be affected)
  - [x] ~~`ScopeResolverVisitor`~~ (should not be affected)
  - [x] ~~`ResolverVisitor`~~ (should not be affected)
- [x] ~~Index and search~~ (should not be affected)
- [ ] Warnings
  - [x] `ErrorVerifier`
  - [ ] Dead code
    - [ ] Verify the correct dead code detection due to the changes in flow analysis.
- [ ] ExitDetector
- [ ] NodeLintRegistry

**Comment by pq** [comment]
Hi! As part of triage, we look for updates on all `P1` issues. @chloestefantsova, is there anything to update?

**Comment by pq** [comment]
Awesome. Thanks for the update. Cool to see this feature cruising along!
