### ISSUE TITLE
[Dot Shorthands][meta] Dot shorthands implementation

### ISSUE THREAD

**Issue by kallentu** [dart-lang/sdk#57036]
## Dot shorthands
This issue tracks the implementation of the dot shorthands feature.

### References
* [Original issue](https://github.com/dart-lang/language/issues/357)
* [Feature specification](https://github.com/dart-lang/language/blob/main/working/3616%20-%20enum%20value%20shorthand/proposal-simple-lrhn.md)
* [Tracking doc](https://docs.google.com/document/d/1mfxozFP9hXfQUBoeTrSUgw9rucEuNTqY-4KxuKZKcEM/edit?pli=1&tab=t.0#heading=h.xii6f83bmssy)
* [Meta issue](https://github.com/dart-lang/sdk/issues/57036)
* [Project](https://github.com/orgs/dart-lang/projects/104)
* [Test tracking sheet](https://docs.google.com/spreadsheets/d/19L0AhfQjS4VjvkdQ1lz61SZhK_nGjuPzs6OODEUyPx0/edit?usp=sharing&resourcekey=0-UwYFyigOGgtphjW50XztsQ)

### Work Items

- [x] https://github.com/dart-lang/sdk/issues/57037
- [x] https://github.com/dart-lang/sdk/issues/59627
- [x] https://github.com/dart-lang/sdk/issues/57038
- [x] https://github.com/dart-lang/co19/issues/2976
- [x] https://github.com/dart-lang/sdk/issues/59757
- [x] https://github.com/dart-lang/sdk/issues/59758
- [x] https://github.com/dart-lang/sdk/issues/59835
- [x] https://github.com/dart-lang/sdk/issues/59836
- [x] https://github.com/dart-lang/dartdoc/issues/3956
- [x] https://github.com/dart-lang/sdk/issues/59872
- [x] https://github.com/dart-lang/sdk/issues/59873
- [x] https://github.com/dart-lang/sdk/issues/59874
- [x] https://github.com/dart-lang/sdk/issues/59885
- [x] https://github.com/dart-lang/sdk/issues/59875
- [x] https://github.com/dart-lang/site-www/issues/6285
- [ ] https://github.com/dart-lang/sdk/issues/59876
- [x] https://github.com/dart-lang/dart_style/issues/1686
- [x] https://github.com/dart-lang/sdk/issues/60443
- [x] https://github.com/dart-lang/sdk/issues/60444
- [x] https://github.com/dart-lang/sdk/issues/60446
- [x] https://github.com/dart-lang/sdk/issues/60726

**Comment by bwilkerson** [comment]
Is there a reason why the tooling support isn't included in the list?

**Comment by kallentu** [comment]
> Is there a reason why the tooling support isn't included in the list?

I've yet to create the issue and start the prepping process (which includes my personal prep, design meetings, etc). I'll add the issue for tooling support and the other missing issues in the next few days or so.

**Comment by eernstg** [comment]
I added the label 'implementation' because it's nice if all ongoing implementation efforts can be found by having that label.

**Comment by kallentu** [comment]
> > This issue tracks the implementation of the wildcard variables feature.
> 
> there's a typo here, it should say "Enum shorthand feature" instead of "wildcard variables"

Hah, good catch. Fixed.

**Comment by amrgetment** [comment]
Is there a lint ticket to follow for forcing shorthand to all of my enums

**Comment by kallentu** [comment]
> Is there a lint ticket to follow for forcing shorthand to all of my enums

A quickfix will be made in this issue here if you'd like to follow along: https://github.com/dart-lang/sdk/issues/59836

**Comment by munificent** [comment]
I'm working on adding support for dot shorthands in the formatter (https://github.com/dart-lang/dart_style/issues/1686), but I ran into an issue with getting the `const` token for const constructor calls: #60840.
