### ISSUE TITLE
meta issue tracking lints with issues when using optional new/const

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#57712]
Follow up from https://github.com/flutter/flutter/issues/17429; we need to ensure that the lints (esp. the ones in use by Flutter) work when using optional new and const. I think this means:

- [ ] removing new and const from the flutter codebase (@munificent has a handy version of dart_style that does this)
- [ ] running `flutter analyze --flutter-repo` and identifying problematic lints (for example, `Prefer const with constant constructors`)
- [ ] addressing the problematic lints (and getting the optional new/const version of them under test)

@pq, can you take this on?

- [ ] prefer_const_literals_to_create_immutables 
- [x] prefer_const_constructors dart-lang/sdk#57706
