### ISSUE TITLE
[1.0.0] review experimental lints

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#57833]
Pre-release (and really ASAP), we should review the lints currently tagged as experimental and assess:

- [x] `prefer_void_to_null` (#1287)
- [x] `avoid_positional_boolean_parameters` (#1288)
- [x] `prefer_foreach` (#1289)
- [x] `literal_only_boolean_expressions` (#1290)

What's keeping them experimental?

My sense is that where possible we should bump to stable or deprecate.

Thoughts?

/cc @alexeieleusis @MichaelRFairhurst @srawlins @a14n @bwilkerson
