### ISSUE TITLE
[meta] rationalize/align/document different lint rule sets

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#57873]
## Rationalization

The Dart ecosystem has a number of "default" rulesets.

* the `pana` package uses [one](https://github.com/dart-lang/pana/blob/master/lib/src/analysis_options.dart) that should mirror what is used by [`stagehand`](https://github.com/dart-lang/stagehand/blob/master/templates/analysis_options.yaml) but could consider another (for example, [pedantic](https://github.com/dart-lang/pana/issues/459)?)
* [`package:pedantic`](https://github.com/dart-lang/pedantic) describes google standard defaults, which are close but not quite to a subset of those in [Effective Dart](https://github.com/dart-lang/linter/blob/master/example/effective-dart.yaml)
* and what's the rationale for what's defined by stagehand anyway; wouldn't it be better if it just used one of the existing rulesets (https://github.com/dart-lang/stagehand/issues/593)?
* the flutter repo uses still [another](https://github.com/flutter/flutter/blob/master/analysis_options.yaml) and the flutter analyze tool still [one more](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/analysis_options_user.yaml)
* (finally?!?) the `dartanalyzer` tool uses yet another set of rules (https://github.com/dart-lang/sdk/issues/57872)

Needless to say, this is VERY confusing.  Ideally we could converge on one set of defaults with variants well documented.

## Alignment

Concretely, I'd propose we converge on `package:pedantic` where possible.  Specifically, I'd suggest defaults should be:

- [x] `stagehand` : pedantic (https://github.com/dart-lang/stagehand/issues/593)
- [x] `pana` : pedantic (https://github.com/dart-lang/pana/issues/459)
- [x] `dartanalyzer` : none (#1376, https://github.com/dart-lang/sdk/issues/35708)
- [x] `flutter` 
   - [x] repo unchanged
   - [x] ~user: superset of `pedantic`?~ (leave informal for now)

## Documentation

Having aligned as best we can, we'll want to document.  Some thoughts for where:

- [x] `analyzer` package [README](https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/README.md) (shows in pub) [PR](https://dart-review.googlesource.com/c/sdk/+/91681/1)
- [x] `linter` 
    - [x] README
    - [x] ~generated rule docs~
- [x] dart-lang "Customize Static Analysis" [doc](https://www.dartlang.org/guides/language/analysis-options)

/cc @bwilkerson @davidmorgan @kevmoo @mit-mit @stereotype441 @devoncarew @kwalrath
