### ISSUE TITLE
Add lints to help users avoid common Widget anti-patterns.

### ISSUE THREAD

**Issue by jacob314** [dart-lang/sdk#57956]
Motivation from a Flutter user group post: "I've been seeing this a lot with new devs. Don't needlessly use Containers. Wrapping a widget in Container and setting no other parameters does absolutely nothing but make your code more complicated."
These lints could help Flutter examples on the web be more idiomatic with less unneeded boilerplate.

Initial list of lints with obvious quick fixes we could add:
- [x] 1. Container with no parameters other than child --> Remove the container.
- [ ] 2. Center() widget as a leaf node.
- [ ] 3. Wrapping a widget in a Padding even though the widget itself has padding settings. 
- [ ] 4. Using multiple widgets to do something Container can do.
- [ ] 5. Using Align when Center will do (https://github.com/dart-lang/linter/issues/2157)
- [x] 6. No state in constructor https://github.com/dart-lang/linter/issues/1865
- [ ] 7. Incomplete or missing didUpdateWidget method https://github.com/dart-lang/linter/issues/2485
- [ ] 8. Failure to manage listener lifecycles correctly https://github.com/dart-lang/linter/issues/2486
- [ ] 9. Guidance around "implicit" `setState` (https://github.com/flutter/devtools/pull/1336#discussion_r346598595)
- [ ] 10. Nested scroll views (https://github.com/flutter/flutter/issues/92883#issuecomment-957986453)
-  [ ] 10. Your idea here??

**Comment by srawlins** [comment]
We won't be implementing this as a warning or a lint rule in the Dart analyzer. We now have a high bar for implementing and maintaining built-in static analysis rules. As of Dart 3.10 (Flutter 3.38), a [new analyzer plugins system](https://dart.dev/tools/analyzer-plugins) is available, and the requested static analysis here could be implemented as an analyzer plugin.
