### ISSUE TITLE
☂ downstream package updates to prepare for 1.4.0 (and improved `directives_ordering`)

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#58380]
Linter [1.4.0](https://github.com/dart-lang/linter/releases/tag/1.4.0) introduces `directives_ordering` updated to sort more cases (see https://github.com/dart-lang/linter/pull/2596).  In order to land in the Dart SDK ([cl/196581](https://dart-review.googlesource.com/c/sdk/+/196581)), a number of downstream fixes need to be made to SDK and Flutter packages.

Dart SDK:

- [x] https://dart-review.googlesource.com/c/sdk/+/196223
- [x] https://dart-review.googlesource.com/c/sdk/+/196180

Flutter:

- [x] https://github.com/flutter/flutter/pull/81017
- [x] https://github.com/flutter/plugins/pull/3823
- [x] https://github.com/flutter/flutter/pull/80817
- [x] https://github.com/flutter/flutter/pull/80901
- [x] https://github.com/flutter/flutter/pull/81210

...

- [x] https://github.com/flutter/flutter/pull/81220 (disable lint temporarily)
- [x] https://github.com/flutter/flutter/issues/81219 (re-enable once SDK lands)

(Some downstream packages):

* https://github.com/dart-lang/args/pull/193
* https://github.com/dart-lang/gcloud/pull/112
* https://github.com/dart-lang/mime/pull/46
* https://github.com/dart-lang/source_span/pull/76
* https://github.com/dart-lang/io/pull/76
