### ISSUE TITLE
Implement constructor tearoffs support in the linter

### ISSUE THREAD

**Issue by eernstg** [dart-lang/sdk#58424]
This issue tracks support of the [constructor tearoffs feature](https://github.com/dart-lang/language/blob/master/accepted/future-releases/constructor-tearoffs/feature-specification.md).  See the [enclosing meta-issue](https://github.com/dart-lang/sdk/issues/46228) for details.

---

## Rules that need investigation, tests, and possible updating

- [x] [`always_specify_types`](https://dart-lang.github.io/linter/lints/always_specify_types.html) (e.g. catch `List<List>;`, `List<List>.filled;`, ~`someFuture.then<List>`~) (https://github.com/dart-lang/linter/pull/2908)
- [x] `avoid_redundant_argument_values` (#2895)
- [x] ~`prefer_const_constructors`~
- [x] `unnecessary_const` (#2903)
- [x] dart-lang/linter#2911
- [x] dart-lang/linter#2909
- [x] dart-lang/linter#2912
- [x] dart-lang/linter#2910
- [x] `unnecessary_new` (#2902)
- [x] dart-lang/linter#2907
- [x] [`unnecessary_statements`](https://dart-lang.github.io/linter/lints/unnecessary_statements.html) (https://github.com/dart-lang/linter/pull/2901)

## Server updates

- [x] https://github.com/dart-lang/sdk/issues/47102
- [x] https://github.com/dart-lang/sdk/issues/47103

## New lints

- [x] dart-lang/linter#2904 (and https://github.com/dart-lang/site-www/issues/3525)

## Related issues / Future work

*  dart-lang/linter#2928 
*  dart-lang/linter#2914
