### ISSUE TITLE
☂ Improve linter test reliability and maintainability

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#58520]
Our current approach to rule testing leans heavily on expectations being communicated in the source via special comments (e.g., `// LINT`).  This works very well for the simple cases but has accumulated some technical debt over time.

1. the test infrastructure cares only about the specific lint-under-test and discards all other diagnostics.  This has caused a bunch of confusion over the years (see e.g., https://github.com/dart-lang/linter/pull/2752#discussion_r665471015).
2. when testing logic that depends on more than one compilation unit we take an integration test approach, spawning a process and expressing expectations in terms of expected CLI output -- this is slow, unwieldy to debug and brittle wrt to modifications (basically the trouble with golden files).

To get this under control, I'd like to consider a few changes:

- [x] dart-lang/sdk#58448
- [x] move all test data source that has deliberate diagnostics (e.g., parse errors) to dedicated (in-memory) tests
  - [x] https://github.com/dart-lang/linter/issues/2974
  - [x] migrate test logic
- [ ] migrate our approach to multi-file tests (mis-labeled "integration" tests) to in-memory tests a la analyzer
  - [x] https://github.com/dart-lang/linter/issues/2974
  - [ ] migrate existing "integration" tests
