### ISSUE TITLE
☂️  process: define a lint proposal process

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#58538]
*Tracking issue for a light-weight process that brings lint requests that are (intentionally) loose and open-ended to actionable proposals.*

## Goals

The process should be
* lightweight
* open
* formal but not litigious

encourage feedback from
* the community
* platform / language / analyzer teams

and help measure buy-in from
* "canonical" lint owners
* 1P/ Google3 customers
* flutter

Ultimately the goal is to introduce exactly as much process as would benefit taking a lint rule idea to something that might be implemented and widely adopted.

---

## Tasks

- [x] dart-lang/linter#3012
- [x] 🏷️ introduce new issue tags (to identify proposals and reflect status)
   - [x] new labels: `lint proposal`, `status: pending`, `status: accepted`, `status: closed` 
- [x] 🪜 add a new "proposal" issue template (https://github.com/dart-lang/linter/pull/3010)
