### ISSUE TITLE
☂️ linter implementation for enhanced enums

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#58582]
See https://github.com/dart-lang/sdk/issues/47849 for the main tracking issue.

---

## 🛠️  existing lints

- [x] dart-lang/linter#3093 
  - [x] dart-lang/linter#3186
- [x] dart-lang/linter#3094
  - [x] dart-lang/linter#3233
- [x] dart-lang/linter#3095
  - [x] dart-lang/linter#3188 
- [x] dart-lang/linter#3092
- [x] dart-lang/linter#3205
- [x] dart-lang/linter#3096
- [x] enhanced enum support for `camel_case_types` dart-lang/linter#3091
- [x] dart-lang/linter#3195
  - [x] dart-lang/linter#3202 
- [x] dart-lang/linter#3193
- [x] dart-lang/linter#3196
- [ ] dart-lang/linter#3194
- [x] dart-lang/linter#3197
- [x] ~#3191~
- [x] dart-lang/linter#3198
  - [x] dart-lang/linter#3203 
- [x] dart-lang/linter#3190 
- [x] dart-lang/linter#3207
- [x] dart-lang/linter#3208
- [x] dart-lang/linter#3097 
  - [x] dart-lang/linter#3187
- [x] ~#3199~
- [x] dart-lang/linter#3200
  - [x] dart-lang/linter#3204
- [x] dart-lang/linter#3201
  - [x] dart-lang/linter#3235 
- [x] dart-lang/linter#3192

## 💡 new lints

- [x] dart-lang/linter#3173
