### ISSUE TITLE
☂️ linter implementation for super-initializer parameters

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/sdk#58605]
See https://github.com/dart-lang/sdk/issues/48055 for the main tracking issue.

---

## 🛠️  existing lints

- [x] `avoid_annotating_with_dynamic` (https://github.com/dart-lang/linter/pull/3166)
- [x] `avoid_final_parameters` (https://github.com/dart-lang/linter/pull/3159)
- [x] `avoid_init_to_null` (https://github.com/dart-lang/linter/pull/3158)
- [x] `avoid_types_as_parameter_names` (https://github.com/dart-lang/linter/pull/3163)
- [x] `avoid_unused_constructor_parameters` (https://github.com/dart-lang/linter/pull/3162)
- [x] `deprecated_consistency` (https://github.com/dart-lang/linter/pull/3161)
- [x] `library_private_types_in_public_api` (https://github.com/dart-lang/linter/pull/3180)
- [x] `prefer_asserts_in_initializer_lists` (https://github.com/dart-lang/linter/pull/3164)
- [x] `prefer_equal_for_default_values` (https://github.com/dart-lang/linter/pull/3160)
- [x] `tighten_type_of_initializing_formals` (https://github.com/dart-lang/linter/pull/3167)
- [x] `type_init_formals` (https://github.com/dart-lang/linter/pull/3165)
- [x] https://github.com/dart-lang/linter/issues/3211

## 💡 new lints

- [ ] https://github.com/dart-lang/sdk/issues/58595 (new lint) 
- [x] dart-lang/linter#3174
