### ISSUE TITLE
☂️ linter support for patterns 

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#58837]
A meta-issue to discuss and track work on linter support for [patterns](https://github.com/dart-lang/language/blob/master/accepted/future-releases/0546-patterns/feature-specification.md).

**Updates:**

- [ ] https://github.com/dart-lang/linter/issues/4062
- [x] ⚙️ dart-lang/linter#3669 
  * complete pending parser implementation of `pattern-for` statements  
- [ ] 📄 dart-lang/linter#3674
- [x] 🐞 https://github.com/dart-lang/linter/issues/4060
- [x] https://github.com/dart-lang/linter/issues/4049
- [x] dart-lang/linter#3670
- [x] ~#3675~

**Additions:**

- [x] 🦅 ➕ dart-lang/linter#3671 
- [ ] ⚙️ ➕ dart-lang/linter#4044
- [ ] 🤔 ➕ dart-lang/linter#3672
- [ ] 🤔 ➕ dart-lang/linter#3673

---
