### ISSUE TITLE
remove deprecated lints in 3.0

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#58948]
3.0 would be a good time to remove deprecated lints.

Candidates:

- [x] dart-lang/linter#4005
- [x] dart-lang/linter#4009
- [x] dart-lang/linter#4012
- [x] dart-lang/linter#4013
- [x] dart-lang/linter#4014
- [x] dart-lang/linter#4020
  * (replaced by https://github.com/dart-lang/sdk/issues/50694)
