### ISSUE TITLE
[tracking] rename awkward/inconsistent lints

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#58941]
Following up from https://github.com/dart-lang/sdk/issues/58924, this issue tracks renames to handle name awkwardness or inconsistency.

- [ ] dart-lang/sdk#58845 
- [ ] dart-lang/linter#3874
- [ ] proposal: rename `type_init_formals`to `type_initialize_formals` (to be consistent w/ tighten_type_of_initializing_formals) **[recommended]**
