### ISSUE TITLE
remove `test_data` experiment tests

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#59278]
As we migrate away from the `test_data` style of tests, the experiments support should get phased out too.

- [x] dart-lang/linter#4726
- [x] dart-lang/linter#4732
- [x] dart-lang/linter#4728
- [x] dart-lang/linter#4730
- [x] dart-lang/linter#4733
- [x] dart-lang/linter#4727
- [x] dart-lang/linter#4731
- [x] dart-lang/linter#4734

(Note that the the tests should be evaluated and any valuable test cases migrated before deletion.)

---

FWIW, these tests are currently being skipped internally (b/298007178).
