### ISSUE TITLE
[augmentations] linter support

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#59399]
A meta-issue to discuss and track work on linter support for augmentation libraries.

* [Augmentation Libraries Feature Spec](https://github.com/dart-lang/language/blob/main/working/augmentation-libraries/feature-specification.md)

## Existing Lints

Some existing lints will need tests (minimally) and possibly enhanced implementations.

- [x] dart-lang/sdk#59457
- [x] [augmentations] evaluate support for `always_put_control_body_on_new_line`
- [x] dart-lang/sdk#59450
- [x] dart-lang/sdk#59458
- [x] [augmentations] evaluate support for `always_use_package_imports`
- [ ] dart-lang/sdk#59433
- [ ] dart-lang/sdk#59435
- [x] dart-lang/sdk#59459
- [x] [augmentations] evaluate support for `avoid_bool_literals_in_conditional_expressions`
- [x] [augmentations] evaluate support for `avoid_catches_without_on_clauses`
- [x] [augmentations] evaluate support for `avoid_catching_errors`
- [x] dart-lang/sdk#59439
- [x] [augmentations] evaluate support for `avoid_double_and_int_checks`
- [x] [augmentations] evaluate support for `avoid_dynamic_calls`
- [x] [augmentations] evaluate support for `avoid_empty_else`
- [ ] dart-lang/sdk#59440
- [x] [augmentations] evaluate support for `avoid_escaping_inner_quotes`
- [x] dart-lang/sdk#59434
- [x] [augmentations] evaluate support for `avoid_final_parameters`
- [x] [augmentations] evaluate support for `avoid_function_literals_in_foreach_calls`
- [x] [augmentations] evaluate support for `avoid_implementing_value_types`
- [x] [augmentations] evaluate support for `avoid_init_to_null`
- [x] [augmentations] evaluate support for `avoid_js_rounded_ints`
- [x] [augmentations] evaluate support for `avoid_multiple_declarations_per_line`
- [x] [augmentations] evaluate support for `avoid_null_checks_in_equality_operators`
- [x] dart-lang/sdk#59415
- [x] [augmentations] evaluate support for `avoid_print`
- [ ] https://github.com/dart-lang/sdk/issues/59405
- [ ] [augmentations] evaluate support for `avoid_redundant_argument_values`
- [x] [augmentations] evaluate support for `avoid_relative_lib_imports`
- [x] [augmentations] support for `avoid_renaming_method_parameters`
- [x] [augmentations] evaluate support for `avoid_return_types_on_setters`
- [x] [augmentations] evaluate support for `avoid_returning_null_for_void`
- [x] [augmentations] evaluate support for `avoid_returning_this`
- [ ] dart-lang/sdk#59436
- [x] [augmentations] evaluate support for `avoid_shadowing_type_parameters`
- [x] [augmentations] evaluate support for `avoid_single_cascade_in_expression_statements`
- [x] [augmentations] evaluate support for `avoid_slow_async_io`
- [x] [augmentations] evaluate support for `avoid_type_to_string`
- [x] [augmentations] evaluate support for `avoid_types_as_parameter_names`
- [x] [augmentations] evaluate support for `avoid_types_on_closure_parameters`
- [x] [augmentations] evaluate support for `avoid_unnecessary_containers`
- [ ] dart-lang/sdk#59442
- [x] [augmentations] evaluate support for `avoid_void_async`
- [x] [augmentations] evaluate support for `avoid_web_libraries_in_flutter`
- [x] [augmentations] evaluate support for `await_only_futures`
- [x] dart-lang/sdk#59414
- [x] dart-lang/sdk#59400
- [x] [augmentations] evaluate support for `cancel_subscriptions`
- [x] [augmentations] evaluate support for `cascade_invocations`
- [x] [augmentations] evaluate support for `cast_nullable_to_non_nullable`
- [x] [augmentations] evaluate support for `close_sinks`
- [x] [augmentations] evaluate support for `collection_methods_unrelated_type`
- [x] [augmentations] evaluate support for `combinators_ordering`
- [x] [augmentations] evaluate support for `comment_references`
- [x] [augmentations] evaluate support for `conditional_uri_does_not_exist`
- [x] dart-lang/sdk#59441
- [x] [augmentations] evaluate support for `control_flow_in_finally`
- [x] [augmentations] evaluate support for `curly_braces_in_flow_control_structures`
- [x] [augmentations] evaluate support for `dangling_library_doc_comments`
- [x] [augmentations] evaluate support for `depend_on_referenced_packages`
- [x] [augmentations] evaluate support for `deprecated_consistency`
- [ ] [augmentations] evaluate support for `deprecated_member_use_from_same_package`
- [x] [augmentations] evaluate support for `diagnostic_describe_all_properties`
- [x] [augmentations] evaluate support for `directives_ordering`
- [x] [augmentations] evaluate support for `discarded_futures`
- [x] [augmentations] evaluate support for `do_not_use_environment`
- [x] [augmentations] evaluate support for `empty_catches`
- [x] [augmentations] evaluate support for `empty_constructor_bodies`
- [x] [augmentations] evaluate support for `empty_statements`
- [x] [augmentations] evaluate support for `eol_at_end_of_file`
- [x] [augmentations] evaluate support for `erase_dart_type_extension_types`
- [x] [augmentations] evaluate support for `exhaustive_cases`
- [x] [augmentations] evaluate support for `file_names`
- [x] [augmentations] evaluate support for `flutter_style_todos`
- [x] dart-lang/sdk#59437
- [x] [augmentations] evaluate support for `implementation_imports`
- [x] [augmentations] evaluate support for `implicit_call_tearoffs`
- [x] [augmentations] evaluate support for `implicit_reopen`
- [x] [augmentations] evaluate support for `invalid_case_patterns`
- [x] [augmentations] evaluate support for `join_return_with_assignment`
- [x] [augmentations] evaluate support for `leading_newlines_in_multiline_strings`
- [x] [augmentations] evaluate support for `library_annotations`
- [x] [augmentations] evaluate support for `library_names`
- [x] [augmentations] evaluate support for `library_prefixes`
- [x] [augmentations] evaluate support for `library_private_types_in_public_api`
- [x] [augmentations] evaluate support for `lines_longer_than_80_chars`
- [x] [augmentations] evaluate support for `literal_only_boolean_expressions`
- [ ] [augmentations] evaluate support for `matching_super_parameters`
- [x] [augmentations] evaluate support for `missing_whitespace_between_adjacent_strings`
- [x] [augmentations] evaluate support for `no_adjacent_strings_in_list`
- [x] [augmentations] evaluate support for `no_default_cases`
- [x] [augmentations] evaluate support for `no_duplicate_case_values`
- [x] [augmentations] evaluate support for `no_leading_underscores_for_library_prefixes`
- [x] [augmentations] evaluate support for `no_leading_underscores_for_local_identifiers`
- [x] [augmentations] evaluate support for `no_literal_bool_comparisons`
- [x] [augmentations] evaluate support for `no_logic_in_create_state`
- [x] [augmentations] evaluate support for `no_runtimeType_toString`
- [x] [augmentations] evaluate support for `no_self_assignments`
- [x] [augmentations] evaluate support for `no_wildcard_variable_uses`
- [x] dart-lang/sdk#59401
- [x] [augmentations] evaluate support for `noop_primitive_operations`
- [x] [augmentations] evaluate support for `null_check_on_nullable_type_parameter`
- [x] [augmentations] evaluate support for `null_closures`
- [x] [augmentations] evaluate support for `omit_local_variable_types`
- [x] dart-lang/sdk#59432
- [x] [augmentations] evaluate support for `only_throw_errors`
- [x] dart-lang/sdk#59438
- [x] dart-lang/sdk#59451
- [x] [augmentations] evaluate support for `package_names`
- [x] [augmentations] evaluate support for `package_prefixed_library_names`
- [x] [augmentations] evaluate support for `parameter_assignments`
- [x] [augmentations] evaluate support for `prefer_adjacent_string_concatenation`
- [x] [augmentations] evaluate support for `prefer_asserts_in_initializer_lists`
- [x] [augmentations] evaluate support for `prefer_asserts_with_message`
- [x] [augmentations] evaluate support for `prefer_collection_literals`
- [x] [augmentations] evaluate support for `prefer_conditional_assignment`
- [x] dart-lang/sdk#59467
- [x] dart-lang/sdk#59468
- [x] [augmentations] evaluate support for `prefer_const_declarations`
- [x] [augmentations] evaluate support for `prefer_const_literals_to_create_immutables`
- [x] [augmentations] evaluate support for `prefer_constructors_over_static_methods`
- [x] [augmentations] evaluate support for `prefer_contains`
- [x] [augmentations] evaluate support for `prefer_double_quotes`
- [x] [augmentations] evaluate support for `prefer_expression_function_bodies`
- [ ] https://github.com/dart-lang/sdk/issues/59404
- [x] [augmentations] evaluate support for `prefer_final_in_for_each`
- [x] [augmentations] evaluate support for `prefer_final_locals`
- [x] [augmentations] evaluate support for `prefer_final_parameters`
- [x] [augmentations] evaluate support for `prefer_for_elements_to_map_fromIterable`
- [x] [augmentations] evaluate support for `prefer_foreach`
- [x] [augmentations] evaluate support for `prefer_function_declarations_over_variables`
- [x] dart-lang/sdk#59449
- [x] [augmentations] evaluate support for `prefer_if_elements_to_conditional_expressions`
- [x] [augmentations] evaluate support for `prefer_if_null_operators`
- [ ] [augmentations] evaluate support for `prefer_initializing_formals`
- [x] [augmentations] evaluate support for `prefer_inlined_adds`
- [x] [augmentations] evaluate support for `prefer_int_literals`
- [x] [augmentations] evaluate support for `prefer_interpolation_to_compose_strings`
- [x] [augmentations] evaluate support for `prefer_is_empty`
- [x] [augmentations] evaluate support for `prefer_is_not_empty`
- [x] [augmentations] evaluate support for `prefer_is_not_operator`
- [x] [augmentations] evaluate support for `prefer_iterable_whereType`
- [x] [augmentations] evaluate support for `prefer_mixin`
- [x] [augmentations] evaluate support for `prefer_null_aware_method_calls`
- [x] [augmentations] evaluate support for `prefer_null_aware_operators`
- [x] [augmentations] evaluate support for `prefer_relative_imports`
- [x] [augmentations] evaluate support for `prefer_single_quotes`
- [x] [augmentations] evaluate support for `prefer_spread_collections`
- [x] dart-lang/sdk#59460
- [x] dart-lang/sdk#59408
- [x] [augmentations] evaluate support for `provide_deprecation_message`
- [ ] dart-lang/sdk#59419
- [x] [augmentations] evaluate support for `recursive_getters`
- [x] [augmentations] evaluate support for `require_trailing_commas`
- [x] [augmentations] evaluate support for `secure_pubspec_urls`
- [x] [augmentations] evaluate support for `sized_box_for_whitespace`
- [x] [augmentations] evaluate support for `sized_box_shrink_expand`
- [x] [augmentations] evaluate support for `slash_for_doc_comments`
- [x] [augmentations] evaluate support for `sort_child_properties_last`
- [x] [augmentations] evaluate support for `sort_constructors_first`
- [x] [augmentations] evaluate support for `sort_pub_dependencies`
- [x] [augmentations] evaluate support for `sort_unnamed_constructors_first`
- [x] [augmentations] evaluate support for `test_types_in_equals`
- [x] [augmentations] evaluate support for `throw_in_finally`
- [ ] [augmentations] evaluate support for `tighten_type_of_initializing_formals`
- [x] dart-lang/sdk#59411
- [ ] [augmentations] evaluate support for `type_init_formals`
- [x] [augmentations] evaluate support for `type_literal_in_constant_pattern`
- [x] [augmentations] evaluate support for `unawaited_futures`
- [x] [augmentations] evaluate support for `unnecessary_await_in_return`
- [x] [augmentations] evaluate support for `unnecessary_brace_in_string_interps`
- [x] [augmentations] evaluate support for `unnecessary_breaks`
- [ ] [augmentations] evaluate support for `unnecessary_const`
- [ ] [augmentations] evaluate support for `unnecessary_constructor_name`
- [ ] [augmentations] evaluate support for `unnecessary_final`
- [ ] dart-lang/sdk#59443
- [x] [augmentations] evaluate support for `unnecessary_lambdas`
- [ ] [augmentations] evaluate support for `unnecessary_late`
- [x] [augmentations] evaluate support for `unnecessary_library_directive`
- [x] [augmentations] evaluate support for `unnecessary_new`
- [x] [augmentations] evaluate support for `unnecessary_null_aware_assignments`
- [ ] [augmentations] evaluate support for `unnecessary_null_aware_operator_on_extension_on_nullable`
- [x] [augmentations] evaluate support for `unnecessary_null_checks`
- [x] [augmentations] evaluate support for `unnecessary_null_in_if_null_operators`
- [x] [augmentations] evaluate support for `unnecessary_nullable_for_final_variable_declarations`
- [ ] dart-lang/sdk#59418
- [x] [augmentations] evaluate support for `unnecessary_parenthesis`
- [x] [augmentations] evaluate support for `unnecessary_raw_strings`
- [x] [augmentations] evaluate support for `unnecessary_statements`
- [x] [augmentations] evaluate support for `unnecessary_string_escapes`
- [x] [augmentations] evaluate support for `unnecessary_string_interpolations`
- [x] [augmentations] evaluate support for `unnecessary_this`
- [x] [augmentations] evaluate support for `unnecessary_to_list_in_spreads`
- [ ] https://github.com/dart-lang/sdk/issues/59402
- [ ] [augmentations] evaluate support for `unrelated_type_equality_checks`
- [x] [augmentations] evaluate support for `unsafe_html`
- [x] [augmentations] evaluate support for `use_build_context_synchronously`
- [ ] [augmentations] evaluate support for `use_colored_box`
- [ ] [augmentations] evaluate support for `use_decorated_box`
- [ ] dart-lang/sdk#59416
- [x] [augmentations] evaluate support for `use_full_hex_values_for_flutter_colors`
- [x] [augmentations] evaluate support for `use_function_type_syntax_for_parameters`
- [x] [augmentations] evaluate support for `use_if_null_to_convert_nulls_to_bools`
- [x] [augmentations] evaluate support for `use_is_even_rather_than_modulo`
- [x] [augmentations] support for `use_key_in_widget_constructors`
  - [x] https://github.com/dart-lang/sdk/issues/59444 
- [ ] https://github.com/dart-lang/sdk/issues/59403
- [ ] [augmentations] evaluate support for `use_named_constants`
- [x] [augmentations] evaluate support for `use_raw_strings`
- [x] [augmentations] evaluate support for `use_rethrow_when_possible`
- [x] [augmentations] evaluate support for `use_setters_to_change_properties`
- [x] [augmentations] evaluate support for `use_string_buffers`
- [x] [augmentations] evaluate support for `use_string_in_part_of_directives`
- [ ] [augmentations] evaluate support for `use_super_parameters`
- [x] [augmentations] evaluate support for `use_test_throws_matchers`
- [ ] [augmentations] evaluate support for `use_to_and_as_if_applicable`
- [x] [augmentations] evaluate support for `valid_regexps`
- [x] [augmentations] evaluate support for `void_checks`

General questions that have implications for a number of lints:

- [x] https://github.com/dart-lang/sdk/issues/55579
- [x] https://github.com/dart-lang/sdk/issues/55540

## New Lints

Authors and users of macros (and augmentation classes) might benefit from some new lints.

- [ ] dart-lang/sdk#59409

🚧 Feedback welcome! 🚧 

### Visibility

To whom and under what circumstances should we display diagnostics produced in macro generated files?

- [ ] :☂️ determine what, when and how diagnostics in macro-generated files should be displayed
  - [x] https://github.com/dart-lang/language/issues/3346 
- [x] https://github.com/dart-lang/sdk/issues/54875 (pre-release)

/fyi @dart-lang/language-team @bwilkerson @keertip @scheglov @srawlins
