### ISSUE TITLE
[Wildcard Variables] Linter Support

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#59471]
A meta-issue to discuss and track work on linter support for wildcard variables.

* [Wildcards Feature Spec](https://github.com/dart-lang/language/blob/main/working/wildcards/feature-specification.md)

---

## Existing Lints

- [x] [Wildcard Variables] evaluate support for `always_declare_return_types`
- [x] [Wildcard Variables] evaluate support for `always_put_control_body_on_new_line`
- [x] [Wildcard Variables] evaluate support for `always_put_required_named_parameters_first`
- [x] [Wildcard Variables] evaluate support for `always_specify_types`
- [x] [Wildcard Variables] evaluate support for `always_use_package_imports`
- [x] [Wildcard Variables] evaluate support for `annotate_overrides`
- [x] [Wildcard Variables] evaluate support for `annotate_redeclares` [experimental]
- [x] [Wildcard Variables] evaluate support for `avoid_annotating_with_dynamic`
- [x] [Wildcard Variables] evaluate support for `avoid_bool_literals_in_conditional_expressions`
- [x] [Wildcard Variables] evaluate support for `avoid_catches_without_on_clauses`
- [x] [Wildcard Variables] evaluate support for `avoid_catching_errors`
- [x] [Wildcard Variables] evaluate support for `avoid_classes_with_only_static_members`
- [x] [Wildcard Variables] evaluate support for `avoid_double_and_int_checks`
- [x] [Wildcard Variables] evaluate support for `avoid_dynamic_calls`
- [x] [Wildcard Variables] evaluate support for `avoid_empty_else`
- [x] [Wildcard Variables] evaluate support for `avoid_equals_and_hash_code_on_mutable_classes`
- [x] [Wildcard Variables] evaluate support for `avoid_escaping_inner_quotes`
- [x] [Wildcard Variables] evaluate support for `avoid_field_initializers_in_const_classes`
- [x] dart-lang/sdk#59496
- [x] [Wildcard Variables] evaluate support for `avoid_function_literals_in_foreach_calls`
- [x] [Wildcard Variables] evaluate support for `avoid_implementing_value_types`
- [x] [Wildcard Variables] evaluate support for `avoid_init_to_null`
- [x] [Wildcard Variables] evaluate support for `avoid_js_rounded_ints`
- [x] [Wildcard Variables] evaluate support for `avoid_multiple_declarations_per_line`
- [x] [Wildcard Variables] evaluate support for `avoid_null_checks_in_equality_operators`
- [x] [Wildcard Variables] evaluate support for `avoid_positional_boolean_parameters`
- [x] [Wildcard Variables] evaluate support for `avoid_print`
- [x] [Wildcard Variables] evaluate support for `avoid_private_typedef_functions`
- [x] [Wildcard Variables] evaluate support for `avoid_redundant_argument_values`
- [x] [Wildcard Variables] evaluate support for `avoid_relative_lib_imports`
- [x] dart-lang/sdk#59483
- [x] [Wildcard Variables] evaluate support for `avoid_return_types_on_setters`
- [x] [Wildcard Variables] evaluate support for `avoid_returning_null_for_void`
- [x] [Wildcard Variables] evaluate support for `avoid_returning_this`
- [x] [Wildcard Variables] evaluate support for `avoid_setters_without_getters`
- [x] dart-lang/sdk#59497
- [x] [Wildcard Variables] evaluate support for `avoid_single_cascade_in_expression_statements`
- [x] [Wildcard Variables] evaluate support for `avoid_slow_async_io`
- [x] [Wildcard Variables] evaluate support for `avoid_type_to_string`
- [x] dart-lang/sdk#59502
- [x] [Wildcard Variables] evaluate support for `avoid_types_on_closure_parameters`
- [x] [Wildcard Variables] evaluate support for `avoid_unnecessary_containers`
- [x] [Wildcard Variables] support for `avoid_unused_constructor_parameters`
  - [x]  dart-lang/sdk#57125
- [x] [Wildcard Variables] evaluate support for `avoid_void_async`
- [x] [Wildcard Variables] evaluate support for `avoid_web_libraries_in_flutter`
- [x] [Wildcard Variables] evaluate support for `await_only_futures`
- [x] [Wildcard Variables] evaluate support for `camel_case_extensions`
- [x] [Wildcard Variables] evaluate support for `camel_case_types`
- [x] [Wildcard Variables] evaluate support for `cancel_subscriptions`
- [x] [Wildcard Variables] evaluate support for `cascade_invocations`
- [x] [Wildcard Variables] evaluate support for `cast_nullable_to_non_nullable`
- [x] [Wildcard Variables] evaluate support for `close_sinks`
- [x] [Wildcard Variables] evaluate support for `collection_methods_unrelated_type`
- [x] [Wildcard Variables] evaluate support for `combinators_ordering`
- [x] [Wildcard Variables] evaluate support for `comment_references`
- [x] [Wildcard Variables] evaluate support for `conditional_uri_does_not_exist`
- [x] [Wildcard Variables] evaluate support for `constant_identifier_names`
- [x] [Wildcard Variables] evaluate support for `control_flow_in_finally`
- [x] [Wildcard Variables] evaluate support for `curly_braces_in_flow_control_structures`
- [x] [Wildcard Variables] evaluate support for `dangling_library_doc_comments`
- [x] [Wildcard Variables] evaluate support for `depend_on_referenced_packages`
- [x] [Wildcard Variables] evaluate support for `deprecated_consistency`
- [x] [Wildcard Variables] evaluate support for `deprecated_member_use_from_same_package`
- [x] [Wildcard Variables] evaluate support for `diagnostic_describe_all_properties`
- [x] [Wildcard Variables] evaluate support for `directives_ordering`
- [x] [Wildcard Variables] evaluate support for `discarded_futures`
- [x] [Wildcard Variables] evaluate support for `document_ignores`
- [x] [Wildcard Variables] evaluate support for `do_not_use_environment`
- [x] [Wildcard Variables] support for `empty_catches`
  - [x] https://github.com/dart-lang/sdk/issues/57132
- [x] [Wildcard Variables] evaluate support for `empty_constructor_bodies`
- [x] [Wildcard Variables] evaluate support for `empty_statements`
- [x] [Wildcard Variables] evaluate support for `eol_at_end_of_file`
- [x] [Wildcard Variables] evaluate support for `erase_dart_type_extension_types`
- [x] [Wildcard Variables] evaluate support for `exhaustive_cases`
- [x] [Wildcard Variables] evaluate support for `file_names`
- [x] [Wildcard Variables] evaluate support for `flutter_style_todos`
- [x] [Wildcard Variables] evaluate support for `hash_and_equals`
- [x] [Wildcard Variables] evaluate support for `implementation_imports`
- [x] [Wildcard Variables] evaluate support for `implicit_call_tearoffs`
- [x] [Wildcard Variables] evaluate support for `implicit_reopen` [experimental]
- [x] [Wildcard Variables] evaluate support for `invalid_case_patterns` [experimental]
- [x] [Wildcard Variables] evaluate support for `join_return_with_assignment`
- [x] [Wildcard Variables] evaluate support for `invalid_runtime_check_with_js_interop_types`
- [x] [Wildcard Variables] evaluate support for `leading_newlines_in_multiline_strings`
- [x] [Wildcard Variables] evaluate support for `library_annotations`
- [x] [Wildcard Variables] evaluate support for `library_names`
- [x] [Wildcard Variables] evaluate support for `library_prefixes`
  - [x] dart-lang/sdk#59480 
- [x] [Wildcard Variables] evaluate support for `library_private_types_in_public_api`
- [x] [Wildcard Variables] evaluate support for `lines_longer_than_80_chars`
- [x] [Wildcard Variables] evaluate support for `literal_only_boolean_expressions`
- [x] [Wildcard Variables] evaluate support for `matching_super_parameters`
- [x] [Wildcard Variables] evaluate support for `missing_code_block_language_in_doc_comment`
- [x] [Wildcard Variables] evaluate support for `missing_whitespace_between_adjacent_strings`
- [x] [Wildcard Variables] evaluate support for `no_adjacent_strings_in_list`
- [x] [Wildcard Variables] evaluate support for `no_default_cases` [experimental]
- [x] [Wildcard Variables] evaluate support for `no_duplicate_case_values`
- [x] dart-lang/sdk#59490
- [ ] dart-lang/sdk#59491
- [x] [Wildcard Variables] evaluate support for `no_literal_bool_comparisons`
- [x] [Wildcard Variables] evaluate support for `no_logic_in_create_state`
- [x] [Wildcard Variables] evaluate support for `no_runtimeType_toString`
- [x] [Wildcard Variables] evaluate support for `no_self_assignments`
- [ ] [Wildcard Variables] support for `no_wildcard_variable_uses`
  - [ ] https://github.com/dart-lang/sdk/issues/59470
  - [x] https://github.com/dart-lang/sdk/issues/59523
- [x] dart-lang/sdk#59499
- [x] [Wildcard Variables] evaluate support for `noop_primitive_operations`
- [x] [Wildcard Variables] evaluate support for `null_check_on_nullable_type_parameter`
- [x] [Wildcard Variables] evaluate support for `null_closures`
- [x] [Wildcard Variables] evaluate support for `omit_local_variable_types`
- [x] [Wildcard Variables] evaluate support for `omit_obvious_local_variable_types` [experimental]
- [x] [Wildcard Variables] evaluate support for `one_member_abstracts`
- [x] [Wildcard Variables] evaluate support for `only_throw_errors`
- [x] [Wildcard Variables] evaluate support for `overridden_fields`
- [x] [Wildcard Variables] evaluate support for `package_api_docs`
- [x] [Wildcard Variables] evaluate support for `package_names`
- [x] [Wildcard Variables] evaluate support for `package_prefixed_library_names`
- [x] dart-lang/sdk#59492
- [x] [Wildcard Variables] evaluate support for `prefer_adjacent_string_concatenation`
- [x] [Wildcard Variables] evaluate support for `prefer_asserts_in_initializer_lists`
- [x] [Wildcard Variables] evaluate support for `prefer_asserts_with_message`
- [x] [Wildcard Variables] evaluate support for `prefer_collection_literals`
- [x] [Wildcard Variables] evaluate support for `prefer_conditional_assignment`
- [x] [Wildcard Variables] evaluate support for `prefer_const_constructors`
- [x] [Wildcard Variables] evaluate support for `prefer_const_constructors_in_immutables`
- [x] [Wildcard Variables] evaluate support for `prefer_const_declarations`
- [x] [Wildcard Variables] evaluate support for `prefer_const_literals_to_create_immutables`
- [x] [Wildcard Variables] evaluate support for `prefer_constructors_over_static_methods`
- [x] [Wildcard Variables] evaluate support for `prefer_contains`
- [x] [Wildcard Variables] evaluate support for `prefer_double_quotes`
- [x] [Wildcard Variables] evaluate support for `prefer_expression_function_bodies`
- [x] [Wildcard Variables] evaluate support for `prefer_final_fields`
- [x] [Wildcard Variables] evaluate support for `prefer_final_in_for_each`
- [x] dart-lang/sdk#59493
- [x] dart-lang/sdk#59495
- [x] [Wildcard Variables] evaluate support for `prefer_for_elements_to_map_fromIterable`
- [x] [Wildcard Variables] evaluate support for `prefer_foreach`
- [x] [Wildcard Variables] evaluate support for `prefer_function_declarations_over_variables`
- [x] [Wildcard Variables] evaluate support for `prefer_generic_function_type_aliases`
- [x] [Wildcard Variables] evaluate support for `prefer_if_elements_to_conditional_expressions`
- [x] [Wildcard Variables] evaluate support for `prefer_if_null_operators`
- [x] [Wildcard Variables] evaluate support for `prefer_initializing_formals`
- [x] [Wildcard Variables] evaluate support for `prefer_inlined_adds`
- [x] [Wildcard Variables] evaluate support for `prefer_int_literals`
- [x] [Wildcard Variables] evaluate support for `prefer_interpolation_to_compose_strings`
- [x] [Wildcard Variables] evaluate support for `prefer_is_empty`
- [x] [Wildcard Variables] evaluate support for `prefer_is_not_empty`
- [x] [Wildcard Variables] evaluate support for `prefer_is_not_operator`
- [x] [Wildcard Variables] evaluate support for `prefer_iterable_whereType`
- [x] [Wildcard Variables] evaluate support for `prefer_mixin`
- [x] [Wildcard Variables] evaluate support for `prefer_null_aware_method_calls`
- [x] [Wildcard Variables] evaluate support for `prefer_null_aware_operators`
- [x] [Wildcard Variables] evaluate support for `prefer_relative_imports`
- [x] [Wildcard Variables] evaluate support for `prefer_single_quotes`
- [x] [Wildcard Variables] evaluate support for `prefer_spread_collections`
- [x] [Wildcard Variables] evaluate support for `prefer_typing_uninitialized_variables`
- [x] [Wildcard Variables] evaluate support for `prefer_void_to_null`
- [x] [Wildcard Variables] evaluate support for `provide_deprecation_message`
- [x] [Wildcard Variables] evaluate support for `public_member_api_docs`
- [x] [Wildcard Variables] evaluate support for `recursive_getters`
- [x] [Wildcard Variables] evaluate support for `require_trailing_commas`
- [x] [Wildcard Variables] evaluate support for `secure_pubspec_urls`
- [x] [Wildcard Variables] evaluate support for `sized_box_for_whitespace`
- [x] [Wildcard Variables] evaluate support for `sized_box_shrink_expand`
- [x] [Wildcard Variables] evaluate support for `slash_for_doc_comments`
- [x] [Wildcard Variables] evaluate support for `sort_child_properties_last`
- [x] [Wildcard Variables] evaluate support for `sort_constructors_first`
- [x] [Wildcard Variables] evaluate support for `sort_pub_dependencies`
- [x] [Wildcard Variables] evaluate support for `sort_unnamed_constructors_first`
- [x] [Wildcard Variables] evaluate support for `test_types_in_equals`
- [x] [Wildcard Variables] evaluate support for `throw_in_finally`
- [x] [Wildcard Variables] evaluate support for `tighten_type_of_initializing_formals`
- [x] [Wildcard Variables] evaluate support for `type_annotate_public_apis`
- [x] [Wildcard Variables] evaluate support for `type_init_formals`
- [x] [Wildcard Variables] evaluate support for `type_literal_in_constant_pattern`
- [x] [Wildcard Variables] evaluate support for `unawaited_futures`
- [x] [Wildcard Variables] evaluate support for `unintended_html_in_doc_comment`
- [x] [Wildcard Variables] evaluate support for `unnecessary_await_in_return`
- [x] [Wildcard Variables] evaluate support for `unnecessary_brace_in_string_interps`
- [x] [Wildcard Variables] evaluate support for `unnecessary_breaks`
- [x] [Wildcard Variables] evaluate support for `unnecessary_const`
- [x] [Wildcard Variables] evaluate support for `unnecessary_constructor_name`
- [x] dart-lang/linter#5043
- [x] [Wildcard Variables] evaluate support for `unnecessary_getters_setters`
- [x] [Wildcard Variables] evaluate support for `unnecessary_lambdas`
- [x] [Wildcard Variables] evaluate support for `unnecessary_late`
- [x] [Wildcard Variables] evaluate support for `unnecessary_library_directive`
- [x] [Wildcard Variables] evaluate support for `unnecessary_library_name`
- [x] [Wildcard Variables] evaluate support for `unnecessary_new`
- [x] [Wildcard Variables] evaluate support for `unnecessary_null_aware_assignments`
- [x] [Wildcard Variables] evaluate support for `unnecessary_null_aware_operator_on_extension_on_nullable`
- [x] [Wildcard Variables] evaluate support for `unnecessary_null_checks` [experimental]
- [x] [Wildcard Variables] evaluate support for `unnecessary_null_in_if_null_operators`
- [x] [Wildcard Variables] evaluate support for `unnecessary_nullable_for_final_variable_declarations`
- [x] [Wildcard Variables] evaluate support for `unnecessary_overrides`
- [x] [Wildcard Variables] evaluate support for `unnecessary_parenthesis`
- [x] [Wildcard Variables] evaluate support for `unnecessary_raw_strings`
- [x] [Wildcard Variables] evaluate support for `unnecessary_statements`
- [x] [Wildcard Variables] evaluate support for `unnecessary_string_escapes`
- [x] [Wildcard Variables] evaluate support for `unnecessary_string_interpolations`
- [x] [Wildcard Variables] evaluate support for `unnecessary_this`
- [x] [Wildcard Variables] evaluate support for `unnecessary_to_list_in_spreads`
- [x] [Wildcard Variables] evaluate support for `unreachable_from_main`
- [x] [Wildcard Variables] evaluate support for `unrelated_type_equality_checks`
- [x] [Wildcard Variables] evaluate support for `unsafe_html`
- [x] [Wildcard Variables] evaluate support for `use_build_context_synchronously`
- [x] [Wildcard Variables] evaluate support for `use_colored_box`
- [x] [Wildcard Variables] evaluate support for `use_decorated_box`
- [x] [Wildcard Variables] evaluate support for `use_enums`
- [x] [Wildcard Variables] evaluate support for `use_full_hex_values_for_flutter_colors`
- [x] [Wildcard Variables] evaluate support for `use_function_type_syntax_for_parameters`
- [x] [Wildcard Variables] evaluate support for `use_if_null_to_convert_nulls_to_bools`
- [x] [Wildcard Variables] evaluate support for `use_is_even_rather_than_modulo`
- [x] [Wildcard Variables] evaluate support for `use_key_in_widget_constructors`
- [x] [Wildcard Variables] evaluate support for `use_late_for_private_fields_and_variables` [experimental]
- [x] [Wildcard Variables] evaluate support for `use_named_constants`
- [x] [Wildcard Variables] evaluate support for `use_raw_strings`
- [x] [Wildcard Variables] evaluate support for `use_rethrow_when_possible`
- [x] [Wildcard Variables] evaluate support for `use_setters_to_change_properties`
- [x] [Wildcard Variables] evaluate support for `use_string_buffers`
- [x] [Wildcard Variables] evaluate support for `use_string_in_part_of_directives`
- [x] [Wildcard Variables] evaluate support for `use_super_parameters` [experimental]
- [x] [Wildcard Variables] evaluate support for `use_test_throws_matchers`
- [x] [Wildcard Variables] evaluate support for `use_to_and_as_if_applicable`
- [x] [Wildcard Variables] evaluate support for `valid_regexps`
- [x] [Wildcard Variables] evaluate support for `void_checks`

## New Lints
- [ ] dart-lang/sdk#59475
- [ ] https://github.com/dart-lang/sdk/issues/56595
- [x] ~#5077~
- [x] ~https://github.com/dart-lang/sdk/issues/59473~

**Comment by kallentu** [comment]
Closing for now. We seem to be done the work in this area. If there are emerging issues or feature requests, we can reopen.
