### ISSUE TITLE
[enhanced-parts] Linter Support

### ISSUE THREAD

**Issue by pq** [dart-lang/sdk#59482]
A meta-issue to discuss and track work on linter support for enhanced-parts.

* [enhanced-parts feature spec](https://github.com/dart-lang/language/blob/main/working/augmentation-libraries/parts_with_imports.md)
* Experiment flag: `Feature.enhanced_parts`

## Existing Lints

Some existing lints will need tests (minimally) and possibly enhanced implementations.

  - [x] [enhanced-parts] evaluate support for `always_declare_return_types`
  - [x] [enhanced-parts] evaluate support for `always_put_control_body_on_new_line`
  - [x] [enhanced-parts] evaluate support for `always_put_required_named_parameters_first`
  - [x] [enhanced-parts] evaluate support for `always_specify_types`
  - [x] dart-lang/linter#5085
  - [x] [enhanced-parts] evaluate support for `annotate_overrides`
  - [x] [enhanced-parts] evaluate support for `annotate_redeclares` [experimental]
  - [x] [enhanced-parts] evaluate support for `avoid_annotating_with_dynamic`
  - [x] [enhanced-parts] evaluate support for `avoid_bool_literals_in_conditional_expressions`
  - [x] [enhanced-parts] evaluate support for `avoid_catches_without_on_clauses`
  - [x] [enhanced-parts] evaluate support for `avoid_catching_errors`
  - [x] [enhanced-parts] evaluate support for `avoid_classes_with_only_static_members`
  - [x] [enhanced-parts] evaluate support for `avoid_double_and_int_checks`
  - [x] [enhanced-parts] evaluate support for `avoid_dynamic_calls`
  - [x] [enhanced-parts] evaluate support for `avoid_empty_else`
  - [x] [enhanced-parts] evaluate support for `avoid_equals_and_hash_code_on_mutable_classes`
  - [x] [enhanced-parts] evaluate support for `avoid_escaping_inner_quotes`
  - [x] [enhanced-parts] evaluate support for `avoid_field_initializers_in_const_classes`
  - [x] [enhanced-parts] evaluate support for `avoid_final_parameters`
  - [x] [enhanced-parts] evaluate support for `avoid_function_literals_in_foreach_calls`
  - [x] [enhanced-parts] evaluate support for `avoid_implementing_value_types`
  - [x] [enhanced-parts] evaluate support for `avoid_init_to_null`
  - [x] [enhanced-parts] evaluate support for `avoid_js_rounded_ints`
  - [x] [enhanced-parts] evaluate support for `avoid_multiple_declarations_per_line`
  - [x] [enhanced-parts] evaluate support for `avoid_null_checks_in_equality_operators`
  - [x] [enhanced-parts] evaluate support for `avoid_positional_boolean_parameters`
  - [x] [enhanced-parts] evaluate support for `avoid_print`
  - [x] [enhanced-parts] evaluate support for `avoid_private_typedef_functions`
  - [x] [enhanced-parts] evaluate support for `avoid_redundant_argument_values`
  - [x] dart-lang/linter#5080
  - [x] [enhanced-parts] evaluate support for `avoid_renaming_method_parameters`
  - [x] [enhanced-parts] evaluate support for `avoid_return_types_on_setters`
  - [x] [enhanced-parts] evaluate support for `avoid_returning_null_for_void`
  - [x] [enhanced-parts] evaluate support for `avoid_returning_this`
  - [x] [enhanced-parts] evaluate support for `avoid_setters_without_getters`
  - [x] [enhanced-parts] evaluate support for `avoid_shadowing_type_parameters`
  - [x] [enhanced-parts] evaluate support for `avoid_single_cascade_in_expression_statements`
  - [x] [enhanced-parts] evaluate support for `avoid_slow_async_io`
  - [x] [enhanced-parts] evaluate support for `avoid_type_to_string`
  - [x] [enhanced-parts] evaluate support for `avoid_types_as_parameter_names`
  - [x] [enhanced-parts] evaluate support for `avoid_types_on_closure_parameters`
  - [x] [enhanced-parts] evaluate support for `avoid_unnecessary_containers`
  - [x] [enhanced-parts] evaluate support for `avoid_unused_constructor_parameters`
  - [x] [enhanced-parts] evaluate support for `avoid_void_async`
  - [x] [enhanced-parts] evaluate support for `avoid_web_libraries_in_flutter`
  - [x] [enhanced-parts] evaluate support for `await_only_futures`
  - [x] [enhanced-parts] evaluate support for `camel_case_extensions`
  - [x] [enhanced-parts] evaluate support for `camel_case_types`
  - [x] [enhanced-parts] evaluate support for `cancel_subscriptions`
  - [x] [enhanced-parts] evaluate support for `cascade_invocations`
  - [x] [enhanced-parts] evaluate support for `cast_nullable_to_non_nullable`
  - [x] [enhanced-parts] evaluate support for `close_sinks`
  - [x] [enhanced-parts] evaluate support for `collection_methods_unrelated_type`
  - [x] [enhanced-parts] evaluate support for `combinators_ordering`
  - [x] [enhanced-parts] evaluate support for `comment_references`
  - [x] dart-lang/linter#5081
  - [x] [enhanced-parts] evaluate support for `constant_identifier_names`
  - [x] [enhanced-parts] evaluate support for `control_flow_in_finally`
  - [x] [enhanced-parts] evaluate support for `curly_braces_in_flow_control_structures`
  - [x] [enhanced-parts] evaluate support for `dangling_library_doc_comments`
  - [x] [enhanced-parts] evaluate support for `depend_on_referenced_packages`
  - [x] [enhanced-parts] evaluate support for `deprecated_consistency`
  - [x] [enhanced-parts] evaluate support for `deprecated_member_use_from_same_package`
  - [x] [enhanced-parts] evaluate support for `diagnostic_describe_all_properties`
  - [x] [enhanced-parts] evaluate support for `directives_ordering`
  - [x] [enhanced-parts] evaluate support for `discarded_futures`
  - [x] [enhanced-parts] evaluate support for `document_ignores`
  - [x] [enhanced-parts] evaluate support for `do_not_use_environment`
  - [x] [enhanced-parts] evaluate support for `empty_catches`
  - [x] [enhanced-parts] evaluate support for `empty_constructor_bodies`
  - [x] [enhanced-parts] evaluate support for `empty_statements`
  - [x] [enhanced-parts] evaluate support for `eol_at_end_of_file`
  - [x] [enhanced-parts] evaluate support for `erase_dart_type_extension_types`
  - [x] [enhanced-parts] evaluate support for `exhaustive_cases`
  - [x] [enhanced-parts] evaluate support for `file_names`
  - [x] [enhanced-parts] evaluate support for `flutter_style_todos`
  - [x] [enhanced-parts] evaluate support for `hash_and_equals`
  - [x] dart-lang/linter#5082
  - [x] [enhanced-parts] evaluate support for `implicit_call_tearoffs`
  - [x] [enhanced-parts] evaluate support for `implicit_reopen` [experimental]
  - [x] [enhanced-parts] evaluate support for `invalid_case_patterns` [experimental]
  - [x] [enhanced-parts] evaluate support for `join_return_with_assignment`
  - [x] [enhanced-parts] evaluate support for `invalid_runtime_check_with_js_interop_types`
  - [x] [enhanced-parts] evaluate support for `leading_newlines_in_multiline_strings`
  - [x] dart-lang/linter#5084
  - [x] [enhanced-parts] evaluate support for `library_names`
  - [x] [enhanced-parts] evaluate support for `library_prefixes`
  - [x] [enhanced-parts] evaluate support for `library_private_types_in_public_api`
  - [x] [enhanced-parts] evaluate support for `lines_longer_than_80_chars`
  - [x] [enhanced-parts] evaluate support for `literal_only_boolean_expressions`
  - [x] [enhanced-parts] evaluate support for `matching_super_parameters`
  - [x] [enhanced-parts] evaluate support for `missing_code_block_language_in_doc_comment`
  - [x] [enhanced-parts] evaluate support for `missing_whitespace_between_adjacent_strings`
  - [x] [enhanced-parts] evaluate support for `no_adjacent_strings_in_list`
  - [x] [enhanced-parts] evaluate support for `no_default_cases` [experimental]
  - [x] [enhanced-parts] evaluate support for `no_duplicate_case_values`
  - [x] [enhanced-parts] evaluate support for `no_leading_underscores_for_library_prefixes`
  - [x] [enhanced-parts] evaluate support for `no_leading_underscores_for_local_identifiers`
  - [x] [enhanced-parts] evaluate support for `no_literal_bool_comparisons`
  - [x] [enhanced-parts] evaluate support for `no_logic_in_create_state`
  - [x] [enhanced-parts] evaluate support for `no_runtimeType_toString`
  - [x] [enhanced-parts] evaluate support for `no_self_assignments`
  - [x] [enhanced-parts] evaluate support for `no_wildcard_variable_uses`
  - [x] [enhanced-parts] evaluate support for `non_constant_identifier_names`
  - [x] [enhanced-parts] evaluate support for `noop_primitive_operations`
  - [x] [enhanced-parts] evaluate support for `null_check_on_nullable_type_parameter`
  - [x] [enhanced-parts] evaluate support for `null_closures`
  - [x] [enhanced-parts] evaluate support for `omit_local_variable_types`
  - [x] [enhanced-parts] evaluate support for `omit_obvious_local_variable_types` [experimental]
  - [x] [enhanced-parts] evaluate support for `one_member_abstracts`
  - [x] [enhanced-parts] evaluate support for `only_throw_errors`
  - [x] [enhanced-parts] evaluate support for `overridden_fields`
  - [x] [enhanced-parts] evaluate support for `package_api_docs`
  - [x] [enhanced-parts] evaluate support for `package_names`
  - [x] [enhanced-parts] evaluate support for `package_prefixed_library_names`
  - [x] [enhanced-parts] evaluate support for `parameter_assignments`
  - [x] [enhanced-parts] evaluate support for `prefer_adjacent_string_concatenation`
  - [x] [enhanced-parts] evaluate support for `prefer_asserts_in_initializer_lists`
  - [x] [enhanced-parts] evaluate support for `prefer_asserts_with_message`
  - [x] [enhanced-parts] evaluate support for `prefer_collection_literals`
  - [x] [enhanced-parts] evaluate support for `prefer_conditional_assignment`
  - [x] [enhanced-parts] evaluate support for `prefer_const_constructors`
  - [x] [enhanced-parts] evaluate support for `prefer_const_constructors_in_immutables`
  - [x] [enhanced-parts] evaluate support for `prefer_const_declarations`
  - [x] [enhanced-parts] evaluate support for `prefer_const_literals_to_create_immutables`
  - [x] [enhanced-parts] evaluate support for `prefer_constructors_over_static_methods`
  - [x] [enhanced-parts] evaluate support for `prefer_contains`
  - [x] [enhanced-parts] evaluate support for `prefer_double_quotes`
  - [x] [enhanced-parts] evaluate support for `prefer_expression_function_bodies`
  - [x] [enhanced-parts] evaluate support for `prefer_final_fields`
  - [x] [enhanced-parts] evaluate support for `prefer_final_in_for_each`
  - [x] [enhanced-parts] evaluate support for `prefer_final_locals`
  - [x] [enhanced-parts] evaluate support for `prefer_final_parameters`
  - [x] [enhanced-parts] evaluate support for `prefer_for_elements_to_map_fromIterable`
  - [x] [enhanced-parts] evaluate support for `prefer_foreach`
  - [x] [enhanced-parts] evaluate support for `prefer_function_declarations_over_variables`
  - [x] [enhanced-parts] evaluate support for `prefer_generic_function_type_aliases`
  - [x] [enhanced-parts] evaluate support for `prefer_if_elements_to_conditional_expressions`
  - [x] [enhanced-parts] evaluate support for `prefer_if_null_operators`
  - [x] [enhanced-parts] evaluate support for `prefer_initializing_formals`
  - [x] [enhanced-parts] evaluate support for `prefer_inlined_adds`
  - [x] [enhanced-parts] evaluate support for `prefer_int_literals`
  - [x] [enhanced-parts] evaluate support for `prefer_interpolation_to_compose_strings`
  - [x] [enhanced-parts] evaluate support for `prefer_is_empty`
  - [x] [enhanced-parts] evaluate support for `prefer_is_not_empty`
  - [x] [enhanced-parts] evaluate support for `prefer_is_not_operator`
  - [x] [enhanced-parts] evaluate support for `prefer_iterable_whereType`
  - [x] [enhanced-parts] evaluate support for `prefer_mixin`
  - [x] [enhanced-parts] evaluate support for `prefer_null_aware_method_calls`
  - [x] [enhanced-parts] evaluate support for `prefer_null_aware_operators`
  - [x] dart-lang/linter#5083
  - [x] [enhanced-parts] evaluate support for `prefer_single_quotes`
  - [x] [enhanced-parts] evaluate support for `prefer_spread_collections`
  - [x] [enhanced-parts] evaluate support for `prefer_typing_uninitialized_variables`
  - [x] [enhanced-parts] evaluate support for `prefer_void_to_null`
  - [x] [enhanced-parts] evaluate support for `provide_deprecation_message`
  - [x] dart-lang/linter#5090
  - [x] [enhanced-parts] evaluate support for `recursive_getters`
  - [x] [enhanced-parts] evaluate support for `require_trailing_commas`
  - [x] [enhanced-parts] evaluate support for `secure_pubspec_urls`
  - [x] [enhanced-parts] evaluate support for `sized_box_for_whitespace`
  - [x] [enhanced-parts] evaluate support for `sized_box_shrink_expand`
  - [x] [enhanced-parts] evaluate support for `slash_for_doc_comments`
  - [x] [enhanced-parts] evaluate support for `sort_child_properties_last`
  - [x] [enhanced-parts] evaluate support for `sort_constructors_first`
  - [x] [enhanced-parts] evaluate support for `sort_pub_dependencies`
  - [x] [enhanced-parts] evaluate support for `sort_unnamed_constructors_first`
  - [x] [enhanced-parts] evaluate support for `test_types_in_equals`
  - [x] [enhanced-parts] evaluate support for `throw_in_finally`
  - [x] [enhanced-parts] evaluate support for `tighten_type_of_initializing_formals`
  - [x] [enhanced-parts] evaluate support for `type_annotate_public_apis`
  - [x] [enhanced-parts] evaluate support for `type_init_formals`
  - [x] [enhanced-parts] evaluate support for `type_literal_in_constant_pattern`
  - [x] [enhanced-parts] evaluate support for `unawaited_futures`
  - [x] [enhanced-parts] evaluate support for `unintended_html_in_doc_comment`
  - [x] [enhanced-parts] evaluate support for `unnecessary_await_in_return`
  - [x] [enhanced-parts] evaluate support for `unnecessary_brace_in_string_interps`
  - [x] [enhanced-parts] evaluate support for `unnecessary_breaks`
  - [x] [enhanced-parts] evaluate support for `unnecessary_const`
  - [x] [enhanced-parts] evaluate support for `unnecessary_constructor_name`
  - [x] [enhanced-parts] evaluate support for `unnecessary_final`
  - [x] [enhanced-parts] evaluate support for `unnecessary_getters_setters`
  - [x] [enhanced-parts] evaluate support for `unnecessary_lambdas`
  - [x] [enhanced-parts] evaluate support for `unnecessary_late`
  - [x] [enhanced-parts] evaluate support for `unnecessary_library_directive`
  - [x] [enhanced-parts] evaluate support for `unnecessary_library_name`
  - [x] [enhanced-parts] evaluate support for `unnecessary_new`
  - [x] [enhanced-parts] evaluate support for `unnecessary_null_aware_assignments`
  - [x] [enhanced-parts] evaluate support for `unnecessary_null_aware_operator_on_extension_on_nullable`
  - [x] [enhanced-parts] evaluate support for `unnecessary_null_checks` [experimental]
  - [x] [enhanced-parts] evaluate support for `unnecessary_null_in_if_null_operators`
  - [x] [enhanced-parts] evaluate support for `unnecessary_nullable_for_final_variable_declarations`
  - [x] [enhanced-parts] evaluate support for `unnecessary_overrides`
  - [x] [enhanced-parts] evaluate support for `unnecessary_parenthesis`
  - [x] [enhanced-parts] evaluate support for `unnecessary_raw_strings`
  - [x] [enhanced-parts] evaluate support for `unnecessary_statements`
  - [x] [enhanced-parts] evaluate support for `unnecessary_string_escapes`
  - [x] [enhanced-parts] evaluate support for `unnecessary_string_interpolations`
  - [x] [enhanced-parts] evaluate support for `unnecessary_this`
  - [x] [enhanced-parts] evaluate support for `unnecessary_to_list_in_spreads`
  - [x] [enhanced-parts] evaluate support for `unreachable_from_main`
  - [x] [enhanced-parts] evaluate support for `unrelated_type_equality_checks`
  - [x] [enhanced-parts] evaluate support for `unsafe_html`
  - [x] [enhanced-parts] evaluate support for `use_build_context_synchronously`
  - [x] [enhanced-parts] evaluate support for `use_colored_box`
  - [x] [enhanced-parts] evaluate support for `use_decorated_box`
  - [x] [enhanced-parts] evaluate support for `use_enums`
  - [x] [enhanced-parts] evaluate support for `use_full_hex_values_for_flutter_colors`
  - [x] [enhanced-parts] evaluate support for `use_function_type_syntax_for_parameters`
  - [x] [enhanced-parts] evaluate support for `use_if_null_to_convert_nulls_to_bools`
  - [x] [enhanced-parts] evaluate support for `use_is_even_rather_than_modulo`
  - [x] [enhanced-parts] evaluate support for `use_key_in_widget_constructors`
  - [x] [enhanced-parts] evaluate support for `use_late_for_private_fields_and_variables` [experimental]
  - [x] [enhanced-parts] evaluate support for `use_named_constants`
  - [x] [enhanced-parts] evaluate support for `use_raw_strings`
  - [x] [enhanced-parts] evaluate support for `use_rethrow_when_possible`
  - [x] [enhanced-parts] evaluate support for `use_setters_to_change_properties`
  - [x] [enhanced-parts] evaluate support for `use_string_buffers`
  - [x] dart-lang/linter#5026
  - [x] [enhanced-parts] evaluate support for `use_super_parameters` [experimental]
  - [x] [enhanced-parts] evaluate support for `use_test_throws_matchers`
  - [x] [enhanced-parts] evaluate support for `use_to_and_as_if_applicable`
  - [x] [enhanced-parts] evaluate support for `valid_regexps`
  - [x] [enhanced-parts] evaluate support for `void_checks`

## General Part Support

There are a number of outstanding issues with our support for parts. In support of this feature (and in anticipation) of greater adoption of parts, we might consider prioritizing some fixes.

- [x] ~~https://github.com/dart-lang/sdk/issues/59452~~
- [x] https://github.com/dart-lang/sdk/issues/58095
- [x] https://github.com/dart-lang/sdk/issues/58428

**Comment by FMorschel** [comment]
Is there still work to be done here @pq?

**Comment by pq** [comment]
Yeah. There likely is. We've just paused it for now.

**Comment by davidmorgan** [comment]
@pq I'm checking in on the status of Parts With Imports, previously known as Enhanced Parts.

Do you think there is much more to do here?

Thanks.

**Comment by bwilkerson** [comment]
It isn't clear whether the state in the initial comment is up to date or whether some items need to be unchecked because of comments further down in the issue. It's also possible that there are new lints added since this issue was created.

I think it will require a complete re-analysis of the situation.

**Comment by pq** [comment]
It's hard to remember the state of the world in 2024 and we did kind of abruptly pause this work. Which is to say I agree with Brian

> I think it will require a complete re-analysis of the situation.

💯

**Comment by bwilkerson** [comment]
Closing in favor of https://github.com/dart-lang/sdk/issues/63725 so that we have a clean slate.
