### ISSUE TITLE
☔  Deprecate legacy HTML/JS libraries/packages

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#59716]
- [x] Mark legacy dart: libraries as deprecated
- [x] Mark https://pub.dev/packages/js as discontinued
  - [x] Publish https://pub.dev/packages/js with APIs annotated as deprecated
  - [x] Mark pkg:js discontinued once pub.dev rolls to Dart 3.7

**Comment by ahmednfwela** [comment]
Shouldn't all the [missing api](https://github.com/dart-lang/web/labels/area-api-missing) issues be solved before deprecating old packages? this way consumers can have a clear migration path.

**Comment by srujzs** [comment]
That tag covers more than just "missing from package:web but are in the web libraries", so it isn't necessarily an indicator of migrate-ability.

Something would be a blocker if a functionality was exposed before which has no alternative or workaround in either `package:web` or `dart:js_interop(_unsafe)` that wasn't intended by design (e.g. dynamic dispatch). On a brief pass, I don't see that as the case for any of those issues. Of course, if something is *very* confusing or annoying to deal with for users, then we should prioritize those issues and consider that as a blocker.

The motivation behind this is to avoid further proliferation of legacy interop code and eventually get it down to a point where the ecosystem can move forward with Wasm easily.

**Comment by ahmednfwela** [comment]
This was also discusses a while back https://github.com/dart-lang/sdk/issues/56358 and I have raised the same concern

**Comment by srujzs** [comment]
There's a canonical issue for typing JS functions: https://dart-review.googlesource.com/c/sdk/+/401046. There are some downsides to generating typed `JSFunction`s everywhere in `package:web` but I think it'd be a net positive.

**Comment by mit-mit** [comment]
Hey @kevmoo is the last checkmark item done now?
